// ios-app-frontend/src/views/Profile.vue
<template>
  <div class="app-shell">
    <div class="hero-bg">
      <button class="hero-notif" aria-label="通知" @click="$router.push('/notifications')">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18.134 11C18.715 16.375 21 18 21 18H3s3-2.133 3-9.6c0-1.697.632-3.325 1.757-4.525S10.41 2 12 2q.507 0 1 .09M19 8a3 3 0 1 0 0-6a3 3 0 0 0 0 6m-5.27 13a2 2 0 0 1-3.46 0"/></svg>
      </button>
    </div>
    <div class="profile-card anim-fade-up">
      <div class="profile-avatar"><img :src="avatarUrl" alt="头像" loading="lazy"></div>
      <div class="profile-info">
        <div class="profile-username">{{ userName }}</div>
        <div class="profile-id">ID: {{ userIdShort }}</div>
        <div v-if="regionText" class="profile-region">📍 {{ regionText }}</div>
      </div>
      <div class="stats-row anim-fade-up anim-delay-1">
        <div class="stat-item"><div class="stat-num">{{ reviewCount }}</div><div class="stat-label">评测</div></div>
        <div class="stat-item"><div class="stat-num">{{ profile?.trust_score ?? '--' }}</div><div class="stat-label">信任分</div></div>
        <div class="stat-item"><div class="stat-num">0</div><div class="stat-label">粉丝</div></div>
        <div class="stat-item"><div class="stat-num">0</div><div class="stat-label">关注</div></div>
      </div>
      <div class="profile-actions anim-fade-up anim-delay-2">
        <button class="action-btn primary" @click="$router.push('/edit-profile')">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>
          编辑资料
        </button>
        <button class="action-btn secondary" @click="$router.push('/settings')">
          <svg viewBox="0 0 1024 1024" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="M553.7 753.4h-59.9c-12.8 0-23.3-10.4-23.3-23.3v-52c-10.8-3.4-21.2-7.7-31.2-13l-32.1 32.1c-5.5 5.5-13.2 8.6-21.2 8.6s-15.7-3.2-21.2-8.7l-37.6-37.6c-5.7-5.7-8.8-13.2-8.8-21.2s3.1-15.5 8.8-21.2l32.1-32.1c-5.2-10-9.6-20.4-12.9-31.2H301c-16.5 0-29.9-13.4-29.9-29.9v-53.2c0-16.5 13.4-29.9 29.9-29.9h45.3c3.4-10.8 7.7-21.2 12.9-31.2l-32.1-32.1c-5.7-5.7-8.8-13.2-8.8-21.2s3.1-15.5 8.8-21.2l37.7-37.7c5.5-5.5 13.2-8.6 21.2-8.6s15.7 3.2 21.2 8.7l32 32c10-5.3 20.5-9.6 31.2-13v-52c0-12.8 10.4-23.3 23.3-23.3h59.9c16.5 0 29.9 13.4 29.9 29.9v45.3c10.8 3.4 21.2 7.7 31.2 13l32.1-32.1c5.5-5.5 13.2-8.6 21.2-8.6s15.7 3.2 21.2 8.7l37.6 37.6c5.7 5.7 8.8 13.2 8.8 21.2s-3.1 15.5-8.8 21.2l-32.1 32.1c5.2 10 9.6 20.4 12.9 31.2h45.3c16.5 0 29.9 13.4 29.9 29.9V524c0 16.5-13.4 29.9-29.9 29.9h-45.3c-3.4 10.8-7.7 21.2-12.9 31.2l32.1 32.1c5.7 5.7 8.8 13.2 8.8 21.2s-3.1 15.5-8.8 21.2l-37.7 37.7c-5.5 5.5-13.2 8.6-21.2 8.6s-15.7-3.2-21.2-8.7l-32-32c-10 5.3-20.5 9.6-31.2 13v45.3c0.1 16.5-13.3 29.9-29.8 29.9z m-54-29.2h54l0.8-68.6 11.1-2.7c15.6-3.8 30.5-10 44.2-18.3l9.8-5.9 48 48 38.8-37.6-48-49.1 5.9-9.8c8.3-13.7 14.5-28.6 18.3-44.2l2.7-11.1h67.8l0.8-0.8v-53.2l-68.6-0.8-2.7-11.1c-3.9-15.6-10-30.5-18.3-44.2l-5.9-9.8 48-48-37.6-38.8-49.1 48-9.8-5.9c-13.8-8.3-28.7-14.5-44.2-18.3l-11.1-2.7v-67.8l-54.8-0.7v68.5l-11.1 2.7c-15.6 3.8-30.5 10-44.2 18.3l-9.8 5.9-48-48-38.8 37.6 48 49.1-5.9 9.8c-8.3 13.7-14.5 28.6-18.3 44.2L369 470h-68l-0.8 54 68.6 0.8 2.7 11.1c3.9 15.6 10 30.5 18.3 44.2l5.9 9.8-48 48 37.6 38.8 49.1-48 9.8 5.9c13.8 8.3 28.7 14.5 44.2 18.3l11.1 2.7v68.6z" fill="#2c2c2c"/><path d="M527.1 599.5c-56.3 0-102.1-45.8-102.1-102.1s45.8-102.1 102.1-102.1 102.1 45.8 102.1 102.1-45.9 102.1-102.1 102.1z m0-175c-40.2 0-72.9 32.7-72.9 72.9s32.7 72.9 72.9 72.9 72.9-32.7 72.9-72.9-32.7-72.9-72.9-72.9z" fill="#2c2c2c"/></svg>
          设置
        </button>
      </div>
      <div class="divider"></div>
      <div class="pet-selector">
        <div v-for="pet in pets" :key="pet.id" class="pet-chip" :class="{ active: selectedPet === pet.id }" @click="selectedPet = pet.id" @dblclick="$router.push('/pets/' + pet.id)">
          <div class="pet-chip-avatar">{{ pet.emoji }}</div>
          <span class="pet-chip-name">{{ pet.name }}</span>
        </div>
        <div class="pet-chip" style="border-style:dashed;color:var(--muted)" @click="$router.push('/pet/create')">
          <div class="pet-chip-avatar" style="background:transparent;font-size:16px">+</div>
          <span class="pet-chip-name">添加</span>
        </div>
      </div>
      <div class="profile-body">
        <div class="glass-card">
          <div class="glass-card-header"><div class="glass-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/></svg>饮食日志</div><span class="glass-card-more">全部 <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg></span></div>
          <div class="record-item" v-for="l in dietLogs" :key="l.id"><div class="record-icon diet">{{ l.icon }}</div><div class="record-content"><div class="record-name">{{ l.name }}</div><div class="record-desc">{{ l.desc }}</div></div><span class="record-time">{{ l.time }}</span></div>
          <div v-if="!dietLogs.length" class="record-item"><div class="record-content"><div class="record-name" style="color:var(--muted)">暂无饮食记录</div></div></div>
        </div>
        <div class="glass-card">
          <div class="glass-card-header"><div class="glass-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>健康记录</div><span class="glass-card-badge">{{ healthRecords.length }} 条</span></div>
          <div class="record-item" v-for="r in healthRecords" :key="r.id"><div class="record-icon" :class="r.type">{{ r.icon }}</div><div class="record-content"><div class="record-name">{{ r.name }}</div><div class="record-desc">{{ r.desc }}</div></div><span class="record-time">{{ r.date }}</span></div>
          <div v-if="!healthRecords.length" class="record-item"><div class="record-content"><div class="record-name" style="color:var(--muted)">暂无健康记录</div></div></div>
        </div>
        <div class="glass-card">
          <div class="glass-card-header"><div class="glass-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a4 4 0 0 0-4 4c0 2 2 4 4 6 2-2 4-4 4-6a4 4 0 0 0-4-4z"/><path d="M20 21H4"/></svg>体重趋势</div>
            <button class="add-btn" @click="showWeightForm = !showWeightForm">{{ showWeightForm ? '收起' : '+ 记录' }}</button>
          </div>
          <div v-if="showWeightForm" class="weight-form">
            <input v-model="newWeight" type="number" step="0.1" min="0" class="weight-input" placeholder="输入体重（kg）" />
            <button class="weight-submit" :disabled="!newWeight || weightSaving" @click="handleAddWeight">{{ weightSaving ? '记录中' : '记录' }}</button>
          </div>
          <div class="weight-mini">
            <div>
              <div class="weight-mini-value">{{ latestWeight }} <span style="font-size:14px;font-weight:400;color:var(--muted)">kg</span></div>
              <div class="weight-mini-label">最新体重</div>
            </div>
            <div class="weight-bar-chart">
              <div v-for="(item, idx) in weightChartData" :key="idx" class="weight-bar-item" @click="handleDeleteWeight(item.id, item.value, item.label)">
                <div class="weight-bar-value">{{ item.value }}</div>
                <div class="weight-bar" :style="{ height: item.height + 'px' }"></div>
                <div class="weight-bar-label">{{ item.label }}</div>
              </div>
            </div>
          </div>
        </div>
        <div class="glass-card">
          <div class="glass-card-header">
            <div class="glass-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>过敏信息</div>
            <button v-if="!showAllergyForm" class="add-btn" @click="showAllergyForm = true">+ 添加</button>
          </div>
          <div class="allergy-tags">
            <span v-for="a in allergyTags" :key="a.id" class="allergy-tag">
              {{ a.allergen }} · {{ a.severityLabel }}
              <button class="allergy-del" @click.stop="onDeleteAllergy(a.id, a.confirmed)">×</button>
            </span>
            <span v-if="!allergyTags.length && !showAllergyForm" class="allergy-tag" style="color:var(--muted);background:rgba(0,0,0,.04);border-color:transparent">暂无</span>
          </div>
          <div v-if="showAllergyForm" class="allergy-form">
            <input v-model="newAllergen" class="allergy-input" placeholder="过敏原名称，如：鸡肉、谷物" />
            <div class="allergy-form-row">
              <select v-model="newSeverity" class="allergy-select">
                <option value="mild">轻微</option>
                <option value="moderate">中度</option>
                <option value="severe">严重</option>
              </select>
              <label class="allergy-check"><input type="checkbox" v-model="newConfirmed" /> 已确认</label>
            </div>
            <div class="allergy-form-actions">
              <button class="allergy-submit" :disabled="!newAllergen.trim()" @click="onAddAllergy">添加</button>
              <button class="allergy-cancel" @click="showAllergyForm = false">取消</button>
            </div>
          </div>
        </div>
        <div class="glass-card" style="margin-bottom:20px">
          <div class="glass-card-header"><div class="glass-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>健康事件</div></div>
          <div class="timeline">
            <div class="timeline-item" v-for="ev in healthEvents" :key="ev.date + ev.text"><div class="timeline-dot"></div><div class="timeline-date">{{ ev.date }}</div><div class="timeline-text">{{ ev.text }}</div></div>
            <div v-if="!healthEvents.length" class="timeline-item"><div class="timeline-text" style="color:var(--muted)">暂无健康事件</div></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <TabBar active-tab="profile" />
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { Toast } from 'tdesign-mobile-vue'
import TabBar from '../components/TabBar.vue'
import { useAuth } from '../composables/useAuth'
import { usePets } from '../composables/usePets'
import { useDietLogs } from '../composables/useDietLogs'
import { useHealthRecords } from '../composables/useHealthRecords'

const { profile, user } = useAuth()
const { pets: rawPets, fetchPets, updatePet } = usePets()
const { dietLogs: rawDietLogs, fetchDietLogs } = useDietLogs()
const { healthRecords: rawHealth, weightRecords, allergies, timeline, fetchHealthRecords, fetchAllergies, addAllergy, deleteAllergy, addHealthRecord, deleteHealthRecord } = useHealthRecords()

const selectedPet = ref(null)
const showWeightForm = ref(false)
const newWeight = ref('')
const weightSaving = ref(false)

const SPECIES_EMOJI = { cat: '🐱', dog: '🐶' }
const FOOD_ICON = { dry_food: '🍖', wet_food: '🐟', water: '💧', treat: '🦴', default: '🍽️' }
const RECORD_ICON = { vaccination: '💉', symptom: '🩺', medication: '💊', diagnosis: '📋', checkup: '🩻', weight: '⚖️' }
const SEVERITY_LABEL = { mild: '轻度', moderate: '中度', severe: '重度' }

const userName = computed(() => profile.value?.display_name || profile.value?.username || '铲屎官')
const userIdShort = computed(() => {
  const num = profile.value?.user_number
  if (num) return `nuzzmily${String(num).padStart(3, '0')}`
  return 'nuzzmily000'
})
const avatarUrl = computed(() => profile.value?.avatar_url || '/mqpyqgao-logo.png')
const regionText = computed(() => {
  const r = profile.value?.region || ''
  if (!r) return ''
  return r.replace('·', ' ')
})
const reviewCount = computed(() => profile.value?.review_count || 0)

const pets = computed(() => rawPets.value.map(p => ({
  id: p.id, name: p.name, emoji: SPECIES_EMOJI[p.species] || '🐾'
})))

const dietLogs = computed(() => rawDietLogs.value.slice(0, 3).map(l => ({
  id: l.id, icon: FOOD_ICON[l.food_type] || FOOD_ICON.default,
  name: l.food_name, desc: l.notes || l.food_type,
  time: (l.created_at || l.logged_date || '').slice(11, 16) || '—'
})))

const healthRecords = computed(() => rawHealth.value.slice(0, 3).map(r => ({
  id: r.id, icon: RECORD_ICON[r.record_type] || '📋', type: r.record_type,
  name: r.diagnosis || r.medication_name || r.record_type,
  desc: r.notes || '', date: (r.record_time || '').slice(5, 10)
})))

const latestWeight = computed(() => {
  const w = weightRecords.value[0]?.weight_kg
  return w ? Number(w).toFixed(1) : '--'
})

const weightChartData = computed(() => {
  const records = weightRecords.value.slice(0, 7).reverse()
  const weights = records.map(r => Number(r.weight_kg))
  const maxWeight = Math.max(...weights)
  const minWeight = Math.min(...weights)
  const range = maxWeight - minWeight || 1

  return records.map((record, idx) => {
    const weight = Number(record.weight_kg)
    const normalized = (weight - minWeight) / range
    const height = 15 + normalized * 25
    const date = new Date(record.record_time)
    const label = `${date.getMonth() + 1}/${date.getDate()}`
    return { id: record.id, value: weight.toFixed(1), height, label }
  })
})

const allergyTags = computed(() => allergies.value.map(a => ({
  id: a.id, allergen: a.allergen, severityLabel: SEVERITY_LABEL[a.severity] || '', confirmed: a.confirmed
})))

const showAllergyForm = ref(false)
const newAllergen = ref('')
const newSeverity = ref('mild')
const newConfirmed = ref(false)

async function handleAddWeight() {
  if (!newWeight.value || !selectedPet.value) return
  weightSaving.value = true
  try {
    const kg = Math.round(Number(newWeight.value) * 100) / 100
    await addHealthRecord({
      pet_id: selectedPet.value,
      record_type: 'weight',
      weight_kg: kg,
      record_time: new Date().toISOString()
    })
    await updatePet(selectedPet.value, { weight_kg: kg })
    Toast({ theme: 'success', message: '体重已记录' })
    newWeight.value = ''
    showWeightForm.value = false
    fetchHealthRecords(selectedPet.value)
  } catch (e) {
    Toast({ theme: 'error', message: e.message || '记录失败' })
  } finally {
    weightSaving.value = false
  }
}

async function handleDeleteWeight(id, value, label) {
  if (!confirm(`确定要删除 ${label} 的体重记录（${value} kg）吗？`)) return
  try {
    await deleteHealthRecord(id)
    Toast({ theme: 'success', message: '已删除' })
    fetchHealthRecords(selectedPet.value)
  } catch (e) {
    Toast({ theme: 'error', message: e.message || '删除失败' })
  }
}

async function onAddAllergy() {
  if (!newAllergen.value.trim() || !selectedPet.value) return
  try {
    await addAllergy({
      pet_id: selectedPet.value,
      allergen: newAllergen.value.trim(),
      severity: newSeverity.value,
      confirmed: newConfirmed.value
    })
    Toast({ theme: 'success', message: '过敏原已添加' })
    newAllergen.value = ''
    newSeverity.value = 'mild'
    newConfirmed.value = false
    showAllergyForm.value = false
  } catch (e) {
    Toast({ theme: 'error', message: e.message || '添加失败' })
  }
}

async function onDeleteAllergy(id, isConfirmed) {
  if (isConfirmed && !confirm('该过敏原已确认，确定要删除吗？')) return
  try {
    await deleteAllergy(id)
    Toast({ theme: 'success', message: '过敏原已删除' })
  } catch (e) {
    Toast({ theme: 'error', message: e.message || '删除失败' })
  }
}

const healthEvents = computed(() => timeline.value.slice(0, 4))

async function loadAll(petId) {
  await Promise.all([fetchHealthRecords(petId), fetchDietLogs(petId)])
  if (petId) fetchAllergies(petId)
}

onMounted(async () => {
  await fetchPets()
  if (pets.value.length) selectedPet.value = pets.value[0].id
})

watch(selectedPet, (id) => { if (id) loadAll(id) })
</script>

<style scoped>
.app-shell{width:100%;min-height:100vh;min-height:100dvh;padding-top:0;padding-bottom:calc(88px + var(--safe-bottom));overflow-y:auto;overflow-x:hidden;-webkit-overflow-scrolling:touch}
.hero-bg{width:100%;height:calc(clamp(180px,45vh,220px) + var(--safe-top));background:url('/scene graph.png') center bottom/cover no-repeat;position:fixed;top:0;left:0;right:0;z-index:0}
.hero-notif{position:absolute;top:calc(var(--safe-top) + 16px);right:16px;width:41.31px;height:41.31px;border-radius:50%;background:rgba(255,255,255,.72);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);box-shadow:0 2px 12px rgba(0,0,0,.1);display:flex;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.6);cursor:pointer;transition:transform .2s}
.hero-notif:active{transform:scale(.9)}
.hero-notif svg{width:20px;height:20px;color:var(--fg)}
.profile-card{background:var(--card);border-radius:var(--radius-card) var(--radius-card) 0 0;margin-top:calc(clamp(180px,45vh,220px) + var(--safe-top) - 36px);position:relative;z-index:1;padding-top:36px;padding-bottom:12px}
.profile-avatar{position:absolute;top:-36px;right:28px;width:clamp(60px,18vw,80px);aspect-ratio:1;border-radius:50%;border:3px solid var(--card);box-shadow:0 4px 16px rgba(0,0,0,.1);overflow:hidden;background:linear-gradient(135deg,var(--beige),var(--brown));display:flex;align-items:center;justify-content:center;z-index:2}
.profile-avatar img{width:100%;height:100%;object-fit:cover}
.profile-info{padding:0 28px;padding-right:clamp(100px,25vw,144px);display:flex;flex-direction:column;gap:4px}
.profile-username{font-family:var(--font-display);font-size:24px;font-weight:700;letter-spacing:-.02em;color:var(--fg);line-height:1.2}
.profile-id{font-size:13px;color:var(--muted);letter-spacing:.01em}
.profile-region{font-size:12px;color:var(--muted);margin-top:2px}
.stats-row{display:flex;justify-content:space-around;padding:16px 28px 0}
.stat-item{display:flex;flex-direction:column;align-items:center;gap:4px;cursor:pointer}
.stat-item:active{opacity:.7}
.stat-num{font-family:var(--font-num);font-size:20px;font-weight:600;line-height:1;letter-spacing:-.02em;color:var(--fg)}
.stat-label{font-size:12px;color:var(--muted);letter-spacing:.01em}
.profile-actions{display:flex;gap:12px;padding:16px 28px 0}
.action-btn{flex:1;height:44px;border-radius:var(--radius-btn);display:flex;align-items:center;justify-content:center;gap:6px;font-size:14px;font-weight:500;letter-spacing:.01em;cursor:pointer;transition:transform .15s,opacity .15s;border:none}
.action-btn:active{transform:scale(.96)}
.action-btn.primary{background:var(--brown);color:#fff;box-shadow:var(--shadow-btn)}
.action-btn.secondary{background:var(--bg);color:var(--fg);border:1px solid var(--border)}
.action-btn svg{width:16px;height:16px}
.action-btn.secondary svg{width:35px;height:35px}
.divider{height:1px;background:var(--border);margin:12px 28px 0}
.pet-selector{display:flex;gap:8px;padding:16px 20px 0;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none}
.pet-selector::-webkit-scrollbar{display:none}
.pet-chip{flex-shrink:0;display:flex;align-items:center;gap:6px;padding:6px 12px;border-radius:var(--radius-btn);background:var(--bg);border:1.5px solid var(--border);cursor:pointer;transition:all .2s}
.pet-chip.active{border-color:var(--brown);background:rgba(139,94,70,.06)}
.pet-chip:active{transform:scale(.96)}
.pet-chip-avatar{width:22px;height:22px;border-radius:6px;background:linear-gradient(135deg,rgba(215,181,147,.2),rgba(215,181,147,.08));display:flex;align-items:center;justify-content:center;font-size:12px}
.pet-chip-name{font-size:12px;font-weight:500;color:var(--fg);white-space:nowrap}
.profile-body{padding:16px 20px 0}
.glass-card{background:rgba(0,0,0,.03);border-radius:20px;padding:16px;margin-bottom:12px}
.glass-card-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}
.glass-card-title{display:flex;align-items:center;gap:8px;font-size:15px;font-weight:600;color:var(--fg)}
.glass-card-title svg{width:16px;height:16px;color:var(--brown)}
.glass-card-badge{font-size:11px;color:var(--muted);background:rgba(0,0,0,.04);padding:3px 8px;border-radius:var(--radius-btn);font-weight:500}
.glass-card-more{font-size:12px;color:var(--brown);font-weight:500;cursor:pointer;display:flex;align-items:center;gap:2px}
.glass-card-more svg{width:12px;height:12px}
.record-item{display:flex;align-items:flex-start;gap:10px;padding:10px 0;border-bottom:1px solid rgba(0,0,0,.04)}
.record-item:last-child{border-bottom:none;padding-bottom:0}
.record-item:first-child{padding-top:0}
.record-icon{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:16px}
.record-icon.diet{background:rgba(139,94,70,.1)}
.record-icon.health{background:rgba(108,138,105,.1)}
.record-icon.symptom{background:rgba(255,59,48,.1)}
.record-content{flex:1;min-width:0}
.record-name{font-size:13px;font-weight:500;color:var(--fg);margin-bottom:1px}
.record-desc{font-size:11px;color:var(--muted);line-height:1.4}
.record-time{font-size:10px;color:var(--muted);white-space:nowrap;flex-shrink:0;margin-top:2px}
.weight-mini{display:flex;align-items:center;justify-content:space-between}
.weight-mini-value{font-size:24px;font-weight:600;color:var(--brown);font-family:var(--font-num)}
.weight-mini-label{font-size:11px;color:var(--muted)}
.weight-form{display:flex;gap:8px;margin-bottom:12px}
.weight-input{flex:1;height:36px;border:1px solid var(--border);border-radius:8px;padding:0 10px;font-size:13px;font-family:var(--font-body);color:var(--fg);background:var(--card);outline:none}
.weight-input:focus{border-color:var(--brown)}
.weight-submit{flex-shrink:0;height:36px;padding:0 14px;border-radius:8px;background:var(--brown);color:#fff;font-size:13px;font-weight:500;border:none;cursor:pointer}
.weight-submit:disabled{opacity:.4;cursor:default}
.weight-submit:active{transform:scale(.96)}
.weight-bar-chart{display:flex;align-items:flex-end;gap:4px;height:50px;padding:0 2px}
.weight-bar-item{display:flex;flex-direction:column;align-items:center;gap:2px;flex:1;cursor:pointer;transition:transform .15s}
.weight-bar-item:active{transform:scale(.9)}
.weight-bar-value{font-size:9px;color:var(--muted);font-family:var(--font-num)}
.weight-bar{width:100%;max-width:12px;background:linear-gradient(180deg,var(--brown),rgba(139,94,70,.6));border-radius:4px 4px 0 0;min-height:4px}
.weight-bar-label{font-size:8px;color:var(--muted);margin-top:1px}
.allergy-tags{display:flex;flex-wrap:wrap;gap:6px}
.allergy-tag{display:inline-flex;align-items:center;gap:4px;padding:5px 12px;border-radius:var(--radius-btn);background:rgba(255,59,48,.06);border:1px solid rgba(255,59,48,.12);font-size:12px;color:#FF3B30;font-weight:500}
.allergy-del{background:none;border:none;color:#FF3B30;font-size:14px;cursor:pointer;padding:0 2px;opacity:.6;line-height:1}
.allergy-del:active{opacity:1}
.add-btn{background:none;border:none;color:var(--brown);font-size:13px;font-weight:500;cursor:pointer;padding:4px 8px}
.allergy-form{margin-top:12px;padding:14px;background:rgba(0,0,0,.03);border-radius:16px}
.allergy-input{width:100%;height:40px;border:1px solid var(--border);border-radius:12px;padding:0 12px;font-size:14px;background:var(--card);color:var(--fg);outline:none;margin-bottom:10px}
.allergy-input::placeholder{color:var(--muted)}
.allergy-form-row{display:flex;gap:10px;align-items:center;margin-bottom:10px}
.allergy-select{flex:1;height:40px;border:1px solid var(--border);border-radius:12px;padding:0 12px;font-size:13px;background:var(--card);color:var(--fg);outline:none}
.allergy-check{display:flex;align-items:center;gap:6px;font-size:13px;color:var(--fg);cursor:pointer}
.allergy-check input{accent-color:var(--brown)}
.allergy-form-actions{display:flex;gap:8px}
.allergy-submit{flex:1;height:38px;border-radius:var(--radius-btn);background:var(--brown);color:#fff;border:none;font-size:14px;font-weight:500;cursor:pointer}
.allergy-submit:disabled{opacity:.4;cursor:default}
.allergy-cancel{height:38px;border-radius:var(--radius-btn);background:transparent;color:var(--muted);border:1px solid var(--border);font-size:14px;cursor:pointer;padding:0 16px}
.timeline{position:relative;padding-left:16px}
.timeline::before{content:'';position:absolute;left:5px;top:6px;bottom:6px;width:1.5px;background:rgba(0,0,0,.06);border-radius:1px}
.timeline-item{position:relative;padding:0 0 12px 14px}
.timeline-item:last-child{padding-bottom:0}
.timeline-dot{position:absolute;left:-15px;top:5px;width:8px;height:8px;border-radius:50%;border:2px solid var(--brown);background:var(--card)}
.timeline-date{font-size:10px;color:var(--muted);margin-bottom:2px;font-weight:500}
.timeline-text{font-size:12px;color:var(--fg);line-height:1.5}
@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
.anim-fade-up{opacity:0;animation:fadeUp .6s cubic-bezier(.22,1,.36,1) forwards}
.anim-delay-1{animation-delay:.1s}.anim-delay-2{animation-delay:.2s}
</style>

// nuzzly-expo/app/(tabs)/profile.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
 View,
 Text,
 ScrollView,
 TouchableOpacity,
 Image,
 ImageBackground,
 StyleSheet,
 TextIn,
 Alert,
 Dimensions,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { colors, spacing, radius, shadows, typography, sizes } from '../../src/theme/tokens';
import { useAuthStore } from '../../src/stores/authStore';
import { usePets, Pet } from '../../src/hooks/usePets';
import { useDietLogs, DietLog } from '../../src/hooks/useDietLogs';
import { useHealth Recordss, Health Records, Allergy } from '../../src/hooks/useHealth Recordss';
import { useToast } from '../../src/hooks/useToast';
import ToastContainer from '../../src/components/ToastContainer';
import {
 BellIcon,
 EditIcon,
 SettingsIcon,
 UtensilsIcon,
 ActivityIcon,
 MapPinIcon,
 ClockIcon,
 AlertTriangleIcon,
} from '../../src/components/Icons';

const { width: screenWidth } = Dimensions.get('window');

const SPECIES_EMOJI: Record<string, string> = { cat: '🐱', dog: '🐶' };
const FOOD_ICON: Record<string, string> = {
 dry_food: '🍖',
 wet_food: '🐟',
 water: '💧',
 treat: '🦴',
 default: '🍽️',
};
const RECORD_ICON: Record<string, string> = {
 vaccination: '💉',
 symptom: '🩺',
 medication: '💊',
 diagnosis: '📋',
 checkup: '🩻',
 weight: '⚖️',
};
const SEVERITY_LABEL: Record<string, string> = { mild: 'Mild', Moderate: 'Moderate', severe: 'Severe' };

export default function profile() {
 const router = useRouter();
 const insets = useSafeAreaInsets();
 const profile = useAuthStore((s) => s.profile);
 const { toasts, show } = useToast();

 const { pets: rawPets, fetchPets, updatePet } = usePets();
 const { dietLogs: rawDietLogs, fetchDietLogs } = useDietLogs();
 const {
 healthRecords: rawHealth,
 weightRecords,
 allergies: rawAllergies,
 timeline,
 fetchHealth Recordss,
 fetchAllergies,
 addAllergy,
 deleteAllergy,
 addHealth Records,
 deleteHealth Records,
 } = useHealth Recordss();

 const [selectedPet, setSelectedPet] = useState<string | null>(null);
 const [showWeightForm, setShowWeightForm] = useState(false);
 const [newWeight, setNewWeight] = useState('');
 const [weightSaving, setWeightSaving] = useState(false);
 const [showAllergyForm, setShowAllergyForm] = useState(false);
 const [newAllergen, setNewAllergen] = useState('');
 const [newSeverity, setNewSeverity] = useState<'mild' | 'Moderate' | 'severe'>('mild');
 const [newConfirmed, setNewConfirmed] = useState(false);

 const lastTapRef = useRef<Record<string, number>>({});

 const userName = profile?.display_name || profile?.username || 'Pet Parent';
 const userIdShort = useMemo(() => {
 const num = (profile as any)?.user_number;
 if (num) return `nuzzmily${String(num).padStart(3, '0')}`;
 return 'nuzzmily000';
 }, [profile]);
 const avatarUrl = profile?.avatar_url;
 const regionText = (profile as any)?.region?.replace(' · ', ' ') || '';
 const reviewCount = (profile as any)?.review_count || 0;

 const pets = useMemo(() =>
 rawPets.map((p: Pet) => ({
 id: p.id,
 name: p.name,
 emoji: SPECIES_EMOJI[p.species] || '🐾',
 })),
 [rawPets]);

 const dietLogs = useMemo(() =>
 rawDietLogs.slice(0, 3).map((l: DietLog) => ({
 id: l.id,
 icon: FOOD_ICON[l.food_type || ''] || FOOD_ICON.default,
 name: l.food_name,
 desc: l.notes || l.food_type,
 time: (l.created_at || l.logged_date || '').slice(11, 16) || '-',
 })),
 [rawDietLogs]);

 const healthRecords = useMemo(() =>
 rawHealth.slice(0, 3).map((r: Health Records) => ({
 id: r.id,
 icon: RECORD_ICON[r.record_type] || '📋',
 type: r.record_type,
 name: r.diagnosis || r.medication_name || r.record_type,
 desc: r.notes || '',
 date: (r.record_time || '').slice(5, 10),
 })),
 [rawHealth]);

 const latestWeight = useMemo(() => {
 const w = weightRecords[0]?.weight_kg;
 return w? Number(w).toFixed(1): '--';
 }, [weightRecords]);

 const weightChartData = useMemo(() => {
 const records = weightRecords.slice(0, 7).reverse();
 const weights = records.map((r) => Number(r.weight_kg));
 const maxWeight = Math.max(...weights, 1);
 const minWeight = Math.min(...weights, 0);
 const range = maxWeight - minWeight || 1;
 return records.map((record) => {
 const weight = Number(record.weight_kg);
 const normalized = (weight - minWeight) / range;
 const height = 15 + normalized * 25;
 const date = new Date(record.record_time || Date.now());
 const label = `${date.getMonth() + 1}/${date.getDate()}`;
 return { id: record.id, value: weight.toFixed(1), height, label };
 });
 }, [weightRecords]);

 const allergyTags = useMemo(() =>
 rawAllergies.map((a: Allergy) => ({
 id: a.id,
 allergen: a.allergen,
 severityLabel: SEVERITY_LABEL[a.severity] || '',
 confirmed: a.confirmed,
 })),
 [rawAllergies]);

 useEffect(() => {
 fetchPets().then(() => {
 if (pets.length &&!selectedPet) setSelectedPet(pets[0].id);
 });
 }, [fetchPets]);

 useEffect(() => {
 if (selectedPet) {
 fetchHealth Recordss(selectedPet);
 fetchDietLogs(selectedPet);
 fetchAllergies(selectedPet);
 }
 }, [selectedPet, fetchHealth Recordss, fetchDietLogs, fetchAllergies]);

 async function handleAddWeight() {
 if (!newWeight ||!selectedPet) return;
 setWeightSaving(true);
 try {
 const kg = Math.round(Number(newWeight) * 100) / 100;
 await addHealth Records({
 pet_id: selectedPet,
 record_type: 'weight',
 weight_kg: kg,
 record_time: new Date().toISOString(),
 });
 await updatePet(selectedPet, { weight_kg: kg });
 show('Weight recorded', 'success');
 setNewWeight('');
 setShowWeightForm(false);
 fetchHealth Recordss(selectedPet);
 } catch (e: any) {
 show(e.message || 'Record Failed', 'error');
 } finally {
 setWeightSaving(false);
 }
 }

 async function handleDeleteWeight(id: string, value: string, label: string) {
 Alert.alert('Confirm Delete', `Are you sure you want to delete ${label} 's weight record (${value} kg)?`, [{ text: 'Cancel', style: 'cancel' },
 {
 text: 'Delete',
 style: 'destructive',
 onPress: async () => {
 try {
 await deleteHealth Records(id);
 show('Deleted', 'success');
 if (selectedPet) fetchHealth Recordss(selectedPet);
 } catch (e: any) {
 show(e.message || 'Delete Failed', 'error');
 }
 },
 },]);
 }

 async function onAddAllergy() {
 if (!newAllergen.trim() ||!selectedPet) return;
 try {
 await addAllergy({
 pet_id: selectedPet,
 allergen: newAllergen.trim(),
 severity: newSeverity,
 confirmed: newConfirmed,
 });
 show('Allergy added', 'success');
 setNewAllergen('');
 setNewSeverity('mild');
 setNewConfirmed(false);
 setShowAllergyForm(false);
 } catch (e: any) {
 show(e.message || 'Add Failed', 'error');
 }
 }

 async function onDeleteAllergy(id: string, isConfirmed: boolean) {
 if (isConfirmed) {
 const ok = await new Promise<boolean>((resolve) => {
 Alert.alert('Confirm Delete', 'the AllergyConfirmed, Are you sure you want to delete?', [{ text: 'Cancel', onPress: () => resolve(false) },
 { text: 'Delete', style: 'destructive', onPress: () => resolve(true) },]);
 });
 if (!ok) return;
 }
 try {
 await deleteAllergy(id);
 show('AllergyDeleted', 'success');
 } catch (e: any) {
 show(e.message || 'Delete Failed', 'error');
 }
 }

 function handlePetChipPress(petId: string) {
 const now = Date.now();
 const last = lastTapRef.current[petId] || 0;
 if (now - last < 300) {
 router.push(`/pets/${petId}`);
 } else {
 setSelectedPet(petId);
 }
 lastTapRef.current[petId] = now;
 }

 const healthevents = useMemo(() => timeline.slice(0, 4), [timeline]);

 return (<View style={styles.container}>
 <ToastContainer toasts={toasts} />
 <ScrollView
 showsVerticalScrollIndicator={false}
 contentContainerStyle={{ paddingBottom: 90 + insets.bottom }}
 contentInsetAdjustmentBehavior="never"
 >
 {/* Hero Background */}
 <ImageBackground
 source={require('../../assets/images/scene graph.png')}
 style={[styles.heroBg, { height: Math.min(Math.max(screenWidth * 0.45, 180), 220) + insets.top }]}
 imageStyle={styles.heroBgImage}
 >
 <TouchableOpacity
 activeOpacity={0.8}
 style={[styles.heroNotif, { top: insets.top + 16 }]}
 onPress={() => router.push('/notifications')}
 >
 <BellIcon size={20} color={colors.fg} />
 </TouchableOpacity>
 </ImageBackground>

 {/* profile Card */}
 <View
 style={[styles.profileCard,
 { marginTop: Math.min(Math.max(screenWidth * 0.45, 180), 220) + insets.top - 36 },]}
 >
 <View style={styles.profileAvatar}>
 {avatarUrl? (<Image source={{ uri: avatarUrl }} style={styles.profileAvatarImg} />): (<Image source={require('../../assets/images/mqpyqgao-logo.png')} style={styles.profileAvatarImg} />)}
 </View>
 <View style={styles.profileInfo}>
 <Text style={styles.profileUsername}>{userName}</Text>
 <Text style={styles.profileId}>ID: {userIdShort}</Text>
 {regionText? <Text style={styles.profileRegion}>📍 {regionText}</Text>: null}
 </View>

 <View style={styles.statsRow}>
 <TouchableOpacity activeOpacity={0.7} style={styles.statItem}>
 <Text style={styles.statNum}>{reviewCount}</Text>
 <Text style={styles.statLabel}>Reviews</Text>
 </TouchableOpacity>
 <TouchableOpacity activeOpacity={0.7} style={styles.statItem}>
 <Text style={styles.statNum}>{(profile as any)?.trust_score?? '--'}</Text>
 <Text style={styles.statLabel}>Trust Score</Text>
 </TouchableOpacity>
 <TouchableOpacity activeOpacity={0.7} style={styles.statItem}>
 <Text style={styles.statNum}>0</Text>
 <Text style={styles.statLabel}>Followingers</Text>
 </TouchableOpacity>
 <TouchableOpacity activeOpacity={0.7} style={styles.statItem}>
 <Text style={styles.statNum}>0</Text>
 <Text style={styles.statLabel}>Following</Text>
 </TouchableOpacity>
 </View>

 <View style={styles.profileActions}>
 <TouchableOpacity
 activeOpacity={0.9}
 style={[styles.actionBtn, styles.actionBtnPrimary]}
 onPress={() => router.push('/edit-profile')}
 >
 <EditIcon size={16} color="#fff" />
 <Text style={styles.actionBtnTextPrimary}>Edit profile</Text>
 </TouchableOpacity>
 <TouchableOpacity
 activeOpacity={0.9}
 style={[styles.actionBtn, styles.actionBtnSecondary]}
 onPress={() => router.push('/settings')}
 >
 <SettingsIcon size={16} color={colors.fg} />
 <Text style={styles.actionBtnTextSecondary}>Settings</Text>
 </TouchableOpacity>
 </View>

 <View style={styles.r} />

 <ScrollView
 horizontal
 showsHorizontalScrollIndicator={false}
 contentContainerStyle={styles.petSelector}
 >
 {pets.map((pet: any) => (<TouchableOpacity
 key={pet.id}
 activeOpacity={0.8}
 style={[styles.petChip, selectedPet === pet.id && styles.petChipActive]}
 onPress={() => handlePetChipPress(pet.id)}
 >
 <View style={styles.petChipAvatar}>
 <Text style={styles.petChipEmoji}>{pet.emoji}</Text>
 </View>
 <Text style={styles.petChipName}>{pet.name}</Text>
 </TouchableOpacity>))}
 <TouchableOpacity
 activeOpacity={0.8}
 style={[styles.petChip, styles.petChipAdd]}
 onPress={() => router.push('/pet/create')}
 >
 <View style={[styles.petChipAvatar, styles.petChipAvatarAdd]}>
 <Text style={styles.petChipAddIcon}>+</Text>
 </View>
 <Text style={[styles.petChipName, { color: colors.muted }]}>Add</Text>
 </TouchableOpacity>
 </ScrollView>

 <View style={styles.profileBody}>
 {/* Diet Logs */}
 <View style={styles.glassCard}>
 <View style={styles.glassCardHeader}>
 <View style={styles.glassCardTitle}>
 <UtensilsIcon size={16} color={colors.primary} />
 <Text style={styles.glassCardTitleText}>Diet Logs</Text>
 </View>
 <TouchableOpacity activeOpacity={0.7} style={styles.glassCardMore}>
 <Text style={styles.glassCardMoreText}>All</Text>
 </TouchableOpacity>
 </View>
 {dietLogs.length? (dietLogs.map((l: any) => (<View key={l.id} style={styles.recordItem}>
 <View style={[styles.recordIcon, styles.recordIconDiet]}>
 <Text style={styles.recordIconEmoji}>{l.icon}</Text>
 </View>
 <View style={styles.recordContent}>
 <Text style={styles.recordName}>{l.name}</Text>
 <Text style={styles.recordDesc}>{l.desc}</Text>
 </View>
 <Text style={styles.recordTime}>{l.time}</Text>
 </View>))): (<View style={styles.recordItem}>
 <View style={styles.recordContent}>
 <Text style={[styles.recordName, { color: colors.muted }]}>No diet records</Text>
 </View>
 </View>)}
 </View>

 {/* Health Records */}
 <View style={styles.glassCard}>
 <View style={styles.glassCardHeader}>
 <View style={styles.glassCardTitle}>
 <ActivityIcon size={16} color={colors.primary} />
 <Text style={styles.glassCardTitleText}>Health Records</Text>
 </View>
 <View style={styles.glassCardBadge}>
 <Text style={styles.glassCardBadgeText}>{rawHealth.length} records</Text>
 </View>
 </View>
 {healthRecords.length? (healthRecords.map((r: any) => (<View key={r.id} style={styles.recordItem}>
 <View style={[styles.recordIcon, styles.recordIconHealth]}>
 <Text style={styles.recordIconEmoji}>{r.icon}</Text>
 </View>
 <View style={styles.recordContent}>
 <Text style={styles.recordName}>{r.name}</Text>
 <Text style={styles.recordDesc}>{r.desc}</Text>
 </View>
 <Text style={styles.recordTime}>{r.date}</Text>
 </View>))): (<View style={styles.recordItem}>
 <View style={styles.recordContent}>
 <Text style={[styles.recordName, { color: colors.muted }]}>NoneHealth Records</Text>
 </View>
 </View>)}
 </View>

 {/* Weight Trend */}
 <View style={styles.glassCard}>
 <View style={styles.glassCardHeader}>
 <View style={styles.glassCardTitle}>
 <MapPinIcon size={16} color={colors.primary} />
 <Text style={styles.glassCardTitleText}>Weight Trend</Text>
 </View>
 <TouchableOpacity activeOpacity={0.7} onPress={() => setShowWeightForm((v) =>!v)}>
 <Text style={styles.addBtnText}>{showWeightForm? 'Collapse': '+ Record'}</Text>
 </TouchableOpacity>
 </View>
 {showWeightForm && (<View style={styles.weightForm}>
 <TextIn
 style={styles.weightIn}
 value={newWeight}
 onChangeText={setNewWeight}
 placeholder="Enter weight (kg)"
 keyboardType="decimal-pad"
 placeholderTextColor={colors.muted}
 />
 <TouchableOpacity
 activeOpacity={0.9}
 style={[styles.weightSubmit, (!newWeight || weightSaving) && styles.weightSubmitDisabled]}
 disabled={!newWeight || weightSaving}
 onPress={handleAddWeight}
 >
 <Text style={styles.weightSubmitText}>{weightSaving? 'Recording...': 'Record'}</Text>
 </TouchableOpacity>
 </View>)}
 <View style={styles.weightMini}>
 <View>
 <Text style={styles.weightMiniValue}>
 {latestWeight} <Text style={styles.weightMiniUnit}>kg</Text>
 </Text>
 <Text style={styles.weightMiniLabel}>Latest Weight</Text>
 </View>
 <View style={styles.weightBarChart}>
 {weightChartData.map((item) => (<TouchableOpacity
 key={item.id}
 activeOpacity={0.8}
 style={styles.weightBarItem}
 onPress={() => handleDeleteWeight(item.id, item.value, item.label)}
 >
 <Text style={styles.weightBarValue}>{item.value}</Text>
 <View style={[styles.weightBar, { height: item.height }]} />
 <Text style={styles.weightBarLabel}>{item.label}</Text>
 </TouchableOpacity>))}
 {!weightChartData.length && (<Text style={{ fontSize: 12, color: colors.muted }}>No data yet</Text>)}
 </View>
 </View>
 </View>

 {/* Allergies */}
 <View style={styles.glassCard}>
 <View style={styles.glassCardHeader}>
 <View style={styles.glassCardTitle}>
 <AlertTriangleIcon size={16} color={colors.primary} />
 <Text style={styles.glassCardTitleText}>Allergy Info</Text>
 </View>
 {!showAllergyForm && (<TouchableOpacity activeOpacity={0.7} onPress={() => setShowAllergyForm(true)}>
 <Text style={styles.addBtnText}>+ Add</Text>
 </TouchableOpacity>)}
 </View>
 <View style={styles.allergyTags}>
 {allergyTags.map((a: any) => (<View key={a.id} style={styles.allergyTag}>
 <Text style={styles.allergyTagText}>
 {a.allergen} · {a.severityLabel}
 </Text>
 <TouchableOpacity onPress={() => onDeleteAllergy(a.id, a.confirmed)}>
 <Text style={styles.allergyDel}>×</Text>
 </TouchableOpacity>
 </View>))}
 {!allergyTags.length &&!showAllergyForm && (<View style={[styles.allergyTag, styles.allergyTagEmpty]}>
 <Text style={{ color: colors.muted, fontSize: 12 }}>None</Text>
 </View>)}
 </View>
 {showAllergyForm && (<View style={styles.allergyForm}>
 <TextIn
 style={styles.allergyIn}
 value={newAllergen}
 onChangeText={setNewAllergen}
 placeholder="Allergen name, e.g., chicken, grain"
 placeholderTextColor={colors.muted}
 />
 <View style={styles.allergyFormRow}>
 <View style={styles.allergySelectWrap}>
 {(['mild', 'Moderate', 'severe'] as const).map((s) => (<TouchableOpacity
 key={s}
 activeOpacity={0.8}
 style={[styles.allergySelectOption, newSeverity === s && styles.allergySelectOptionActive]}
 onPress={() => setNewSeverity(s)}
 >
 <Text style={[styles.allergySelectText, newSeverity === s && styles.allergySelectTextActive]}>
 {SEVERITY_LABEL[s]}
 </Text>
 </TouchableOpacity>))}
 </View>
 <TouchableOpacity
 activeOpacity={0.8}
 style={styles.allergyCheck}
 onPress={() => setNewConfirmed((v) =>!v)}
 >
 <View style={[styles.checkbox, newConfirmed && styles.checkboxChecked]}>
 {newConfirmed && <Text style={styles.checkMark}>✓</Text>}
 </View>
 <Text style={styles.allergyCheckText}>Confirmed</Text>
 </TouchableOpacity>
 </View>
 <View style={styles.allergyFormActions}>
 <TouchableOpacity
 activeOpacity={0.9}
 style={[styles.allergySubmit,!newAllergen.trim() && styles.allergySubmitDisabled]}
 disabled={!newAllergen.trim()}
 onPress={onAddAllergy}
 >
 <Text style={styles.allergySubmitText}>Add</Text>
 </TouchableOpacity>
 <TouchableOpacity
 activeOpacity={0.8}
 style={styles.allergyCancel}
 onPress={() => setShowAllergyForm(false)}
 >
 <Text style={styles.allergyCancelText}>Cancel</Text>
 </TouchableOpacity>
 </View>
 </View>)}
 </View>

 {/* Health events */}
 <View style={[styles.glassCard, { marginBottom: 20 }]}>
 <View style={styles.glassCardHeader}>
 <View style={styles.glassCardTitle}>
 <ClockIcon size={16} color={colors.primary} />
 <Text style={styles.glassCardTitleText}>Health events</Text>
 </View>
 </View>
 <View style={styles.timeline}>
 {healthevents.length? (healthevents.map((ev, idx) => (<View key={`${ev.date}-${idx}`} style={styles.timelineItem}>
 <View style={styles.timelineDot} />
 <Text style={styles.timelineDate}>{ev.date}</Text>
 <Text style={styles.timelineText}>{ev.text}</Text>
 </View>))): (<View style={styles.timelineItem}>
 <Text style={[styles.timelineText, { color: colors.muted }]}>NoneHealth events</Text>
 </View>)}
 </View>
 </View>
 </View>
 </View>
 </ScrollView>
 </View>);
}

const styles = StyleSheet.create({
 container: {
 flex: 1,
 backgroundColor: colors.bg,
 },
 heroBg: {
 width: '100%',
 position: 'absolute',
 top: 0,
 left: 0,
 right: 0,
 zIndex: 0,
 },
 heroBgImage: {
 },
 heroNotif: {
 position: 'absolute',
 right: 16,
 width: 41.31,
 height: 41.31,
 borderRadius: 41.31 / 2,
 backgroundColor: 'rgba(255,255,255,0.72)',
 alignItems: 'center',
 justifyContent: 'center',
 borderWidth: 1,
 borderColor: 'rgba(255,255,255,0.6)',...shadows.sm,
 },
 profileCard: {
 backgroundColor: colors.card,
 borderTopLeftRadius: radius.card,
 borderTopRightRadius: radius.card,
 position: 'relative',
 zIndex: 1,
 paddingTop: 36,
 paddingBottom: 12,
 },
 profileAvatar: {
 position: 'absolute',
 top: -36,
 right: 28,
 width: 72,
 height: 72,
 borderRadius: 36,
 borderWidth: 3,
 borderColor: colors.card,...shadows.md,
 overflow: 'hidden',
 backgroundColor: colors.secondary,
 alignItems: 'center',
 justifyContent: 'center',
 zIndex: 2,
 },
 profileAvatarImg: {
 width: '100%',
 height: '100%',
 },
 profileInfo: {
 paddingHorizontal: 28,
 paddingRight: 120,
 gap: 4,
 },
 profileUsername: {
 fontFamily: typography.display,
 fontSize: 24,
 fontWeight: '700',
 letterSpacing: -0.02,
 color: colors.fg,
 lineHeight: 28,
 },
 profileId: {
 fontSize: 13,
 color: colors.muted,
 letterSpacing: 0.01,
 },
 profileRegion: {
 fontSize: 12,
 color: colors.muted,
 marginTop: 2,
 },
 statsRow: {
 flexDirection: 'row',
 justifyContent: 'space-around',
 paddingTop: 16,
 paddingHorizontal: 28,
 },
 statItem: {
 alignItems: 'center',
 gap: 4,
 },
 statNum: {
 fontFamily: typography.num,
 fontSize: 20,
 fontWeight: '600',
 lineHeight: 20,
 letterSpacing: -0.02,
 color: colors.fg,
 },
 statLabel: {
 fontSize: 12,
 color: colors.muted,
 letterSpacing: 0.01,
 },
 profileActions: {
 flexDirection: 'row',
 gap: 12,
 paddingTop: 16,
 paddingHorizontal: 28,
 },
 actionBtn: {
 flex: 1,
 height: 44,
 borderRadius: radius.btn,
 flexDirection: 'row',
 alignItems: 'center',
 justifyContent: 'center',
 gap: 6,
 },
 actionBtnPrimary: {
 backgroundColor: colors.primary,...shadows.btn,
 },
 actionBtnSecondary: {
 backgroundColor: colors.bg,
 borderWidth: 1,
 borderColor: colors.border,
 },
 actionBtnTextPrimary: {
 color: '#fff',
 fontSize: 14,
 fontWeight: '500',
 letterSpacing: 0.01,
 },
 actionBtnTextSecondary: {
 color: colors.fg,
 fontSize: 14,
 fontWeight: '500',
 letterSpacing: 0.01,
 },
 r: {
 height: 1,
 backgroundColor: colors.border,
 marginHorizontal: 28,
 marginTop: 12,
 },
 petSelector: {
 flexDirection: 'row',
 gap: 8,
 paddingHorizontal: 20,
 paddingTop: 16,
 paddingRight: 40,
 },
 petChip: {
 flexDirection: 'row',
 alignItems: 'center',
 gap: 6,
 paddingVertical: 6,
 paddingHorizontal: 12,
 borderRadius: radius.btn,
 backgroundColor: colors.bg,
 borderWidth: 1.5,
 borderColor: colors.border,
 },
 petChipActive: {
 borderColor: colors.primary,
 backgroundColor: 'rgba(139,94,70,0.06)',
 },
 petChipAdd: {
 borderStyle: 'dashed',
 },
 petChipAvatar: {
 width: 22,
 height: 22,
 borderRadius: 6,
 backgroundColor: 'rgba(215,181,147,0.2)',
 alignItems: 'center',
 justifyContent: 'center',
 },
 petChipAvatarAdd: {
 backgroundColor: 'transparent',
 },
 petChipEmoji: {
 fontSize: 12,
 },
 petChipAddIcon: {
 fontSize: 16,
 color: colors.muted,
 },
 petChipName: {
 fontSize: 12,
 fontWeight: '500',
 color: colors.fg,
 },
 profileBody: {
 paddingHorizontal: 20,
 paddingTop: 16,
 },
 glassCard: {
 backgroundColor: 'rgba(0,0,0,0.03)',
 borderRadius: radius['2xl'],
 padding: 16,
 marginBottom: 12,
 },
 glassCardHeader: {
 flexDirection: 'row',
 alignItems: 'center',
 justifyContent: 'space-between',
 marginBottom: 12,
 },
 glassCardTitle: {
 flexDirection: 'row',
 alignItems: 'center',
 gap: 8,
 },
 glassCardTitleText: {
 fontSize: 15,
 fontWeight: '600',
 color: colors.fg,
 },
 glassCardMore: {
 flexDirection: 'row',
 alignItems: 'center',
 gap: 2,
 },
 glassCardMoreText: {
 fontSize: 12,
 color: colors.primary,
 fontWeight: '500',
 },
 glassCardBadge: {
 backgroundColor: 'rgba(0,0,0,0.04)',
 paddingHorizontal: 8,
 paddingVertical: 3,
 borderRadius: radius.btn,
 },
 glassCardBadgeText: {
 fontSize: 11,
 color: colors.muted,
 fontWeight: '500',
 },
 recordItem: {
 flexDirection: 'row',
 alignItems: 'flex-start',
 gap: 10,
 paddingVertical: 10,
 borderBottomWidth: 1,
 borderBottomColor: 'rgba(0,0,0,0.04)',
 },
 recordIcon: {
 width: 36,
 height: 36,
 borderRadius: 10,
 alignItems: 'center',
 justifyContent: 'center',
 },
 recordIconDiet: {
 backgroundColor: 'rgba(139,94,70,0.1)',
 },
 recordIconHealth: {
 backgroundColor: 'rgba(108,138,105,0.1)',
 },
 recordIconEmoji: {
 fontSize: 16,
 },
 recordContent: {
 flex: 1,
 minWidth: 0,
 },
 recordName: {
 fontSize: 13,
 fontWeight: '500',
 color: colors.fg,
 marginBottom: 1,
 },
 recordDesc: {
 fontSize: 11,
 color: colors.muted,
 lineHeight: 15,
 },
 recordTime: {
 fontSize: 10,
 color: colors.muted,
 marginTop: 2,
 },
 weightMini: {
 flexDirection: 'row',
 alignItems: 'center',
 justifyContent: 'space-between',
 },
 weightMiniValue: {
 fontSize: 24,
 fontWeight: '600',
 color: colors.primary,
 fontFamily: typography.num,
 },
 weightMiniUnit: {
 fontSize: 14,
 fontWeight: '400',
 color: colors.muted,
 },
 weightMiniLabel: {
 fontSize: 11,
 color: colors.muted,
 },
 weightForm: {
 flexDirection: 'row',
 gap: 8,
 marginBottom: 12,
 },
 weightIn: {
 flex: 1,
 height: 36,
 borderWidth: 1,
 borderColor: colors.border,
 borderRadius: 8,
 paddingHorizontal: 10,
 fontSize: 13,
 color: colors.fg,
 backgroundColor: colors.card,
 },
 weightSubmit: {
 height: 36,
 paddingHorizontal: 14,
 borderRadius: 8,
 backgroundColor: colors.primary,
 alignItems: 'center',
 justifyContent: 'center',
 },
 weightSubmitDisabled: {
 opacity: 0.4,
 },
 weightSubmitText: {
 color: '#fff',
 fontSize: 13,
 fontWeight: '500',
 },
 weightBarChart: {
 flexDirection: 'row',
 alignItems: 'flex-end',
 gap: 4,
 height: 50,
 paddingHorizontal: 2,
 },
 weightBarItem: {
 flex: 1,
 alignItems: 'center',
 gap: 2,
 },
 weightBarValue: {
 fontSize: 9,
 color: colors.muted,
 fontFamily: typography.num,
 },
 weightBar: {
 width: '100%',
 maxWidth: 12,
 minHeight: 4,
 backgroundColor: colors.primary,
 borderTopLeftRadius: 4,
 borderTopRightRadius: 4,
 },
 weightBarLabel: {
 fontSize: 8,
 color: colors.muted,
 marginTop: 1,
 },
 addBtnText: {
 color: colors.primary,
 fontSize: 13,
 fontWeight: '500',
 },
 allergyTags: {
 flexDirection: 'row',
 flexWrap: 'wrap',
 gap: 6,
 },
 allergyTag: {
 flexDirection: 'row',
 alignItems: 'center',
 gap: 4,
 paddingVertical: 5,
 paddingHorizontal: 12,
 borderRadius: radius.btn,
 backgroundColor: 'rgba(255,59,48,0.06)',
 borderWidth: 1,
 borderColor: 'rgba(255,59,48,0.12)',
 },
 allergyTagEmpty: {
 backgroundColor: 'rgba(0,0,0,0.04)',
 borderColor: 'transparent',
 },
 allergyTagText: {
 fontSize: 12,
 color: colors.danger,
 fontWeight: '500',
 },
 allergyDel: {
 color: colors.danger,
 fontSize: 14,
 opacity: 0.6,
 lineHeight: 16,
 },
 allergyForm: {
 marginTop: 12,
 padding: 14,
 backgroundColor: 'rgba(0,0,0,0.03)',
 borderRadius: 16,
 },
 allergyIn: {
 width: '100%',
 height: 40,
 borderWidth: 1,
 borderColor: colors.border,
 borderRadius: 12,
 paddingHorizontal: 12,
 fontSize: 14,
 backgroundColor: colors.card,
 color: colors.fg,
 marginBottom: 10,
 },
 allergyFormRow: {
 flexDirection: 'row',
 gap: 10,
 alignItems: 'center',
 marginBottom: 10,
 },
 allergySelectWrap: {
 flex: 1,
 flexDirection: 'row',
 gap: 6,
 },
 allergySelectOption: {
 flex: 1,
 height: 36,
 borderRadius: 8,
 borderWidth: 1,
 borderColor: colors.border,
 backgroundColor: colors.card,
 alignItems: 'center',
 justifyContent: 'center',
 },
 allergySelectOptionActive: {
 borderColor: colors.primary,
 backgroundColor: 'rgba(139,94,70,0.08)',
 },
 allergySelectText: {
 fontSize: 12,
 color: colors.fg,
 },
 allergySelectTextActive: {
 color: colors.primary,
 fontWeight: '500',
 },
 allergyCheck: {
 flexDirection: 'row',
 alignItems: 'center',
 gap: 6,
 },
 checkbox: {
 width: 16,
 height: 16,
 borderRadius: 4,
 borderWidth: 1.5,
 borderColor: colors.border,
 alignItems: 'center',
 justifyContent: 'center',
 },
 checkboxChecked: {
 backgroundColor: colors.primary,
 borderColor: colors.primary,
 },
 checkMark: {
 color: '#fff',
 fontSize: 10,
 fontWeight: '700',
 },
 allergyCheckText: {
 fontSize: 13,
 color: colors.fg,
 },
 allergyFormActions: {
 flexDirection: 'row',
 gap: 8,
 },
 allergySubmit: {
 flex: 1,
 height: 38,
 borderRadius: radius.btn,
 backgroundColor: colors.primary,
 alignItems: 'center',
 justifyContent: 'center',
 },
 allergySubmitDisabled: {
 opacity: 0.4,
 },
 allergySubmitText: {
 color: '#fff',
 fontSize: 14,
 fontWeight: '500',
 },
 allergyCancel: {
 height: 38,
 borderRadius: radius.btn,
 backgroundColor: 'transparent',
 borderWidth: 1,
 borderColor: colors.border,
 paddingHorizontal: 16,
 alignItems: 'center',
 justifyContent: 'center',
 },
 allergyCancelText: {
 color: colors.muted,
 fontSize: 14,
 },
 timeline: {
 paddingLeft: 16,
 position: 'relative',
 },
 timelineItem: {
 paddingBottom: 12,
 paddingLeft: 14,
 position: 'relative',
 },
 timelineDot: {
 position: 'absolute',
 left: -13,
 top: 5,
 width: 8,
 height: 8,
 borderRadius: 4,
 borderWidth: 2,
 borderColor: colors.primary,
 backgroundColor: colors.card,
 },
 timelineDate: {
 fontSize: 10,
 color: colors.muted,
 marginBottom: 2,
 fontWeight: '500',
 },
 timelineText: {
 fontSize: 12,
 color: colors.fg,
 lineHeight: 18,
 },
});
