// ios-app-frontend/src/views/Settings.vue
<template>
  <div class="settings-shell">
    <header class="settings-header">
      <button class="back-btn" @click="$router.back()"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></button>
      <h1 class="settings-title">设置</h1>
    </header>
    <div class="settings-body">
      <div class="settings-group">
        <div class="settings-group-title">账号与资料</div>
        <div class="settings-cell" @click="$router.push('/settings/sub/account')"><span>账号与安全</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
        <div class="settings-cell" @click="$router.push('/settings/sub/pets')"><span>宠物档案</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
      </div>
      <div class="settings-group">
        <div class="settings-group-title">会员</div>
        <div class="settings-cell" @click="$router.push('/settings/sub/membership')"><span>会员</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
      </div>
      <div class="settings-group">
        <div class="settings-group-title">显示与语言</div>
        <div class="settings-cell" @click="$router.push('/settings/sub/language')"><span>语言</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
        <div class="settings-cell" @click="$router.push('/settings/sub/fontsize')"><span>文字大小</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
      </div>
      <div class="settings-group">
        <div class="settings-group-title">基础</div>
        <div class="settings-cell" @click="$router.push('/settings/sub/notification')"><span>通知</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
        <div class="settings-cell" @click="$router.push('/settings/sub/general')"><span>通用</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
        <div class="settings-cell" @click="$router.push('/settings/sub/privacy')"><span>隐私</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
      </div>
      <div class="settings-group">
        <div class="settings-group-title">内容与社交</div>
        <div class="settings-cell" @click="$router.push('/settings/sub/content')"><span>我的内容</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
        <div class="settings-cell" @click="$router.push('/settings/sub/interaction')"><span>互动设置</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
      </div>
      <div class="settings-group">
        <div class="settings-group-title">其他</div>
        <div class="settings-cell" @click="$router.push('/settings/sub/about')"><span>关于我们</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
        <div class="settings-cell" @click="$router.push('/settings/sub/feedback')"><span>帮助与反馈</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M9 18l6-6-6-6"/></svg></div>
      </div>
      <button class="logout-btn" @click="handleLogout">退出登录</button>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../composables/useAuth'

const router = useRouter()
const { signOut, profile } = useAuth()

const isAdmin = computed(() => profile.value?.is_admin)

async function handleLogout() {
  await signOut()
  router.replace('/login')
}
</script>

<style scoped>
.settings-shell{width:100%;min-height:100vh;min-height:100dvh;background:var(--bg);padding-top:var(--safe-top)}
.settings-header{display:flex;align-items:center;padding:12px 16px;gap:12px}
.back-btn{width:40px;height:40px;border-radius:50%;background:var(--card);box-shadow:var(--shadow-card);display:flex;align-items:center;justify-content:center;border:1px solid var(--border);cursor:pointer;transition:transform .2s}
.back-btn:active{transform:scale(.92)}
.back-btn svg{width:20px;height:20px;color:var(--fg)}
.settings-title{font-family:var(--font-display);font-size:18px;font-weight:600;flex:1;text-align:center;margin-right:40px}
.settings-body{padding:0 16px 40px}
.settings-group{background:var(--card);border-radius:12px;margin-bottom:12px;overflow:hidden}
.settings-group-title{font-size:13px;color:var(--muted);padding:16px 16px 8px;letter-spacing:.01em}
.settings-cell{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid var(--border);cursor:pointer;transition:background .15s}
.settings-cell:last-child{border-bottom:none}
.settings-cell:active{background:rgba(0,0,0,.03)}
.settings-cell span{font-size:16px;color:var(--fg)}
.settings-cell svg{width:16px;height:16px;color:var(--muted)}
.logout-btn{width:100%;height:48px;border-radius:var(--radius-btn);background:var(--card);border:1px solid var(--border);font-size:16px;color:var(--red);font-weight:500;cursor:pointer;transition:background .15s;margin-top:8px}
.logout-btn:active{background:rgba(255,59,48,.05)}
</style>

// nuzzly-expo/app/(tabs)/settings.tsx
import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Alert,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { colors, spacing, radius, shadows, typography } from '../../src/theme/tokens';
import { useAuthStore } from '../../src/stores/authStore';
import { ChevronLeftIcon, ChevronRightIcon } from '../../src/components/Icons';

interface SettingItem {
  label: string;
  path: string;
}

interface SettingGroup {
  title: string;
  items: SettingItem[];
}

const GROUPS: SettingGroup[] = [
  {
    title: '账号与资料',
    items: [
      { label: '账号与安全', path: '/settings/sub/account' },
      { label: '宠物档案', path: '/settings/sub/pets' },
    ],
  },
  {
    title: '会员',
    items: [{ label: '会员', path: '/settings/sub/membership' }],
  },
  {
    title: '显示与语言',
    items: [
      { label: '语言', path: '/settings/sub/language' },
      { label: '文字大小', path: '/settings/sub/fontsize' },
    ],
  },
  {
    title: '基础',
    items: [
      { label: '通知', path: '/settings/sub/notification' },
      { label: '通用', path: '/settings/sub/general' },
      { label: '隐私', path: '/settings/sub/privacy' },
    ],
  },
  {
    title: '内容与社交',
    items: [
      { label: '我的内容', path: '/settings/sub/content' },
      { label: '互动设置', path: '/settings/sub/interaction' },
    ],
  },
  {
    title: '其他',
    items: [
      { label: '关于我们', path: '/settings/sub/about' },
      { label: '帮助与反馈', path: '/settings/sub/feedback' },
    ],
  },
];

export default function Settings() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const signOut = useAuthStore((s) => s.signOut);

  async function handleLogout() {
    Alert.alert(
      '退出登录',
      '确定要退出当前账号吗？',
      [
        { text: '取消', style: 'cancel' },
        {
          text: '退出',
          style: 'destructive',
          onPress: async () => {
            await signOut();
            router.replace('/login');
          },
        },
      ],
      { cancelable: true }
    );
  }

  return (
    <View style={styles.container}>
      <View style={[styles.header, { paddingTop: 12 + insets.top, paddingBottom: 12 }]}>
        <TouchableOpacity
          activeOpacity={0.8}
          style={styles.backBtn}
          onPress={() => router.back()}
        >
          <ChevronLeftIcon size={20} color={colors.fg} />
        </TouchableOpacity>
        <Text style={styles.title}>设置</Text>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingHorizontal: spacing.pageX, paddingBottom: 90 + insets.bottom }}
      >
        {GROUPS.map((group, groupIndex) => (
          <View key={group.title} style={styles.group}>
            <Text style={styles.groupTitle}>{group.title}</Text>
            <View style={styles.groupCard}>
              {group.items.map((item, itemIndex) => (
                <TouchableOpacity
                  key={item.label}
                  activeOpacity={0.7}
                  style={[
                    styles.cell,
                    itemIndex < group.items.length - 1 && styles.cellBorder,
                  ]}
                  onPress={() => router.push(item.path as any)}
                >
                  <Text style={styles.cellLabel}>{item.label}</Text>
                  <ChevronRightIcon size={16} color={colors.muted} />
                </TouchableOpacity>
              ))}
            </View>
          </View>
        ))}

        <TouchableOpacity
          activeOpacity={0.9}
          style={styles.logoutBtn}
          onPress={handleLogout}
        >
          <Text style={styles.logoutText}>退出登录</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.pageX,
    gap: spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    ...shadows.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    flex: 1,
    fontFamily: typography.display,
    fontSize: typography.sizes.xl,
    fontWeight: '600',
    color: colors.fg,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 40,
  },
  group: {
    marginBottom: spacing.md,
  },
  groupTitle: {
    fontSize: typography.sizes.sm,
    color: colors.muted,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    letterSpacing: 0.01,
  },
  groupCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    overflow: 'hidden',
    ...shadows.sm,
  },
  cell: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
  },
  cellBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  cellLabel: {
    fontSize: typography.sizes.base,
    color: colors.fg,
  },
  logoutBtn: {
    width: '100%',
    height: 48,
    borderRadius: radius.btn,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    ...shadows.sm,
  },
  logoutText: {
    fontSize: typography.sizes.base,
    color: colors.danger,
    fontWeight: '500',
  },
});
