// nuzzly-expo/app/admin.tsx
import { useState, useEffect, useMemo } from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';
import PageHeader from '../src/components/PageHeader';
import { useAuth } from '../src/hooks/useAuth';
import { supabase } from '../src/lib/supabase';

interface AdminStats {
  userCount: number;
  petCount: number;
  productCount: number;
  reviewCount: number;
  reviewLast7d: number;
  flaggedCount: number;
}

interface RecentReview {
  id: string;
  overall_rating?: number;
  review_text?: string;
  created_at?: string;
  products?: { name?: string } | null;
  public_profiles?: { username?: string; display_name?: string } | null;
}

interface FlaggedUser {
  id: string;
  username?: string;
  display_name?: string;
  trust_score?: number;
  flag_reason?: string;
}

const STAT_ACCENTS = ['#7BA7BC', '#A8C5A0', '#E8A87C', '#FF7A59', '#B59BD8', '#ff3b30'];

export default function AdminScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { profile } = useAuth();
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<AdminStats>({
    userCount: 0,
    petCount: 0,
    productCount: 0,
    reviewCount: 0,
    reviewLast7d: 0,
    flaggedCount: 0,
  });
  const [recentReviews, setRecentReviews] = useState<RecentReview[]>([]);
  const [flaggedUsers, setFlaggedUsers] = useState<FlaggedUser[]>([]);

  const isAdmin = !!profile?.is_admin;

  const statCards = useMemo(
    () => [
      { label: '总用户', value: stats.userCount, accent: STAT_ACCENTS[0] },
      { label: '总宠物', value: stats.petCount, accent: STAT_ACCENTS[1] },
      { label: '产品数', value: stats.productCount, accent: STAT_ACCENTS[2] },
      { label: '评价数', value: stats.reviewCount, accent: STAT_ACCENTS[3] },
      { label: '近7天新评价', value: stats.reviewLast7d, accent: STAT_ACCENTS[4] },
      { label: '被标记用户', value: stats.flaggedCount, accent: STAT_ACCENTS[5] },
    ],
    [stats]
  );

  useEffect(() => {
    if (!isAdmin) {
      setLoading(false);
      router.replace('/profile');
      return;
    }
    loadStats().finally(() => setLoading(false));
  }, [isAdmin, router]);

  async function loadStats() {
    const sevenDaysAgo = new Date(Date.now() - 7 * 86400000).toISOString();
    const [users, pets, products, reviews, recent, flagged, recentCount] = await Promise.all([
      supabase.from('public_profiles').select('id', { count: 'exact', head: true }),
      supabase.from('pets').select('id', { count: 'exact', head: true }),
      supabase.from('products').select('id', { count: 'exact', head: true }),
      supabase.from('product_reviews').select('id', { count: 'exact', head: true }),
      supabase
        .from('product_reviews')
        .select(
          'id, overall_rating, review_text, created_at, public_profiles!inner(username, display_name), products!inner(name)'
        )
        .order('created_at', { ascending: false })
        .limit(5),
      supabase
        .from('public_profiles')
        .select('id, username, display_name, trust_score, flag_reason')
        .eq('is_flagged', true)
        .limit(5),
      supabase.from('product_reviews').select('id', { count: 'exact', head: true }).gte('created_at', sevenDaysAgo),
    ]);

    setStats({
      userCount: (users.count as number) ?? 0,
      petCount: (pets.count as number) ?? 0,
      productCount: (products.count as number) ?? 0,
      reviewCount: (reviews.count as number) ?? 0,
      reviewLast7d: (recentCount.count as number) ?? 0,
      flaggedCount: (flagged.data?.length as number) ?? 0,
    });
    setRecentReviews((recent.data as RecentReview[]) || []);
    setFlaggedUsers((flagged.data as FlaggedUser[]) || []);
  }

  function formatTime(ts?: string) {
    if (!ts) return '';
    return new Date(ts).toLocaleDateString('zh-CN', { month: '2-digit', day: '2-digit' });
  }

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="管理员控制台" actionText="Admin" actionDisabled />
      <ScrollView
        style={styles.container}
        contentContainerStyle={{ paddingBottom: insets.bottom + spacing.xl }}
        showsVerticalScrollIndicator={false}
      >
        {loading ? (
          <View style={styles.skeletonList}>
            {[1, 2, 3].map((i) => (
              <View key={i} style={styles.skeletonCard} />
            ))}
          </View>
        ) : (
          <>
            <View style={styles.statsGrid}>
              {statCards.map((s) => (
                <View key={s.label} style={[styles.statCard, { borderLeftColor: s.accent }]}>
                  <Text style={styles.statValue}>{s.value}</Text>
                  <Text style={styles.statLabel}>{s.label}</Text>
                </View>
              ))}
            </View>

            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <Text style={styles.sectionTitle}>最近评价</Text>
                <Text style={styles.sectionCount}>共 {recentReviews.length} 条</Text>
              </View>
              {recentReviews.length ? (
                <View style={styles.listCard}>
                  {recentReviews.map((r) => (
                    <View key={r.id} style={styles.reviewItem}>
                      <View style={styles.reviewRating}>
                        <Text style={styles.reviewRatingText}>{r.overall_rating ?? '—'}</Text>
                      </View>
                      <View style={styles.reviewInfo}>
                        <Text style={styles.reviewProduct} numberOfLines={1}>
                          {r.products?.name ?? '—'}
                        </Text>
                        <Text style={styles.reviewText} numberOfLines={1}>
                          {r.review_text || '（无内容）'}
                        </Text>
                        <Text style={styles.reviewMeta}>
                          @
                          {r.public_profiles?.display_name ||
                            r.public_profiles?.username ||
                            '未知'} · {formatTime(r.created_at)}
                        </Text>
                      </View>
                    </View>
                  ))}
                </View>
              ) : (
                <View style={styles.emptyMini}>
                  <Text style={styles.emptyMiniText}>暂无最近评价</Text>
                </View>
              )}
            </View>

            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <Text style={styles.sectionTitle}>被标记用户</Text>
              </View>
              {flaggedUsers.length ? (
                <View style={styles.listCard}>
                  {flaggedUsers.map((u) => (
                    <View key={u.id} style={styles.userItem}>
                      <View style={styles.userAvatar}>
                        <Text style={styles.userAvatarText}>
                          {(u.display_name || u.username || '?').charAt(0)}
                        </Text>
                      </View>
                      <View style={styles.userInfo}>
                        <Text style={styles.userName} numberOfLines={1}>
                          {u.display_name || u.username}
                        </Text>
                        <Text style={styles.userReason} numberOfLines={1}>
                          {u.flag_reason || '已标记'}
                        </Text>
                      </View>
                      <Text style={styles.userScore}>信任分 {u.trust_score ?? 0}</Text>
                    </View>
                  ))}
                </View>
              ) : (
                <View style={styles.emptyMini}>
                  <Text style={styles.emptyMiniText}>
                    <Text style={{ color: colors.success }}>社区秩序良好</Text>，暂无被标记用户
                  </Text>
                </View>
              )}
            </View>
          </>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.pageX,
  },
  skeletonList: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  skeletonCard: {
    height: 80,
    borderRadius: radius['2xl'],
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingVertical: spacing.lg,
  },
  statCard: {
    width: '47.5%',
    backgroundColor: colors.card,
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    borderLeftWidth: 3,
    ...shadows.sm,
  },
  statValue: {
    fontSize: 24,
    fontWeight: typography.weights.bold,
    color: colors.fg,
  },
  statLabel: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginTop: 4,
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.sizes.lg,
    fontWeight: typography.weights.bold,
    color: colors.fg,
  },
  sectionCount: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    backgroundColor: 'rgba(0,0,0,0.04)',
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: radius.btn,
  },
  listCard: {
    backgroundColor: colors.card,
    borderRadius: radius['2xl'],
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  reviewItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  reviewRating: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,122,89,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewRatingText: {
    fontSize: 13,
    fontWeight: typography.weights.bold,
    color: '#FF7A59',
  },
  reviewInfo: {
    flex: 1,
    minWidth: 0,
  },
  reviewProduct: {
    fontSize: typography.sizes.sm,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
  },
  reviewText: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginTop: 2,
  },
  reviewMeta: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginTop: 4,
    opacity: 0.6,
  },
  userItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,59,48,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarText: {
    fontSize: 14,
    fontWeight: typography.weights.bold,
    color: colors.danger,
  },
  userInfo: {
    flex: 1,
    minWidth: 0,
  },
  userName: {
    fontSize: typography.sizes.sm,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
  },
  userReason: {
    fontSize: typography.sizes.xs,
    color: colors.danger,
    marginTop: 2,
  },
  userScore: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    backgroundColor: 'rgba(255,59,48,0.08)',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: radius.btn,
  },
  emptyMini: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: radius['2xl'],
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyMiniText: {
    fontSize: typography.sizes.base,
    color: colors.muted,
  },
});

// ios-app-frontend/src/views/Admin.vue
<template>
  <div class="app-shell">
    <header class="header anim-fade-up">
      <div class="header-row">
        <button class="back-btn" @click="$router.back()" aria-label="返回">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>
        </button>
        <h1 class="page-title">管理员控制台</h1>
        <span class="admin-badge">Admin</span>
      </div>
    </header>

    <div v-if="loading" class="list-body">
      <div v-for="i in 3" :key="i" class="skeleton-card shimmer"></div>
    </div>

    <template v-else>
      <!-- 统计卡片 -->
      <div class="stats-grid anim-fade-up anim-delay-1">
        <div v-for="s in statCards" :key="s.label" class="stat-card" :style="{ borderLeftColor: s.accent }">
          <div class="stat-value">{{ s.value }}</div>
          <div class="stat-label">{{ s.label }}</div>
        </div>
      </div>

      <!-- 最近评价 -->
      <div class="section anim-fade-up anim-delay-2">
        <div class="section-header">
          <h2 class="section-title">最近评价</h2>
          <span class="section-count">共 {{ recentReviews.length }} 条</span>
        </div>
        <div v-if="recentReviews.length" class="review-list">
          <div v-for="r in recentReviews" :key="r.id" class="review-item">
            <div class="review-rating">{{ r.overall_rating ?? '—' }}</div>
            <div class="review-info">
              <div class="review-product">{{ r.products?.name ?? '—' }}</div>
              <div class="review-text">{{ r.review_text || '（无内容）' }}</div>
              <div class="review-meta">@{{ r.profiles?.username ?? '未知' }} · {{ formatTime(r.created_at) }}</div>
            </div>
          </div>
        </div>
        <div v-else class="empty-mini">暂无最近评价</div>
      </div>

      <!-- 被标记用户 -->
      <div class="section anim-fade-up anim-delay-3">
        <div class="section-header">
          <h2 class="section-title">被标记用户</h2>
        </div>
        <div v-if="flaggedUsers.length" class="user-list">
          <div v-for="u in flaggedUsers" :key="u.id" class="user-item">
            <div class="user-avatar">{{ (u.display_name || u.username || '?').charAt(0) }}</div>
            <div class="user-info">
              <div class="user-name">{{ u.display_name || u.username }}</div>
              <div class="user-reason">{{ u.flag_reason || '已标记' }}</div>
            </div>
            <div class="user-score">信任分 {{ u.trust_score ?? 0 }}</div>
          </div>
        </div>
        <div v-else class="empty-mini">
          <span style="color:var(--green)">社区秩序良好</span>，暂无被标记用户
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../composables/useAuth'
import { supabase } from '../lib/supabase'

const router = useRouter()
const { profile } = useAuth()
const loading = ref(true)
const stats = ref({})
const recentReviews = ref([])
const flaggedUsers = ref([])

const isAdmin = computed(() => profile.value?.is_admin)

const statCards = computed(() => [
  { label: '总用户', value: stats.value.userCount ?? 0, accent: '#7BA7BC' },
  { label: '总宠物', value: stats.value.petCount ?? 0, accent: '#A8C5A0' },
  { label: '产品数', value: stats.value.productCount ?? 0, accent: '#E8A87C' },
  { label: '评价数', value: stats.value.reviewCount ?? 0, accent: '#FF7A59' },
  { label: '近7天新评价', value: stats.value.reviewLast7d ?? 0, accent: '#B59BD8' },
  { label: '被标记用户', value: stats.value.flaggedCount ?? 0, accent: '#ff3b30' },
])

function formatTime(ts) {
  if (!ts) return ''
  return new Date(ts).toLocaleDateString('zh-CN', { month: '2-digit', day: '2-digit' })
}

async function loadStats() {
  const sevenDaysAgo = new Date(Date.now() - 7 * 86400000).toISOString()
  const [users, pets, products, reviews, recent, flagged, recentCount] = await Promise.all([
    supabase.from('profiles').select('id', { count: 'exact', head: true }),
    supabase.from('pets').select('id', { count: 'exact', head: true }),
    supabase.from('products').select('id', { count: 'exact', head: true }),
    supabase.from('product_reviews').select('id', { count: 'exact', head: true }),
    supabase.from('product_reviews').select('id, overall_rating, review_text, created_at, profiles(username), products(name)').order('created_at', { ascending: false }).limit(5),
    supabase.from('profiles').select('id, username, display_name, trust_score, flag_reason').eq('is_flagged', true).limit(5),
    supabase.from('product_reviews').select('id', { count: 'exact', head: true }).gte('created_at', sevenDaysAgo)
  ])

  stats.value = {
    userCount: users.count ?? 0,
    petCount: pets.count ?? 0,
    productCount: products.count ?? 0,
    reviewCount: reviews.count ?? 0,
    reviewLast7d: recentCount.count ?? 0,
    flaggedCount: flagged.data?.length ?? 0
  }

  recentReviews.value = recent.data || []
  flaggedUsers.value = flagged.data || []
}

onMounted(async () => {
  if (!isAdmin.value) {
    loading.value = false
    router.replace('/profile')
    return
  }
  await loadStats()
  loading.value = false
})
</script>

<style scoped>
.app-shell{width:100%;min-height:100vh;min-height:100dvh;padding-top:var(--safe-top);padding-bottom:calc(88px + var(--safe-bottom));overflow-y:auto;overflow-x:hidden;-webkit-overflow-scrolling:touch}
.header{position:relative;padding:4px 24px 0;z-index:1}
.header-row{display:flex;align-items:center;justify-content:space-between}
.back-btn{width:36px;height:36px;border-radius:50%;background:var(--card);box-shadow:var(--shadow-card);display:flex;align-items:center;justify-content:center;border:1px solid var(--border);cursor:pointer;transition:transform .2s;flex-shrink:0}
.back-btn:active{transform:scale(.9)}
.back-btn svg{width:18px;height:18px;color:var(--fg)}
.page-title{font-family:var(--font-display);font-size:18px;font-weight:700;color:var(--fg)}
.admin-badge{font-size:10px;font-weight:600;color:#4A7A91;background:rgba(123,167,188,.12);padding:4px 10px;border-radius:var(--radius-btn)}
.list-body{padding:16px 20px;display:flex;flex-direction:column;gap:12px}
.skeleton-card{height:80px;border-radius:20px}
.stats-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;padding:16px 20px 0}
.stat-card{background:var(--card);border-radius:16px;padding:14px;box-shadow:var(--shadow-card);border:1px solid var(--border);border-left:3px solid transparent}
.stat-value{font-size:24px;font-weight:700;color:var(--fg);font-family:var(--font-num)}
.stat-label{font-size:11px;color:var(--muted);margin-top:4px}
.section{padding:20px 20px 0}
.section-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}
.section-title{font-size:17px;font-weight:700;color:var(--fg)}
.section-count{font-size:12px;color:var(--muted);background:rgba(0,0,0,.04);padding:3px 10px;border-radius:var(--radius-btn)}
.review-list{background:var(--card);border-radius:20px;overflow:hidden;box-shadow:var(--shadow-card);border:1px solid var(--border)}
.review-item{display:flex;align-items:flex-start;gap:12px;padding:14px;border-bottom:1px solid var(--border)}
.review-item:last-child{border-bottom:none}
.review-rating{width:32px;height:32px;border-radius:50%;background:rgba(255,122,89,.1);color:#FF7A59;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:700;flex-shrink:0}
.review-info{flex:1;min-width:0}
.review-product{font-size:13px;font-weight:600;color:var(--fg);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.review-text{font-size:12px;color:var(--muted);margin-top:2px;display:-webkit-box;-webkit-line-clamp:1;-webkit-box-orient:vertical;overflow:hidden}
.review-meta{font-size:11px;color:var(--muted);margin-top:4px;opacity:.6}
.user-list{background:var(--card);border-radius:20px;overflow:hidden;box-shadow:var(--shadow-card);border:1px solid var(--border)}
.user-item{display:flex;align-items:center;gap:12px;padding:14px;border-bottom:1px solid var(--border)}
.user-item:last-child{border-bottom:none}
.user-avatar{width:36px;height:36px;border-radius:50%;background:rgba(255,59,48,.1);color:#FF3B30;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700;flex-shrink:0}
.user-info{flex:1;min-width:0}
.user-name{font-size:13px;font-weight:600;color:var(--fg)}
.user-reason{font-size:11px;color:#FF3B30;margin-top:2px}
.user-score{font-size:11px;color:var(--muted);background:rgba(255,59,48,.08);padding:3px 8px;border-radius:var(--radius-btn);flex-shrink:0}
.empty-mini{text-align:center;padding:24px 16px;font-size:14px;color:var(--muted);background:var(--card);border-radius:20px;border:1px solid var(--border)}
.shimmer{background:linear-gradient(90deg,rgba(0,0,0,.04) 25%,rgba(0,0,0,.08) 37%,rgba(0,0,0,.04) 63%);background-size:400% 100%;animation:shimmer 1.4s ease infinite}
@keyframes shimmer{0%{background-position:100% 0}100%{background-position:0 0}}
.status-bar-spacer{height:var(--safe-top)}
@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
.anim-fade-up{opacity:0;animation:fadeUp .6s cubic-bezier(.22,1,.36,1) forwards}
.anim-delay-1{animation-delay:.1s}.anim-delay-2{animation-delay:.2s}.anim-delay-3{animation-delay:.3s}
</style>
