// nuzzly-expo/app/ai-health-report.tsx
import { useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
} from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import PageHeader from '../src/components/PageHeader';
import { useAIHealthReports } from '../src/hooks/useAIHealthReports';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';

const riskStyles: Record<string, { bg: string; color: string }> = {
  low: { bg: '#E8F5E9', color: '#2E7D32' },
  medium: { bg: '#FFF3E0', color: '#F57C00' },
  high: { bg: '#FFEBEE', color: '#C62828' },
  critical: { bg: '#F44336', color: '#fff' },
};

export default function AIHealthReportScreen() {
  const { pet } = useLocalSearchParams<{ pet?: string }>();
  const petId = pet || '';
  const insets = useSafeAreaInsets();
  const { healthReports, loading, generating, fetchHealthReports, generateHealthReport } =
    useAIHealthReports();

  useEffect(() => {
    if (petId) fetchHealthReports(petId);
  }, [petId]);

  const handleGenerate = async () => {
    try {
      await generateHealthReport(petId, { name: '宠物' });
    } catch (e) {
      console.error(e);
    }
  };

  const getRiskLabel = (level: string) => {
    const labels: Record<string, string> = {
      low: '低风险',
      medium: '中风险',
      high: '高风险',
      critical: '严重',
    };
    return labels[level] || '未知';
  };

  const parseRecommendations = (recs: string[] | string | undefined) => {
    if (Array.isArray(recs)) return recs;
    if (typeof recs === 'string') return recs.split('\n').filter(Boolean);
    return [];
  };

  const formatDate = (dateStr: string) => {
    const d = new Date(dateStr);
    return d.toLocaleDateString('zh-CN');
  };

  return (
    <View style={[styles.container, { paddingBottom: insets.bottom + spacing.md }]}>
      <PageHeader title="AI健康报告" />
      <ScrollView contentContainerStyle={styles.body}>
        {loading ? (
          <View style={styles.skeletonCard}>
            <View style={[styles.shimmerLine, { width: '40%' }]} />
            <View style={[styles.shimmerLine, { width: '80%' }]} />
            <View style={[styles.shimmerLine, { width: '60%' }]} />
          </View>
        ) : healthReports.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyIcon}>🤖</Text>
            <Text style={styles.emptyText}>暂无健康报告</Text>
            <Text style={styles.emptyHint}>AI会根据宠物的健康数据生成个性化报告</Text>
            <TouchableOpacity
              style={styles.generateBtn}
              disabled={generating}
              onPress={handleGenerate}
              activeOpacity={0.8}
            >
              <Text style={styles.generateBtnText}>
                {generating ? '生成中...' : '生成报告'}
              </Text>
            </TouchableOpacity>
          </View>
        ) : (
          <View style={styles.list}>
            <TouchableOpacity
              style={styles.generateBtn}
              disabled={generating}
              onPress={handleGenerate}
              activeOpacity={0.8}
            >
              <Text style={styles.generateBtnText}>
                {generating ? '生成中...' : '生成新报告'}
              </Text>
            </TouchableOpacity>

            {healthReports.map((report) => {
              const risk = riskStyles[report.risk_level] || riskStyles.low;
              return (
                <View key={report.id} style={styles.reportCard}>
                  <View style={styles.reportHeader}>
                    <Text style={styles.reportDate}>{formatDate(report.report_date)}</Text>
                    <View style={[styles.riskBadge, { backgroundColor: risk.bg }]}>
                      <Text style={[styles.riskText, { color: risk.color }]}>
                        {getRiskLabel(report.risk_level)}
                      </Text>
                    </View>
                  </View>
                  <Text style={styles.reportSummary}>{report.summary_text}</Text>
                  {parseRecommendations(report.recommendations).length > 0 && (
                    <View style={styles.recommendations}>
                      <Text style={styles.recTitle}>建议：</Text>
                      {parseRecommendations(report.recommendations).map((rec, idx) => (
                        <Text key={idx} style={styles.recItem}>
                          • {rec}
                        </Text>
                      ))}
                    </View>
                  )}
                  <View style={styles.reportMeta}>
                    <Text style={styles.metaText}>模型: {report.model_used || 'AI'}</Text>
                    <Text style={styles.metaText}>
                      耗时:{' '}
                      {report.processing_time_ms
                        ? `${(report.processing_time_ms / 1000).toFixed(1)}s`
                        : '-'}
                    </Text>
                  </View>
                </View>
              );
            })}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  body: {
    paddingHorizontal: spacing.pageX,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: spacing.lg,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  emptyText: {
    fontSize: 16,
    color: colors.fg,
    marginBottom: spacing.sm,
  },
  emptyHint: {
    fontSize: 13,
    color: colors.muted,
    marginBottom: spacing.lg,
  },
  generateBtn: {
    width: '100%',
    paddingVertical: 14,
    backgroundColor: '#FF6B4A',
    borderRadius: radius.lg,
    alignItems: 'center',
    marginBottom: spacing.lg,
    ...shadows.sm,
  },
  generateBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  list: {
    paddingVertical: spacing.md,
  },
  reportCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  reportDate: {
    fontSize: 14,
    color: colors.muted,
  },
  riskBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
  },
  riskText: {
    fontSize: 12,
    fontWeight: '500',
  },
  reportSummary: {
    fontSize: 14,
    color: colors.fg,
    lineHeight: 22,
    marginBottom: spacing.md,
  },
  recommendations: {
    backgroundColor: '#F9F9F9',
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  recTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.muted,
    marginBottom: spacing.sm,
  },
  recItem: {
    fontSize: 13,
    color: colors.fg,
    lineHeight: 20,
  },
  reportMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metaText: {
    fontSize: 12,
    color: colors.muted,
  },
  skeletonCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginTop: spacing.md,
    ...shadows.sm,
  },
  shimmerLine: {
    height: 12,
    borderRadius: radius.xs,
    backgroundColor: 'rgba(0,0,0,0.06)',
    marginBottom: spacing.sm,
  },
});

// ios-app-frontend/src/views/AIHealthReport.vue
<template>
  <div class="app-shell">
    <PageHeader title="AI健康报告" />

    <!-- 加载态 -->
    <div v-if="loading" class="skeleton-list">
      <div class="report-skeleton skeleton">
        <div class="shimmer-line w40"></div>
        <div class="shimmer-line w80"></div>
        <div class="shimmer-line w60"></div>
      </div>
    </div>

    <!-- 生成按钮 -->
    <div v-if="!loading && healthReports.length === 0" class="empty-state">
      <div class="empty-icon">🤖</div>
      <p class="empty-text">暂无健康报告</p>
      <p class="empty-hint">AI会根据宠物的健康数据生成个性化报告</p>
      <button class="generate-btn" :disabled="generating" @click="handleGenerate">
        {{ generating ? '生成中...' : '生成报告' }}
      </button>
    </div>

    <!-- 报告列表 -->
    <div v-else class="report-list">
      <button class="generate-btn" :disabled="generating" @click="handleGenerate">
        {{ generating ? '生成中...' : '生成新报告' }}
      </button>

      <div v-for="report in healthReports" :key="report.id" class="report-card">
        <div class="report-header">
          <span class="report-date">{{ formatDate(report.report_date) }}</span>
          <span class="risk-badge" :class="'risk-' + report.risk_level">
            {{ getRiskLabel(report.risk_level) }}
          </span>
        </div>
        <div class="report-summary">{{ report.summary_text }}</div>
        <div v-if="report.recommendations" class="report-recommendations">
          <div class="rec-title">建议：</div>
          <div v-for="(rec, idx) in parseRecommendations(report.recommendations)" :key="idx" class="rec-item">
            • {{ rec }}
          </div>
        </div>
        <div class="report-meta">
          <span>模型: {{ report.model_used || 'AI' }}</span>
          <span>耗时: {{ report.processing_time_ms ? (report.processing_time_ms / 1000).toFixed(1) + 's' : '-' }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useAIHealthReports } from '../composables/useAIHealthReports'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const petId = ref(route.query.pet || '')

const { healthReports, loading, generating, fetchHealthReports, generateHealthReport } = useAIHealthReports()

onMounted(() => {
  if (petId.value) {
    fetchHealthReports(petId.value)
  }
})

async function handleGenerate() {
  try {
    await generateHealthReport(petId.value, { name: '宠物' })
  } catch (e) {
    console.error(e)
  }
}

function getRiskLabel(level) {
  const labels = { low: '低风险', medium: '中风险', high: '高风险', critical: '严重' }
  return labels[level] || '未知'
}

function formatDate(dateStr) {
  const d = new Date(dateStr)
  return d.toLocaleDateString('zh-CN')
}

function parseRecommendations(recs) {
  if (Array.isArray(recs)) return recs
  if (typeof recs === 'string') return recs.split('\n').filter(Boolean)
  return []
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; margin-bottom: 8px; }
.empty-hint { font-size: 13px; color: #999; margin-bottom: 20px; }
.generate-btn { width: 100%; padding: 14px; background: #ff6b4a; color: #fff; border: none; border-radius: 12px; font-size: 15px; font-weight: 500; margin-bottom: 16px; }
.generate-btn:disabled { opacity: 0.6; }
.report-list { padding: 16px 0; }
.report-card { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
.report-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
.report-date { font-size: 14px; color: #666; }
.risk-badge { font-size: 12px; padding: 4px 10px; border-radius: 10px; font-weight: 500; }
.risk-low { background: #e8f5e9; color: #2e7d32; }
.risk-medium { background: #fff3e0; color: #f57c00; }
.risk-high { background: #ffebee; color: #c62828; }
.risk-critical { background: #f44336; color: #fff; }
.report-summary { font-size: 14px; color: #333; line-height: 1.6; margin-bottom: 12px; }
.report-recommendations { background: #f9f9f9; border-radius: 8px; padding: 12px; margin-bottom: 12px; }
.rec-title { font-size: 13px; font-weight: 500; color: #666; margin-bottom: 8px; }
.rec-item { font-size: 13px; color: #333; line-height: 1.6; }
.report-meta { display: flex; justify-content: space-between; font-size: 12px; color: #999; }
</style>
