// nuzzly-expo/app/allergies.tsx
import { useEffect, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  TextInput,
  Alert,
  StyleSheet,
} from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAllergies, Allergy } from '../src/hooks/useAllergies';
import PageHeader from '../src/components/PageHeader';
import BottomSheet from '../src/components/BottomSheet';
import EmptyState from '../src/components/EmptyState';
import { colors, spacing, radius, shadows, sizes, typography } from '../src/theme/tokens';

const SEVERITY_OPTIONS = [
  { value: 'mild', label: '轻微' },
  { value: 'moderate', label: '中度' },
  { value: 'severe', label: '严重' },
];

const SEVERITY_BG: Record<string, string> = {
  mild: '#e8f5e9',
  moderate: '#fff3e0',
  severe: '#ffebee',
};

const SEVERITY_ICON: Record<string, string> = {
  mild: '⚠️',
  moderate: '🔶',
  severe: '🔴',
};

function getSeverityClass(severity: string) {
  return SEVERITY_BG[severity] || SEVERITY_BG.mild;
}

function getSeverityIcon(severity: string) {
  return SEVERITY_ICON[severity] || '⚠️';
}

export default function AllergiesScreen() {
  const { pet } = useLocalSearchParams<{ pet?: string }>();
  const petId = pet || '';
  const insets = useSafeAreaInsets();
  const { allergies, loading, fetchAllergies, addAllergy, deleteAllergy, getSeverityLabel } =
    useAllergies();

  const [showSheet, setShowSheet] = useState(false);
  const [newAllergen, setNewAllergen] = useState('');
  const [newSeverity, setNewSeverity] = useState('mild');
  const [newConfirmed, setNewConfirmed] = useState(false);

  useEffect(() => {
    if (petId) fetchAllergies(petId);
  }, [petId]);

  async function handleAdd() {
    if (!newAllergen.trim() || !petId) return;
    try {
      await addAllergy({
        pet_id: petId,
        allergen: newAllergen.trim(),
        severity: newSeverity as Allergy['severity'],
        confirmed: newConfirmed,
      });
      setShowSheet(false);
      setNewAllergen('');
      setNewSeverity('mild');
      setNewConfirmed(false);
    } catch (e: any) {
      Alert.alert('添加失败', e.message || '请稍后重试');
    }
  }

  function handleDelete(allergy: Allergy) {
    Alert.alert('删除过敏原', `确定删除"${allergy.allergen}"吗？`, [
      { text: '取消', style: 'cancel' },
      {
        text: '删除',
        style: 'destructive',
        onPress: async () => {
          try {
            await deleteAllergy(allergy.id);
          } catch (e: any) {
            Alert.alert('删除失败', e.message || '请稍后重试');
          }
        },
      },
    ]);
  }

  const sheetFooter = (
    <View style={styles.sheetFooter}>
      <TouchableOpacity activeOpacity={0.8} onPress={() => setShowSheet(false)} style={styles.btnCancel}>
        <Text style={styles.btnCancelText}>取消</Text>
      </TouchableOpacity>
      <TouchableOpacity
        activeOpacity={0.8}
        disabled={!newAllergen.trim()}
        onPress={handleAdd}
        style={[styles.btnConfirm, !newAllergen.trim() && styles.btnConfirmDisabled]}
      >
        <Text style={styles.btnConfirmText}>添加</Text>
      </TouchableOpacity>
    </View>
  );

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="过敏管理" actionText="添加" onAction={() => setShowSheet(true)} />

      <ScrollView
        contentContainerStyle={[styles.body, { paddingBottom: insets.bottom + spacing.xl }]}
        showsVerticalScrollIndicator={false}
      >
        {loading ? (
          <View style={styles.skeletonList}>
            {[1, 2, 3].map((i) => (
              <View key={i} style={styles.skeletonRow}>
                <View style={styles.shimmerCircle} />
                <View style={styles.shimmerLine} />
              </View>
            ))}
          </View>
        ) : allergies.length === 0 ? (
          <EmptyState
            icon="🛡️"
            title="暂无过敏记录"
            description="添加过敏原可以帮助系统避开相关成分"
          />
        ) : (
          <View style={styles.list}>
            {allergies.map((allergy) => (
              <View key={allergy.id} style={styles.allergyCard}>
                <View style={[styles.allergyIcon, { backgroundColor: getSeverityClass(allergy.severity) }]}>
                  <Text style={styles.allergyIconText}>{getSeverityIcon(allergy.severity)}</Text>
                </View>
                <View style={styles.allergyInfo}>
                  <Text style={styles.allergyName}>{allergy.allergen}</Text>
                  <View style={styles.allergyMeta}>
                    <View
                      style={[
                        styles.severityTag,
                        { backgroundColor: getSeverityClass(allergy.severity) },
                      ]}
                    >
                      <Text style={styles.severityTagText}>{getSeverityLabel(allergy.severity)}</Text>
                    </View>
                    {allergy.confirmed ? (
                      <View style={styles.confirmedTag}>
                        <Text style={styles.confirmedTagText}>已确认</Text>
                      </View>
                    ) : null}
                  </View>
                </View>
                <TouchableOpacity
                  activeOpacity={0.7}
                  onPress={() => handleDelete(allergy)}
                  style={styles.deleteBtn}
                >
                  <Text style={styles.deleteBtnText}>×</Text>
                </TouchableOpacity>
              </View>
            ))}
          </View>
        )}
      </ScrollView>

      <BottomSheet visible={showSheet} onClose={() => setShowSheet(false)} title="添加过敏原" footer={sheetFooter}>
        <View style={styles.formGroup}>
          <Text style={styles.formLabel}>过敏原名称</Text>
          <TextInput
            value={newAllergen}
            onChangeText={setNewAllergen}
            placeholder="例如：鸡肉、谷物、海鲜"
            placeholderTextColor={colors.muted}
            style={styles.formInput}
          />
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.formLabel}>严重程度</Text>
          <View style={styles.severityOptions}>
            {SEVERITY_OPTIONS.map((opt) => {
              const active = newSeverity === opt.value;
              return (
                <TouchableOpacity
                  key={opt.value}
                  activeOpacity={0.8}
                  onPress={() => setNewSeverity(opt.value)}
                  style={[styles.severityBtn, active && styles.severityBtnActive]}
                >
                  <Text style={[styles.severityBtnText, active && styles.severityBtnTextActive]}>
                    {opt.label}
                  </Text>
                </TouchableOpacity>
              );
            })}
          </View>
        </View>

        <View style={styles.formGroup}>
          <View style={styles.toggleRow}>
            <Text style={styles.formLabel}>确认状态</Text>
            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => setNewConfirmed((v) => !v)}
              style={[styles.toggleBtn, newConfirmed && styles.toggleBtnActive]}
            >
              <View style={[styles.toggleDot, newConfirmed && styles.toggleDotActive]} />
            </TouchableOpacity>
          </View>
        </View>
      </BottomSheet>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  body: {
    paddingHorizontal: spacing.pageX,
    paddingTop: spacing.md,
  },
  skeletonList: {
    paddingVertical: spacing.md,
  },
  skeletonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    marginBottom: 8,
  },
  shimmerCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  shimmerLine: {
    flex: 1,
    height: 16,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.06)',
    maxWidth: '60%',
  },
  list: {
    paddingVertical: spacing.md,
  },
  allergyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: 12,
    marginBottom: 8,
  },
  allergyIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  allergyIconText: {
    fontSize: 18,
  },
  allergyInfo: {
    flex: 1,
  },
  allergyName: {
    fontSize: 15,
    fontWeight: typography.weights.medium,
    color: colors.fg,
  },
  allergyMeta: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  severityTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
  },
  severityTagText: {
    fontSize: 11,
    color: colors.fg,
  },
  confirmedTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    backgroundColor: '#e3f2fd',
  },
  confirmedTagText: {
    fontSize: 11,
    color: '#1976d2',
  },
  deleteBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtnText: {
    color: colors.muted,
    fontSize: 18,
    lineHeight: 22,
  },
  formGroup: {
    marginBottom: spacing.md,
  },
  formLabel: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: spacing.sm,
  },
  formInput: {
    height: sizes.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    fontSize: typography.sizes.md,
    color: colors.fg,
    backgroundColor: colors.bg,
  },
  severityOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  severityBtn: {
    flex: 1,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    alignItems: 'center',
  },
  severityBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  severityBtnText: {
    fontSize: 14,
    color: colors.fg,
  },
  severityBtnTextActive: {
    color: colors.card,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  toggleBtn: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.border,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleBtnActive: {
    backgroundColor: colors.primary,
  },
  toggleDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.card,
  },
  toggleDotActive: {
    alignSelf: 'flex-end',
  },
  sheetFooter: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  btnCancel: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    alignItems: 'center',
  },
  btnCancelText: {
    fontSize: 15,
    color: colors.fg,
  },
  btnConfirm: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  btnConfirmDisabled: {
    opacity: 0.5,
  },
  btnConfirmText: {
    fontSize: 15,
    color: colors.card,
  },
});

// ios-app-frontend/src/views/Allergies.vue
<template>
  <div class="app-shell">
    <PageHeader
      title="过敏管理"
      :action-text="'添加'"
      @action="showAddSheet = true"
    />

    <!-- 加载态 -->
    <div v-if="loading" class="skeleton-list">
      <div class="allergy-row skeleton" v-for="i in 3" :key="i">
        <div class="shimmer-circle"></div>
        <div class="shimmer-line w60"></div>
      </div>
    </div>

    <!-- 空状态 -->
    <div v-else-if="allergies.length === 0" class="empty-state">
      <div class="empty-icon">🛡️</div>
      <p class="empty-text">暂无过敏记录</p>
      <p class="empty-hint">添加过敏原可以帮助系统避开相关成分</p>
    </div>

    <!-- 过敏原列表 -->
    <div v-else class="allergy-list">
      <div
        v-for="allergy in allergies"
        :key="allergy.id"
        class="allergy-card"
      >
        <div class="allergy-icon" :class="getSeverityClass(allergy.severity)">
          {{ getSeverityIcon(allergy.severity) }}
        </div>
        <div class="allergy-info">
          <div class="allergy-name">{{ allergy.allergen }}</div>
          <div class="allergy-meta">
            <span class="severity-tag" :class="getSeverityClass(allergy.severity)">
              {{ getSeverityLabel(allergy.severity) }}
            </span>
            <span v-if="allergy.confirmed" class="confirmed-tag">已确认</span>
          </div>
        </div>
        <button class="delete-btn" @click="handleDelete(allergy)">×</button>
      </div>
    </div>

    <!-- 添加弹窗 -->
    <div v-if="showAddSheet" class="sheet-overlay" @click.self="showAddSheet = false">
      <div class="sheet-content">
        <div class="sheet-header">
          <span class="sheet-title">添加过敏原</span>
          <button class="sheet-close" @click="showAddSheet = false">×</button>
        </div>
        <div class="sheet-body">
          <div class="form-group">
            <label class="form-label">过敏原名称</label>
            <input
              v-model="newAllergen"
              class="form-input"
              placeholder="例如：鸡肉、谷物、海鲜"
            />
          </div>
          <div class="form-group">
            <label class="form-label">严重程度</label>
            <div class="severity-options">
              <button
                v-for="opt in severityOptions"
                :key="opt.value"
                class="severity-btn"
                :class="{ active: newSeverity === opt.value }"
                @click="newSeverity = opt.value"
              >
                {{ opt.label }}
              </button>
            </div>
          </div>
          <div class="form-group">
            <label class="form-label">确认状态</label>
            <div class="toggle-row">
              <span>已确认</span>
              <button
                class="toggle-btn"
                :class="{ active: newConfirmed }"
                @click="newConfirmed = !newConfirmed"
              >
                <span class="toggle-dot"></span>
              </button>
            </div>
          </div>
        </div>
        <div class="sheet-footer">
          <button class="btn-cancel" @click="showAddSheet = false">取消</button>
          <button
            class="btn-confirm"
            :disabled="!newAllergen.trim()"
            @click="handleAdd"
          >
            添加
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useAllergies } from '../composables/useAllergies'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const petId = ref(route.query.pet || '')

const { allergies, loading, fetchAllergies, addAllergy, deleteAllergy, getSeverityLabel } = useAllergies()

const showAddSheet = ref(false)
const newAllergen = ref('')
const newSeverity = ref('mild')
const newConfirmed = ref(false)

const severityOptions = [
  { value: 'mild', label: '轻微' },
  { value: 'moderate', label: '中度' },
  { value: 'severe', label: '严重' },
]

onMounted(() => {
  if (petId.value) {
    fetchAllergies(petId.value)
  }
})

function getSeverityClass(severity) {
  const classes = { mild: 'severity-mild', moderate: 'severity-moderate', severe: 'severity-severe' }
  return classes[severity] || 'severity-mild'
}

function getSeverityIcon(severity) {
  const icons = { mild: '⚠️', moderate: '🔶', severe: '🔴' }
  return icons[severity] || '⚠️'
}

async function handleAdd() {
  if (!newAllergen.value.trim()) return
  try {
    await addAllergy({
      pet_id: petId.value,
      allergen: newAllergen.value.trim(),
      severity: newSeverity.value,
      confirmed: newConfirmed.value,
    })
    showAddSheet.value = false
    newAllergen.value = ''
    newSeverity.value = 'mild'
    newConfirmed.value = false
  } catch (e) {
    console.error(e)
  }
}

async function handleDelete(allergy) {
  if (confirm(`确定删除过敏原"${allergy.allergen}"吗？`)) {
    await deleteAllergy(allergy.id, allergy.confirmed)
  }
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; margin-bottom: 8px; }
.empty-hint { font-size: 13px; color: #999; }
.allergy-list { padding: 16px 0; }
.allergy-card { display: flex; align-items: center; gap: 12px; background: #fff; border-radius: 12px; padding: 12px; margin-bottom: 8px; }
.allergy-icon { width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 18px; }
.severity-mild { background: #e8f5e9; }
.severity-moderate { background: #fff3e0; }
.severity-severe { background: #ffebee; }
.allergy-info { flex: 1; }
.allergy-name { font-size: 15px; font-weight: 500; color: #333; }
.allergy-meta { display: flex; gap: 8px; margin-top: 4px; }
.severity-tag { font-size: 11px; padding: 2px 8px; border-radius: 10px; }
.confirmed-tag { font-size: 11px; padding: 2px 8px; border-radius: 10px; background: #e3f2fd; color: #1976d2; }
.delete-btn { width: 28px; height: 28px; border-radius: 50%; border: none; background: #f5f5f5; color: #999; font-size: 18px; cursor: pointer; }
.sheet-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 100; display: flex; align-items: flex-end; }
.sheet-content { width: 100%; background: #fff; border-radius: 16px 16px 0 0; padding: 20px; }
.sheet-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
.sheet-title { font-size: 17px; font-weight: 600; }
.sheet-close { width: 28px; height: 28px; border: none; background: #f5f5f5; border-radius: 50%; font-size: 18px; }
.form-group { margin-bottom: 16px; }
.form-label { display: block; font-size: 14px; color: #666; margin-bottom: 8px; }
.form-input { width: 100%; padding: 12px; border: 1px solid #e0e0e0; border-radius: 8px; font-size: 15px; }
.severity-options { display: flex; gap: 8px; }
.severity-btn { flex: 1; padding: 10px; border: 1px solid #e0e0e0; border-radius: 8px; background: #fff; font-size: 14px; }
.severity-btn.active { background: #ff6b4a; color: #fff; border-color: #ff6b4a; }
.toggle-row { display: flex; justify-content: space-between; align-items: center; }
.toggle-btn { width: 48px; height: 28px; border-radius: 14px; border: none; background: #e0e0e0; position: relative; transition: background 0.3s; }
.toggle-btn.active { background: #ff6b4a; }
.toggle-dot { position: absolute; top: 2px; left: 2px; width: 24px; height: 24px; border-radius: 50%; background: #fff; transition: transform 0.3s; }
.toggle-btn.active .toggle-dot { transform: translateX(20px); }
.sheet-footer { display: flex; gap: 12px; margin-top: 20px; }
.btn-cancel { flex: 1; padding: 12px; border: 1px solid #e0e0e0; border-radius: 8px; background: #fff; font-size: 15px; }
.btn-confirm { flex: 1; padding: 12px; border: none; border-radius: 8px; background: #ff6b4a; color: #fff; font-size: 15px; }
.btn-confirm:disabled { opacity: 0.5; }
</style>
