// nuzzly-expo/app/diseases.tsx
import { useEffect, useMemo, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  TextInput,
  Alert,
  StyleSheet,
} from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useDiseaseRecords, DiseaseRecord } from '../src/hooks/useDiseaseRecords';
import PageHeader from '../src/components/PageHeader';
import BottomSheet from '../src/components/BottomSheet';
import EmptyState from '../src/components/EmptyState';
import { colors, spacing, radius, shadows, sizes, typography } from '../src/theme/tokens';

const SEVERITY_OPTIONS = [
  { value: 'mild', label: '轻微' },
  { value: 'moderate', label: '中度' },
  { value: 'severe', label: '严重' },
];

const STATUS_OPTIONS = [
  { value: 'active', label: '进行中' },
  { value: 'under_treatment', label: '治疗中' },
  { value: 'chronic', label: '慢性病' },
  { value: 'resolved', label: '已康复' },
];

const STATUS_BG: Record<string, string> = {
  active: '#fff3e0',
  under_treatment: '#e3f2fd',
  chronic: '#f5f5f5',
  resolved: '#e8f5e9',
};

const STATUS_TEXT: Record<string, string> = {
  active: '#f57c00',
  under_treatment: '#1976d2',
  chronic: '#666',
  resolved: '#2e7d32',
};

const SEVERITY_BG: Record<string, string> = {
  mild: '#e8f5e9',
  moderate: '#fff3e0',
  severe: '#ffebee',
};

export default function DiseasesScreen() {
  const { pet } = useLocalSearchParams<{ pet?: string }>();
  const petId = pet || '';
  const insets = useSafeAreaInsets();
  const { diseaseRecords, loading, fetchDiseaseRecords, createDiseaseRecord, getSeverityLabel, getStatusLabel } =
    useDiseaseRecords();

  const [showSheet, setShowSheet] = useState(false);
  const [newName, setNewName] = useState('');
  const [newSeverity, setNewSeverity] = useState('mild');
  const [newStatus, setNewStatus] = useState('active');

  useEffect(() => {
    if (petId) fetchDiseaseRecords(petId);
  }, [petId]);

  const stats = useMemo(() => {
    const active = diseaseRecords.filter(
      (d) => d.status === 'active' || d.status === 'under_treatment'
    );
    const chronic = diseaseRecords.filter((d) => d.status === 'chronic');
    const resolved = diseaseRecords.filter((d) => d.status === 'resolved');
    return { active, chronic, resolved };
  }, [diseaseRecords]);

  async function handleAdd() {
    if (!newName.trim() || !petId) return;
    try {
      await createDiseaseRecord({
        pet_id: petId,
        name: newName.trim(),
        severity: newSeverity as DiseaseRecord['severity'],
        status: newStatus as DiseaseRecord['status'],
      });
      setShowSheet(false);
      setNewName('');
      setNewSeverity('mild');
      setNewStatus('active');
    } catch (e: any) {
      Alert.alert('保存失败', e.message || '请稍后重试');
    }
  }

  function formatDate(dateStr?: string) {
    if (!dateStr) return '-';
    const d = new Date(dateStr);
    return `${d.getMonth() + 1}/${d.getDate()}`;
  }

  const sheetFooter = (
    <View style={styles.sheetFooter}>
      <TouchableOpacity activeOpacity={0.8} onPress={() => setShowSheet(false)} style={styles.btnCancel}>
        <Text style={styles.btnCancelText}>取消</Text>
      </TouchableOpacity>
      <TouchableOpacity
        activeOpacity={0.8}
        disabled={!newName.trim()}
        onPress={handleAdd}
        style={[styles.btnConfirm, !newName.trim() && styles.btnConfirmDisabled]}
      >
        <Text style={styles.btnConfirmText}>保存</Text>
      </TouchableOpacity>
    </View>
  );

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="疾病记录" actionText="添加" onAction={() => setShowSheet(true)} />

      <ScrollView
        contentContainerStyle={[styles.body, { paddingBottom: insets.bottom + spacing.xl }]}
        showsVerticalScrollIndicator={false}
      >
        {!loading && (
          <View style={styles.statsRow}>
            <View style={styles.statCard}>
              <Text style={[styles.statValue, { color: '#ff9500' }]}>{stats.active.length}</Text>
              <Text style={styles.statLabel}>进行中</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={[styles.statValue, { color: '#585858' }]}>{stats.chronic.length}</Text>
              <Text style={styles.statLabel}>慢性病</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={[styles.statValue, { color: '#34c759' }]}>{stats.resolved.length}</Text>
              <Text style={styles.statLabel}>已康复</Text>
            </View>
          </View>
        )}

        {!loading && diseaseRecords.length === 0 ? (
          <EmptyState icon="🏥" title="暂无疾病记录" />
        ) : (
          <View style={styles.list}>
            {diseaseRecords.map((record) => (
              <View key={record.id} style={styles.recordCard}>
                <View style={[styles.recordIcon, { backgroundColor: SEVERITY_BG[record.severity] || '#f5f5f5' }]}>
                  <Text style={styles.recordIconText}>🏥</Text>
                </View>
                <View style={styles.recordInfo}>
                  <Text style={styles.recordName}>{record.name}</Text>
                  <View style={styles.recordMeta}>
                    <View
                      style={[
                        styles.statusTag,
                        { backgroundColor: STATUS_BG[record.status] || '#f5f5f5' },
                      ]}
                    >
                      <Text style={[styles.statusTagText, { color: STATUS_TEXT[record.status] || '#666' }]}>
                        {getStatusLabel(record.status)}
                      </Text>
                    </View>
                    <View
                      style={[
                        styles.severityTag,
                        { backgroundColor: SEVERITY_BG[record.severity] || '#f5f5f5' },
                      ]}
                    >
                      <Text style={styles.severityTagText}>{getSeverityLabel(record.severity)}</Text>
                    </View>
                  </View>
                </View>
                <Text style={styles.recordDate}>{formatDate(record.diagnosed_on)}</Text>
              </View>
            ))}
          </View>
        )}
      </ScrollView>

      <BottomSheet
        visible={showSheet}
        onClose={() => setShowSheet(false)}
        title="添加疾病记录"
        footer={sheetFooter}
      >
        <View style={styles.formGroup}>
          <Text style={styles.formLabel}>疾病名称</Text>
          <TextInput
            value={newName}
            onChangeText={setNewName}
            placeholder="例如：感冒、肠胃炎"
            placeholderTextColor={colors.muted}
            style={styles.formInput}
          />
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.formLabel}>严重程度</Text>
          <View style={styles.optionsRow}>
            {SEVERITY_OPTIONS.map((opt) => {
              const active = newSeverity === opt.value;
              return (
                <TouchableOpacity
                  key={opt.value}
                  activeOpacity={0.8}
                  onPress={() => setNewSeverity(opt.value)}
                  style={[styles.optionBtn, active && styles.optionBtnActive]}
                >
                  <Text style={[styles.optionBtnText, active && styles.optionBtnTextActive]}>{opt.label}</Text>
                </TouchableOpacity>
              );
            })}
          </View>
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.formLabel}>当前状态</Text>
          <View style={styles.optionsRow}>
            {STATUS_OPTIONS.map((opt) => {
              const active = newStatus === opt.value;
              return (
                <TouchableOpacity
                  key={opt.value}
                  activeOpacity={0.8}
                  onPress={() => setNewStatus(opt.value)}
                  style={[styles.optionBtn, active && styles.optionBtnActive]}
                >
                  <Text style={[styles.optionBtnText, active && styles.optionBtnTextActive]}>{opt.label}</Text>
                </TouchableOpacity>
              );
            })}
          </View>
        </View>
      </BottomSheet>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  body: {
    paddingHorizontal: spacing.pageX,
    paddingTop: spacing.md,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginVertical: spacing.md,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.md,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 28,
    fontWeight: typography.weights.semibold,
  },
  statLabel: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 4,
  },
  list: {
    paddingVertical: spacing.md,
  },
  recordCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: 14,
    marginBottom: 8,
  },
  recordIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordIconText: {
    fontSize: 20,
  },
  recordInfo: {
    flex: 1,
  },
  recordName: {
    fontSize: 15,
    fontWeight: typography.weights.medium,
    color: colors.fg,
  },
  recordMeta: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  statusTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
  },
  statusTagText: {
    fontSize: 11,
  },
  severityTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
  },
  severityTagText: {
    fontSize: 11,
    color: colors.fg,
  },
  recordDate: {
    fontSize: 13,
    color: colors.muted,
  },
  formGroup: {
    marginBottom: spacing.md,
  },
  formLabel: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: spacing.sm,
  },
  formInput: {
    height: sizes.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    fontSize: typography.sizes.md,
    color: colors.fg,
    backgroundColor: colors.bg,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
  },
  optionBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionBtnText: {
    fontSize: 13,
    color: colors.fg,
  },
  optionBtnTextActive: {
    color: colors.card,
  },
  sheetFooter: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  btnCancel: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.card,
    alignItems: 'center',
  },
  btnCancelText: {
    fontSize: 15,
    color: colors.fg,
  },
  btnConfirm: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  btnConfirmDisabled: {
    opacity: 0.5,
  },
  btnConfirmText: {
    fontSize: 15,
    color: colors.card,
  },
});

// ios-app-frontend/src/views/Diseases.vue
<template>
  <div class="app-shell">
    <PageHeader title="疾病记录" :action-text="'添加'" @action="showAddSheet = true" />

    <!-- 统计卡片 -->
    <div class="stats-row" v-if="!loading">
      <div class="stat-card">
        <div class="stat-value" style="color: #ff9500;">{{ activeDiseases.length }}</div>
        <div class="stat-label">进行中</div>
      </div>
      <div class="stat-card">
        <div class="stat-value" style="color: #585858;">{{ chronicDiseases.length }}</div>
        <div class="stat-label">慢性病</div>
      </div>
      <div class="stat-card">
        <div class="stat-value" style="color: #34c759;">{{ resolvedDiseases.length }}</div>
        <div class="stat-label">已康复</div>
      </div>
    </div>

    <!-- 空状态 -->
    <div v-if="!loading && diseaseRecords.length === 0" class="empty-state">
      <div class="empty-icon">🏥</div>
      <p class="empty-text">暂无疾病记录</p>
    </div>

    <!-- 记录列表 -->
    <div v-else class="record-list">
      <div v-for="record in diseaseRecords" :key="record.id" class="record-card">
        <div class="record-icon" :class="'severity-' + record.severity">🏥</div>
        <div class="record-info">
          <div class="record-name">{{ record.name }}</div>
          <div class="record-meta">
            <span class="status-tag" :class="'status-' + record.status">{{ getStatusLabel(record.status) }}</span>
            <span class="severity-tag">{{ getSeverityLabel(record.severity) }}</span>
          </div>
        </div>
        <div class="record-date">{{ formatDate(record.diagnosed_on) }}</div>
      </div>
    </div>

    <!-- 添加弹窗 -->
    <div v-if="showAddSheet" class="sheet-overlay" @click.self="showAddSheet = false">
      <div class="sheet-content">
        <div class="sheet-header">
          <span class="sheet-title">添加疾病记录</span>
          <button class="sheet-close" @click="showAddSheet = false">×</button>
        </div>
        <div class="sheet-body">
          <div class="form-group">
            <label class="form-label">疾病名称</label>
            <input v-model="newName" class="form-input" placeholder="例如：感冒、肠胃炎" />
          </div>
          <div class="form-group">
            <label class="form-label">严重程度</label>
            <div class="severity-options">
              <button v-for="opt in severityOptions" :key="opt.value" class="severity-btn" :class="{ active: newSeverity === opt.value }" @click="newSeverity = opt.value">
                {{ opt.label }}
              </button>
            </div>
          </div>
          <div class="form-group">
            <label class="form-label">当前状态</label>
            <div class="status-options">
              <button v-for="opt in statusOptions" :key="opt.value" class="status-btn" :class="{ active: newStatus === opt.value }" @click="newStatus = opt.value">
                {{ opt.label }}
              </button>
            </div>
          </div>
        </div>
        <div class="sheet-footer">
          <button class="btn-cancel" @click="showAddSheet = false">取消</button>
          <button class="btn-confirm" :disabled="!newName.trim()" @click="handleAdd">保存</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useDiseaseRecords } from '../composables/useDiseaseRecords'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const petId = ref(route.query.pet || '')

const { diseaseRecords, loading, fetchDiseaseRecords, createDiseaseRecord, getSeverityLabel, getStatusLabel } = useDiseaseRecords()

const showAddSheet = ref(false)
const newName = ref('')
const newSeverity = ref('mild')
const newStatus = ref('active')

const severityOptions = [
  { value: 'mild', label: '轻微' },
  { value: 'moderate', label: '中度' },
  { value: 'severe', label: '严重' },
]

const statusOptions = [
  { value: 'active', label: '进行中' },
  { value: 'under_treatment', label: '治疗中' },
  { value: 'chronic', label: '慢性病' },
  { value: 'resolved', label: '已康复' },
]

const activeDiseases = computed(() => diseaseRecords.value.filter(d => d.status === 'active' || d.status === 'under_treatment'))
const chronicDiseases = computed(() => diseaseRecords.value.filter(d => d.status === 'chronic'))
const resolvedDiseases = computed(() => diseaseRecords.value.filter(d => d.status === 'resolved'))

onMounted(() => {
  if (petId.value) fetchDiseaseRecords(petId.value)
})

async function handleAdd() {
  if (!newName.value.trim()) return
  try {
    await createDiseaseRecord({ pet_id: petId.value, name: newName.value.trim(), severity: newSeverity.value, status: newStatus.value })
    showAddSheet.value = false
    newName.value = ''
    newSeverity.value = 'mild'
    newStatus.value = 'active'
  } catch (e) { console.error(e) }
}

function formatDate(dateStr) {
  if (!dateStr) return '-'
  const d = new Date(dateStr)
  return `${d.getMonth() + 1}/${d.getDate()}`
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.stats-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }
.stat-card { background: #fff; border-radius: 12px; padding: 16px; text-align: center; }
.stat-value { font-size: 28px; font-weight: 600; }
.stat-label { font-size: 12px; color: #999; margin-top: 4px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; }
.record-list { padding: 16px 0; }
.record-card { display: flex; align-items: center; gap: 12px; background: #fff; border-radius: 12px; padding: 14px; margin-bottom: 8px; }
.record-icon { width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 20px; background: #f5f5f5; }
.record-info { flex: 1; }
.record-name { font-size: 15px; font-weight: 500; color: #333; }
.record-meta { display: flex; gap: 8px; margin-top: 4px; }
.status-tag, .severity-tag { font-size: 11px; padding: 2px 8px; border-radius: 10px; }
.status-active { background: #fff3e0; color: #f57c00; }
.status-under_treatment { background: #e3f2fd; color: #1976d2; }
.status-chronic { background: #f5f5f5; color: #666; }
.status-resolved { background: #e8f5e9; color: #2e7d32; }
.record-date { font-size: 13px; color: #999; }
.sheet-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 100; display: flex; align-items: flex-end; }
.sheet-content { width: 100%; background: #fff; border-radius: 16px 16px 0 0; padding: 20px; }
.sheet-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
.sheet-title { font-size: 17px; font-weight: 600; }
.sheet-close { width: 28px; height: 28px; border: none; background: #f5f5f5; border-radius: 50%; font-size: 18px; }
.form-group { margin-bottom: 16px; }
.form-label { display: block; font-size: 14px; color: #666; margin-bottom: 8px; }
.form-input { width: 100%; padding: 12px; border: 1px solid #e0e0e0; border-radius: 8px; font-size: 15px; }
.severity-options, .status-options { display: flex; flex-wrap: wrap; gap: 8px; }
.severity-btn, .status-btn { padding: 8px 16px; border: 1px solid #e0e0e0; border-radius: 8px; background: #fff; font-size: 13px; }
.severity-btn.active, .status-btn.active { background: #ff6b4a; color: #fff; border-color: #ff6b4a; }
.sheet-footer { display: flex; gap: 12px; margin-top: 20px; }
.btn-cancel { flex: 1; padding: 12px; border: 1px solid #e0e0e0; border-radius: 8px; background: #fff; font-size: 15px; }
.btn-confirm { flex: 1; padding: 12px; border: none; border-radius: 8px; background: #ff6b4a; color: #fff; font-size: 15px; }
.btn-confirm:disabled { opacity: 0.5; }
</style>
