// nuzzly-expo/app/recommendations.tsx
import { useEffect, useCallback } from 'react';
import { View, Text, ScrollView, TouchableOpacity, ActivityIndicator, StyleSheet } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';
import PageHeader from '../src/components/PageHeader';
import EmptyState from '../src/components/EmptyState';
import { useRecommendations } from '../src/hooks/useRecommendations';

export default function RecommendationsScreen() {
  const insets = useSafeAreaInsets();
  const { pet } = useLocalSearchParams<{ pet?: string }>();
  const { recommendations, loading, generating, fetchRecommendations, generateRecommendations } =
    useRecommendations();

  useEffect(() => {
    if (pet) fetchRecommendations(pet);
  }, [pet]);

  const handleGenerate = useCallback(async () => {
    if (!pet) return;
    await generateRecommendations(pet);
  }, [pet, generateRecommendations]);

  const isBusy = loading || generating;

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="推荐系统" />
      <ScrollView
        style={styles.container}
        contentContainerStyle={{ paddingBottom: insets.bottom + spacing.xl }}
        showsVerticalScrollIndicator={false}
      >
        {isBusy ? (
          <View style={styles.loadingState}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={styles.loadingText}>
              {generating ? '正在生成推荐...' : '加载中...'}
            </Text>
          </View>
        ) : recommendations.length === 0 ? (
          <EmptyState
            icon="🎯"
            title="暂无推荐"
            description="系统会根据宠物信息生成个性化推荐"
            actionText="生成推荐"
            onAction={handleGenerate}
          />
        ) : (
          <View style={styles.list}>
            {recommendations.map((rec, idx) => (
              <View key={rec.id || idx} style={styles.recCard}>
                <View style={styles.recRank}>
                  <Text style={styles.recRankText}>#{idx + 1}</Text>
                </View>
                <View style={styles.recInfo}>
                  <Text style={styles.recName}>{rec.products?.name || '产品'}</Text>
                  <Text style={styles.recBrand}>{rec.products?.brand}</Text>
                  <Text style={styles.recScore}>匹配度: {rec.score ?? '-'}</Text>
                </View>
                {rec.products?.price_max != null ? (
                  <Text style={styles.recPrice}>¥{rec.products.price_max}</Text>
                ) : null}
              </View>
            ))}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.pageX,
  },
  loadingState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing['3xl'],
  },
  loadingText: {
    marginTop: spacing.md,
    fontSize: typography.sizes.base,
    color: colors.muted,
  },
  list: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  recCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  recRank: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recRankText: {
    fontSize: 14,
    fontWeight: typography.weights.bold,
    color: colors.card,
  },
  recInfo: {
    flex: 1,
  },
  recName: {
    fontSize: typography.sizes.md,
    fontWeight: typography.weights.medium,
    color: colors.fg,
  },
  recBrand: {
    fontSize: typography.sizes.sm,
    color: colors.muted,
    marginTop: 2,
  },
  recScore: {
    fontSize: typography.sizes.xs,
    color: colors.primary,
    marginTop: 4,
    fontWeight: typography.weights.medium,
  },
  recPrice: {
    fontSize: typography.sizes.lg,
    fontWeight: typography.weights.bold,
    color: colors.fg,
  },
});

// ios-app-frontend/src/views/Recommendations.vue
<template>
  <div class="app-shell">
    <PageHeader title="推荐系统" />

    <!-- 加载态 -->
    <div v-if="loading || generating" class="loading-state">
      <div class="loading-spinner"></div>
      <p>{{ generating ? '正在生成推荐...' : '加载中...' }}</p>
    </div>

    <!-- 空状态 -->
    <div v-else-if="recommendations.length === 0" class="empty-state">
      <div class="empty-icon">🎯</div>
      <p class="empty-text">暂无推荐</p>
      <p class="empty-hint">系统会根据宠物信息生成个性化推荐</p>
      <button class="generate-btn" @click="handleGenerate">生成推荐</button>
    </div>

    <!-- 推荐列表 -->
    <div v-else class="recommendation-list">
      <div v-for="(rec, idx) in recommendations" :key="idx" class="rec-card">
        <div class="rec-rank">#{{ idx + 1 }}</div>
        <div class="rec-info">
          <div class="rec-name">{{ rec.products?.name || '产品' }}</div>
          <div class="rec-brand">{{ rec.products?.brand }}</div>
          <div class="rec-score">匹配度: {{ rec.score || '-' }}</div>
        </div>
        <div class="rec-price" v-if="rec.products?.price_max">
          ¥{{ rec.products.price_max }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useRecommendations } from '../composables/useRecommendations'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const petId = ref(route.query.pet || '')

const { recommendations, loading, generating, fetchRecommendations, generateRecommendations } = useRecommendations()

onMounted(() => {
  if (petId.value) fetchRecommendations(petId.value)
})

async function handleGenerate() {
  if (!petId.value) return
  await generateRecommendations(petId.value, {})
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.loading-state { text-align: center; padding: 60px 20px; }
.loading-spinner { width: 40px; height: 40px; border: 3px solid #e0e0e0; border-top-color: #ff6b4a; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 16px; }
@keyframes spin { to { transform: rotate(360deg); } }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; margin-bottom: 8px; }
.empty-hint { font-size: 13px; color: #999; margin-bottom: 20px; }
.generate-btn { padding: 12px 32px; background: #ff6b4a; color: #fff; border: none; border-radius: 12px; font-size: 15px; }
.recommendation-list { padding: 16px 0; }
.rec-card { display: flex; align-items: center; gap: 12px; background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
.rec-rank { width: 32px; height: 32px; border-radius: 50%; background: #ff6b4a; color: #fff; display: flex; align-items: center; justify-content: center; font-size: 14px; font-weight: 600; }
.rec-info { flex: 1; }
.rec-name { font-size: 15px; font-weight: 500; color: #333; }
.rec-brand { font-size: 13px; color: #999; }
.rec-score { font-size: 12px; color: #ff6b4a; margin-top: 4px; }
.rec-price { font-size: 16px; font-weight: 600; color: #333; }
</style>
