// nuzzly-expo/app/records.tsx
import { useEffect, useMemo, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, Alert, StyleSheet } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { usePets } from '../src/hooks/usePets';
import { useDietLogs, DietLog } from '../src/hooks/useDietLogs';
import { useHealthRecords, HealthRecord } from '../src/hooks/useHealthRecords';
import PetChipGroup from '../src/components/PetChipGroup';
import { colors, spacing, radius, shadows, sizes, typography } from '../src/theme/tokens';

const SPECIES_EMOJI: Record<string, string> = { cat: '🐱', dog: '🐶' };
const FOOD_ICON: Record<string, string> = { dry_food: '🍖', wet_food: '🐟', water: '💧', treat: '🦴' };
const RECORD_ICON: Record<string, string> = {
  vaccination: '💉',
  symptom: '🩺',
  medication: '💊',
  diagnosis: '📋',
  checkup: '🩻',
  weight: '⚖️',
};
const SEVERITY_LABEL: Record<string, string> = { mild: '轻度', moderate: '中度', severe: '重度' };

export default function RecordsScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { pets, fetchPets } = usePets();
  const { dietLogs: rawDietLogs, fetchDietLogs, deleteDietLog } = useDietLogs();
  const { healthRecords: rawHealth, weightRecords, allergies, timeline, fetchHealthRecords, fetchAllergies } = useHealthRecords();

  const [selectedPet, setSelectedPet] = useState<string>('');

  const petChips = useMemo(
    () => pets.map((p) => ({ id: p.id, name: p.name, emoji: SPECIES_EMOJI[p.species] || '🐾' })),
    [pets]
  );

  const mappedDietLogs = useMemo(
    () =>
      rawDietLogs.map((l: DietLog) => ({
        id: l.id,
        icon: FOOD_ICON[l.food_type] || '🍽️',
        name: l.food_name,
        desc: l.notes || l.food_type,
        time: (l.created_at || l.logged_date || '').slice(11, 16) || '—',
      })),
    [rawDietLogs]
  );

  const mappedHealthRecords = useMemo(
    () =>
      rawHealth.map((r: HealthRecord) => ({
        id: r.id,
        icon: RECORD_ICON[r.record_type] || '📋',
        type: r.record_type,
        name: r.diagnosis || r.medication_name || r.record_type,
        desc: r.notes || '',
        date: (r.record_time || '').slice(5, 10),
      })),
    [rawHealth]
  );

  const latestWeight = useMemo(() => {
    const w = weightRecords[0]?.weight_kg;
    return w ? `${Number(w).toFixed(1)} kg` : '-- kg';
  }, [weightRecords]);

  const allergyTags = useMemo(
    () => allergies.map((a) => ({ text: a.allergen, level: SEVERITY_LABEL[a.severity] || '' })),
    [allergies]
  );

  const weightDots = useMemo(() => {
    const recs = weightRecords.slice(0, 7).reverse();
    if (!recs.length) return [];
    const weights = recs.map((r) => Number(r.weight_kg));
    const min = Math.min(...weights);
    const max = Math.max(...weights);
    return weights.map((w) => 10 + ((w - min) / (max - min || 1)) * 18);
  }, [weightRecords]);

  async function loadAll(petId: string) {
    await Promise.all([fetchHealthRecords(petId), fetchDietLogs(petId)]);
    if (petId) fetchAllergies(petId);
  }

  useEffect(() => {
    fetchPets().then(() => {
      if (pets.length && !selectedPet) {
        setSelectedPet(pets[0].id);
        loadAll(pets[0].id);
      }
    });
  }, []);

  useEffect(() => {
    if (selectedPet) loadAll(selectedPet);
  }, [selectedPet]);

  async function onDeleteDietLog(id: string) {
    Alert.alert('确定要删除这条饮食记录吗？', '', [
      { text: '取消', style: 'cancel' },
      {
        text: '删除',
        style: 'destructive',
        onPress: async () => {
          try {
            await deleteDietLog(id);
            Alert.alert('已删除');
          } catch (e: any) {
            Alert.alert('删除失败', e.message || '删除失败');
          }
        },
      },
    ]);
  }

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <TouchableOpacity activeOpacity={0.8} onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={colors.fg} />
        </TouchableOpacity>
        <Text style={styles.title}>记录</Text>
        <View style={styles.backBtn} />
      </View>

      <PetChipGroup pets={petChips} selectedId={selectedPet} onSelect={setSelectedPet} />

      <ScrollView contentContainerStyle={{ paddingBottom: insets.bottom + spacing['2xl'] }}>
        <View style={styles.glassCard}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardTitle}>🍽️ 饮食日志</Text>
            <Text style={styles.cardMore}>查看全部 <Ionicons name="chevron-forward" size={14} color={colors.primary} /></Text>
          </View>
          {mappedDietLogs.map((log) => (
            <View key={log.id} style={styles.recordItem}>
              <View style={[styles.recordIcon, styles.dietIcon]}>
                <Text>{log.icon}</Text>
              </View>
              <View style={styles.recordContent}>
                <Text style={styles.recordName}>{log.name}</Text>
                <Text style={styles.recordDesc}>{log.desc}</Text>
              </View>
              <Text style={styles.recordTime}>{log.time}</Text>
              <TouchableOpacity activeOpacity={0.7} onPress={() => onDeleteDietLog(log.id)} style={styles.delBtn}>
                <Text style={styles.delText}>×</Text>
              </TouchableOpacity>
            </View>
          ))}
          {!mappedDietLogs.length && <Text style={styles.emptyMini}>暂无饮食记录</Text>}
        </View>

        <View style={styles.glassCard}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardTitle}>💊 健康记录</Text>
            <Text style={styles.cardBadge}>{rawHealth.length} 条</Text>
          </View>
          {mappedHealthRecords.map((record) => (
            <View key={record.id} style={styles.recordItem}>
              <View style={[styles.recordIcon, styles.healthIcon]}>
                <Text>{record.icon}</Text>
              </View>
              <View style={styles.recordContent}>
                <Text style={styles.recordName}>{record.name}</Text>
                <Text style={styles.recordDesc}>{record.desc}</Text>
              </View>
              <Text style={styles.recordTime}>{record.date}</Text>
            </View>
          ))}
          {!mappedHealthRecords.length && <Text style={styles.emptyMini}>暂无健康记录</Text>}
        </View>

        <View style={styles.glassCard}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardTitle}>⚖️ 体重趋势</Text>
            <Text style={styles.cardMore}>详情 <Ionicons name="chevron-forward" size={14} color={colors.primary} /></Text>
          </View>
          <View style={styles.weightChart}>
            <Text style={styles.weightValue}>{latestWeight}</Text>
            <View style={styles.weightDots}>
              {weightDots.map((dot, i) => (
                <View key={i} style={[styles.weightDot, { marginBottom: dot }]} />
              ))}
            </View>
          </View>
        </View>

        <View style={styles.glassCard}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardTitle}>⚠️ 过敏信息</Text>
          </View>
          <View style={styles.allergyTags}>
            {allergyTags.map((a, idx) => (
              <Text key={idx} style={styles.allergyTag}>
                {a.text}
                {a.level ? ` · ${a.level}` : ''}
              </Text>
            ))}
            {!allergyTags.length && <Text style={[styles.allergyTag, styles.allergyTagEmpty]}>暂无过敏记录</Text>}
          </View>
        </View>

        <View style={[styles.glassCard, { marginBottom: spacing.lg }]}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardTitle}>🕒 健康事件</Text>
          </View>
          <View style={styles.timeline}>
            {timeline.map((event, idx) => (
              <View key={idx} style={styles.timelineItem}>
                <View style={styles.timelineDot} />
                <View>
                  <Text style={styles.timelineDate}>{event.date}</Text>
                  <Text style={styles.timelineText}>{event.text}</Text>
                </View>
              </View>
            ))}
            {!timeline.length && <Text style={styles.emptyMini}>暂无健康事件</Text>}
          </View>
        </View>
      </ScrollView>

      <TouchableOpacity
        activeOpacity={0.8}
        onPress={() => router.push(`/record/create${selectedPet ? '?petId=' + selectedPet : ''}`)}
        style={[styles.fab, { bottom: 24 + insets.bottom }]}
      >
        <Ionicons name="add" size={28} color="#fff" />
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.pageX,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  backBtn: {
    width: sizes.button - 6,
    height: sizes.button - 6,
    borderRadius: radius.pill,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  title: {
    fontSize: typography.sizes['3xl'],
    fontWeight: typography.weights.bold,
    color: colors.fg,
  },
  glassCard: {
    marginHorizontal: spacing.pageX,
    marginTop: spacing.md,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: radius['2xl'],
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.6)',
    ...shadows.md,
    padding: spacing.lg,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  cardTitle: {
    fontSize: typography.sizes.md,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
  },
  cardBadge: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    backgroundColor: 'rgba(0,0,0,0.04)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radius.btn,
    fontWeight: typography.weights.medium,
  },
  cardMore: {
    fontSize: typography.sizes.sm,
    color: colors.primary,
    fontWeight: typography.weights.medium,
  },
  recordItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.04)',
  },
  recordIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dietIcon: {
    backgroundColor: 'rgba(139,94,70,0.1)',
  },
  healthIcon: {
    backgroundColor: 'rgba(108,138,105,0.1)',
  },
  recordContent: {
    flex: 1,
    minWidth: 0,
  },
  recordName: {
    fontSize: typography.sizes.base,
    fontWeight: typography.weights.medium,
    color: colors.fg,
  },
  recordDesc: {
    fontSize: typography.sizes.sm,
    color: colors.muted,
    marginTop: 2,
  },
  recordTime: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginTop: 2,
  },
  delBtn: {
    padding: 4,
  },
  delText: {
    fontSize: 18,
    color: colors.muted,
  },
  emptyMini: {
    textAlign: 'center',
    paddingVertical: spacing.lg,
    fontSize: typography.sizes.base,
    color: colors.muted,
  },
  weightChart: {
    height: 120,
    borderRadius: radius.lg,
    backgroundColor: 'rgba(139,94,70,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  weightValue: {
    position: 'absolute',
    top: 8,
    right: 12,
    fontSize: 20,
    fontWeight: typography.weights.semibold,
    color: colors.primary,
  },
  weightDots: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 24,
    height: 80,
  },
  weightDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  allergyTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  allergyTag: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: radius.btn,
    backgroundColor: 'rgba(255,59,48,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,59,48,0.12)',
    fontSize: typography.sizes.sm,
    color: colors.danger,
    fontWeight: typography.weights.medium,
  },
  allergyTagEmpty: {
    color: colors.muted,
    backgroundColor: 'rgba(0,0,0,0.04)',
    borderColor: 'transparent',
  },
  timeline: {
    position: 'relative',
    paddingLeft: 20,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 16,
    paddingBottom: 16,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.card,
    marginLeft: -21,
    marginTop: 4,
  },
  timelineDate: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginBottom: 4,
    fontWeight: typography.weights.medium,
  },
  timelineText: {
    fontSize: typography.sizes.base,
    color: colors.fg,
    lineHeight: 20,
  },
  fab: {
    position: 'absolute',
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.btn,
    zIndex: 50,
  },
});

// ios-app-frontend/src/views/Records.vue
<template>
  <div class="records-shell">
    <header class="records-header anim-fade-up">
      <div class="records-header-row">
        <button class="back-btn" @click="$router.back()" aria-label="返回">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>
        </button>
      </div>
      <h1 class="records-title">记录</h1>
    </header>

    <div class="pet-selector anim-fade-up anim-delay-1">
      <div v-for="pet in pets" :key="pet.id" class="pet-chip" :class="{ active: selectedPet === pet.id }" @click="selectedPet = pet.id">
        <div class="pet-chip-avatar">{{ pet.emoji }}</div>
        <span class="pet-chip-name">{{ pet.name }}</span>
      </div>
    </div>

    <!-- Diet Logs -->
    <div class="glass-card anim-fade-up anim-delay-2">
      <div class="glass-card-header">
        <div class="glass-card-title">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/><line x1="6" y1="1" x2="6" y2="4"/><line x1="10" y1="1" x2="10" y2="4"/><line x1="14" y1="1" x2="14" y2="4"/></svg>
          饮食日志
        </div>
        <span class="glass-card-more">查看全部 <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg></span>
      </div>
      <div v-for="log in dietLogs" :key="log.id" class="record-item">
        <div class="record-icon diet">{{ log.icon }}</div>
        <div class="record-content">
          <div class="record-name">{{ log.name }}</div>
          <div class="record-desc">{{ log.desc }}</div>
        </div>
        <span class="record-time">{{ log.time }}</span>
        <button class="record-del" @click.stop="onDeleteDietLog(log.id)">×</button>
      </div>
    </div>

    <!-- Health Records -->
    <div class="glass-card anim-fade-up anim-delay-3">
      <div class="glass-card-header">
        <div class="glass-card-title">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>
          健康记录
        </div>
        <span class="glass-card-badge">{{ rawHealth.length }} 条</span>
      </div>
      <div v-for="record in healthRecords" :key="record.id" class="record-item">
        <div class="record-icon" :class="record.type">{{ record.icon }}</div>
        <div class="record-content">
          <div class="record-name">{{ record.name }}</div>
          <div class="record-desc">{{ record.desc }}</div>
        </div>
        <span class="record-time">{{ record.date }}</span>
      </div>
    </div>

    <!-- Weight Tracker -->
    <div class="glass-card anim-fade-up anim-delay-4">
      <div class="glass-card-header">
        <div class="glass-card-title">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a4 4 0 0 0-4 4c0 2 2 4 4 6 2-2 4-4 4-6a4 4 0 0 0-4-4z"/><path d="M20 21H4"/></svg>
          体重趋势
        </div>
        <span class="glass-card-more">详情 <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg></span>
      </div>
      <div class="weight-chart">
        <span class="weight-value">{{ latestWeight }}</span>
        <div class="weight-chart-dots">
          <div class="weight-dot" v-for="(dot, i) in weightDots" :key="i" :style="{ marginBottom: dot + 'px' }"></div>
        </div>
      </div>
    </div>

    <!-- Allergy Info -->
    <div class="glass-card anim-fade-up anim-delay-4">
      <div class="glass-card-header">
        <div class="glass-card-title">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
          过敏信息
        </div>
      </div>
      <div class="allergy-tags">
        <span v-for="a in allergyTags" :key="a.text" class="allergy-tag">{{ a.text }}<template v-if="a.level"> · {{ a.level }}</template></span>
        <span v-if="!allergyTags.length" class="allergy-tag" style="color:var(--muted);background:rgba(0,0,0,.04);border-color:transparent">暂无过敏记录</span>
      </div>
    </div>

    <!-- Health Timeline -->
    <div class="glass-card anim-fade-up anim-delay-5" style="margin-bottom:24px">
      <div class="glass-card-header">
        <div class="glass-card-title">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
          健康事件
        </div>
      </div>
      <div class="timeline">
        <div v-for="event in timeline" :key="event.date" class="timeline-item">
          <div class="timeline-dot"></div>
          <div class="timeline-date">{{ event.date }}</div>
          <div class="timeline-text">{{ event.text }}</div>
        </div>
      </div>
    </div>
  </div>

  <button class="fab anim-scale-in anim-delay-5" aria-label="添加记录" @click="$router.push('/record/create' + (selectedPet ? '?petId=' + selectedPet : ''))">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
  </button>

  <TabBar active-tab="records" />
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { Toast } from 'tdesign-mobile-vue'
import TabBar from '../components/TabBar.vue'
import { usePets } from '../composables/usePets'
import { useDietLogs } from '../composables/useDietLogs'
import { useHealthRecords } from '../composables/useHealthRecords'

const { pets: rawPets, fetchPets } = usePets()
const { dietLogs: rawDietLogs, fetchDietLogs, deleteDietLog } = useDietLogs()
const { healthRecords: rawHealth, weightRecords, allergies, timeline, fetchHealthRecords, fetchAllergies } = useHealthRecords()

const selectedPet = ref(null)

const SPECIES_EMOJI = { cat: '🐱', dog: '🐶' }
const FOOD_ICON = { dry_food: '🍖', wet_food: '🐟', water: '💧', treat: '🦴', default: '🍽️' }
const RECORD_ICON = { vaccination: '💉', symptom: '🩺', medication: '💊', diagnosis: '📋', checkup: '🩻', weight: '⚖️' }
const SEVERITY_LABEL = { mild: '轻度', moderate: '中度', severe: '重度' }

// 宠物列表（加 emoji）
const pets = computed(() => rawPets.value.map(p => ({
  id: p.id,
  name: p.name,
  emoji: SPECIES_EMOJI[p.species] || '🐾'
})))

// 饮食日志映射
const dietLogs = computed(() => rawDietLogs.value.map(l => ({
  id: l.id,
  icon: FOOD_ICON[l.food_type] || FOOD_ICON.default,
  name: l.food_name,
  desc: l.notes || l.food_type,
  time: (l.created_at || l.logged_date || '').slice(11, 16) || '—'
})))

// 健康记录映射（排除体重）
const healthRecords = computed(() => rawHealth.value.map(r => ({
  id: r.id,
  icon: RECORD_ICON[r.record_type] || '📋',
  type: r.record_type,
  name: r.diagnosis || r.medication_name || r.record_type,
  desc: r.notes || '',
  date: (r.record_time || '').slice(5, 10)
})))

// 体重
const latestWeight = computed(() => {
  const w = weightRecords.value[0]?.weight_kg
  return w ? `${Number(w).toFixed(1)} kg` : '-- kg'
})

// 过敏标签
const allergyTags = computed(() => allergies.value.map(a => ({
  text: a.allergen,
  level: SEVERITY_LABEL[a.severity] || ''
})))

// 体重趋势点（根据记录数生成高度）
const weightDots = computed(() => {
  const recs = weightRecords.value.slice(0, 7).reverse()
  if (!recs.length) return []
  const weights = recs.map(r => Number(r.weight_kg))
  const min = Math.min(...weights), max = Math.max(...weights)
  return weights.map(w => 10 + ((w - min) / (max - min || 1)) * 18)
})

async function loadAll(petId) {
  await Promise.all([
    fetchHealthRecords(petId),
    fetchDietLogs(petId)
  ])
  if (petId) fetchAllergies(petId)
}

onMounted(async () => {
  await fetchPets()
  if (pets.value.length) {
    selectedPet.value = pets.value[0].id
  }
})

watch(selectedPet, (id) => {
  if (id) loadAll(id)
})

async function onDeleteDietLog(id) {
  if (!confirm('确定要删除这条饮食记录吗？')) return
  try {
    await deleteDietLog(id)
    Toast({ theme: 'success', message: '已删除' })
  } catch (e) {
    Toast({ theme: 'error', message: e.message || '删除失败' })
  }
}
</script>

<style scoped>
.records-shell{width:100%;min-height:100vh;min-height:100dvh;padding-top:var(--safe-top);padding-bottom:calc(100px + var(--safe-bottom));overflow-y:auto;overflow-x:hidden;-webkit-overflow-scrolling:touch;position:relative}
.records-header{position:relative;padding:20px 24px 0;z-index:1}
.records-header-row{display:flex;align-items:center;justify-content:space-between}
.back-btn{width:40px;height:40px;border-radius:50%;background:var(--card);box-shadow:var(--shadow-card);display:flex;align-items:center;justify-content:center;border:1px solid var(--border);cursor:pointer;transition:transform .2s}
.back-btn:active{transform:scale(.92)}
.back-btn svg{width:20px;height:20px;color:var(--fg)}
.records-title{margin-top:20px;font-family:var(--font-display);font-size:34px;font-weight:700;line-height:1.15;letter-spacing:-.02em}
.pet-selector{display:flex;gap:8px;padding:20px 24px 0;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none;z-index:1}
.pet-selector::-webkit-scrollbar{display:none}
.pet-chip{flex-shrink:0;display:flex;align-items:center;gap:6px;padding:6px 12px;border-radius:var(--radius-btn);background:var(--card);border:1.5px solid var(--border);box-shadow:0 2px 8px rgba(0,0,0,.03);cursor:pointer;transition:all .2s}
.pet-chip.active{border-color:var(--brown);background:rgba(139,94,70,.06)}
.pet-chip:active{transform:scale(.96)}
.pet-chip-avatar{width:22px;height:22px;border-radius:6px;background:linear-gradient(135deg,rgba(215,181,147,.2),rgba(215,181,147,.08));display:flex;align-items:center;justify-content:center;font-size:12px}
.pet-chip-name{font-size:12px;font-weight:500;color:var(--fg);white-space:nowrap}
.glass-card{margin:16px 20px 0;background:rgba(255,255,255,.72);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border-radius:24px;border:1px solid rgba(255,255,255,.6);box-shadow:0 8px 32px rgba(0,0,0,.06),inset 0 1px 0 rgba(255,255,255,.8);padding:20px;position:relative;z-index:1}
.glass-card-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}
.glass-card-title{display:flex;align-items:center;gap:8px;font-size:16px;font-weight:600;color:var(--fg)}
.glass-card-title svg{width:18px;height:18px;color:var(--brown)}
.glass-card-badge{font-size:12px;color:var(--muted);background:rgba(0,0,0,.04);padding:4px 10px;border-radius:var(--radius-btn);font-weight:500}
.glass-card-more{font-size:13px;color:var(--brown);font-weight:500;cursor:pointer;display:flex;align-items:center;gap:2px}
.glass-card-more:active{opacity:.6}
.glass-card-more svg{width:14px;height:14px}
.record-item{display:flex;align-items:flex-start;gap:12px;padding:12px 0;border-bottom:1px solid rgba(0,0,0,.04)}
.record-item:last-child{border-bottom:none;padding-bottom:0}
.record-item:first-child{padding-top:0}
.record-icon{width:40px;height:40px;border-radius:12px;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:18px}
.record-icon.diet{background:rgba(139,94,70,.1)}
.record-icon.health{background:rgba(108,138,105,.1)}
.record-icon.symptom{background:rgba(255,59,48,.1)}
.record-content{flex:1;min-width:0}
.record-name{font-size:14px;font-weight:500;color:var(--fg);margin-bottom:2px}
.record-desc{font-size:12px;color:var(--muted);line-height:1.4}
.record-time{font-size:11px;color:var(--muted);white-space:nowrap;flex-shrink:0;margin-top:2px}
.record-del{background:none;border:none;color:var(--muted);font-size:18px;cursor:pointer;padding:4px;flex-shrink:0;opacity:.5}
.record-del:active{opacity:1;color:#FF3B30}
.weight-chart{height:120px;border-radius:16px;background:linear-gradient(135deg,rgba(139,94,70,.04),rgba(215,181,147,.08));display:flex;align-items:center;justify-content:center;position:relative;overflow:hidden}
.weight-value{position:absolute;top:8px;right:12px;font-size:20px;font-weight:600;color:var(--brown);font-family:var(--font-num)}
.weight-chart-dots{display:flex;align-items:flex-end;gap:24px;height:80px;position:relative;z-index:1}
.weight-dot{width:8px;height:8px;border-radius:50%;background:var(--brown);box-shadow:0 2px 8px rgba(139,94,70,.3)}
.allergy-tags{display:flex;flex-wrap:wrap;gap:8px}
.allergy-tag{padding:6px 14px;border-radius:var(--radius-btn);background:rgba(255,59,48,.06);border:1px solid rgba(255,59,48,.12);font-size:13px;color:#FF3B30;font-weight:500}
.timeline{position:relative;padding-left:20px}
.timeline::before{content:'';position:absolute;left:6px;top:8px;bottom:8px;width:2px;background:rgba(0,0,0,.06);border-radius:1px}
.timeline-item{position:relative;padding:0 0 16px 16px}
.timeline-item:last-child{padding-bottom:0}
.timeline-dot{position:absolute;left:-17px;top:6px;width:10px;height:10px;border-radius:50%;border:2px solid var(--brown);background:var(--card)}
.timeline-date{font-size:11px;color:var(--muted);margin-bottom:4px;font-weight:500}
.timeline-text{font-size:13px;color:var(--fg);line-height:1.5}
.fab{position:fixed;bottom:calc(100px + var(--safe-bottom));right:24px;width:56px;height:56px;border-radius:50%;background:var(--brown);box-shadow:var(--shadow-btn);display:flex;align-items:center;justify-content:center;cursor:pointer;z-index:50;transition:transform .15s}
.fab:active{transform:scale(.9)}
.fab svg{width:24px;height:24px;color:#fff}
@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
@keyframes scaleIn{from{opacity:0;transform:scale(.9)}to{opacity:1;transform:scale(1)}}
.anim-fade-up{opacity:0;animation:fadeUp .6s cubic-bezier(.22,1,.36,1) forwards}
.anim-delay-1{animation-delay:.1s}
.anim-delay-2{animation-delay:.2s}
.anim-delay-3{animation-delay:.3s}
.anim-delay-4{animation-delay:.4s}
.anim-delay-5{animation-delay:.5s}
.anim-scale-in{opacity:0;animation:scaleIn .5s cubic-bezier(.22,1,.36,1) forwards}
</style>
