// nuzzly-expo/app/trace-log.tsx
import { useEffect } from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';
import PageHeader from '../src/components/PageHeader';
import EmptyState from '../src/components/EmptyState';
import { useRecommendationTrace, TraceLog } from '../src/hooks/useRecommendationTrace';

function formatDate(dateStr?: string) {
  if (!dateStr) return '--';
  return new Date(dateStr).toLocaleDateString('zh-CN');
}

export default function TraceLogScreen() {
  const insets = useSafeAreaInsets();
  const { pet } = useLocalSearchParams<{ pet?: string }>();
  const { traceLogs, loading, fetchTraceLogs, getDataSourceLabel } = useRecommendationTrace();

  useEffect(() => {
    if (pet) fetchTraceLogs(pet);
  }, [pet]);

  const renderTrace = (log: TraceLog) => {
    const sources = log.data_sources || [];
    return (
      <View key={log.id} style={styles.traceCard}>
        <View style={styles.traceHeader}>
          <Text style={styles.traceDate}>{formatDate(log.created_at)}</Text>
          <View style={styles.modelBadge}>
            <Text style={styles.modelText}>{log.model_version || '-'}</Text>
          </View>
        </View>
        <View style={styles.traceSources}>
          {sources.map((src) => (
            <View key={src} style={styles.sourceTag}>
              <Text style={styles.sourceText}>{getDataSourceLabel(src)}</Text>
            </View>
          ))}
        </View>
      </View>
    );
  };

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="推荐追踪" />
      <ScrollView
        style={styles.container}
        contentContainerStyle={{ paddingBottom: insets.bottom + spacing.xl }}
        showsVerticalScrollIndicator={false}
      >
        {!loading && traceLogs.length === 0 ? (
          <EmptyState icon="📋" title="暂无追踪记录" />
        ) : (
          <View style={styles.traceList}>{traceLogs.map(renderTrace)}</View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.pageX,
  },
  traceList: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  traceCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  traceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  traceDate: {
    fontSize: typography.sizes.md,
    color: colors.fg,
  },
  modelBadge: {
    backgroundColor: colors.bg,
    paddingVertical: 2,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.sm,
  },
  modelText: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
  },
  traceSources: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  sourceTag: {
    backgroundColor: 'rgba(25,118,210,0.08)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
  },
  sourceText: {
    fontSize: typography.sizes.xs,
    color: colors.info,
  },
});

// ios-app-frontend/src/views/TraceLog.vue
<template>
  <div class="app-shell">
    <PageHeader title="推荐追踪" />

    <!-- 空状态 -->
    <div v-if="!loading && traceLogs.length === 0" class="empty-state">
      <div class="empty-icon">📋</div>
      <p class="empty-text">暂无追踪记录</p>
    </div>

    <!-- 追踪列表 -->
    <div v-else class="trace-list">
      <div v-for="log in traceLogs" :key="log.id" class="trace-card">
        <div class="trace-header">
          <span class="trace-date">{{ formatDate(log.created_at) }}</span>
          <span class="trace-model">{{ log.model_version }}</span>
        </div>
        <div class="trace-sources">
          <span v-for="src in log.data_sources" :key="src" class="source-tag">{{ src }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useRecommendationTrace } from '../composables/useRecommendationTrace'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const petId = ref(route.query.pet || '')

const { traceLogs, loading, fetchTraceLogs } = useRecommendationTrace()

onMounted(() => {
  if (petId.value) fetchTraceLogs(petId.value)
})

function formatDate(dateStr) {
  const d = new Date(dateStr)
  return d.toLocaleDateString('zh-CN')
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; }
.trace-list { padding: 16px 0; }
.trace-card { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
.trace-header { display: flex; justify-content: space-between; margin-bottom: 8px; }
.trace-date { font-size: 14px; color: #333; }
.trace-model { font-size: 12px; color: #999; background: #f5f5f5; padding: 2px 8px; border-radius: 8px; }
.trace-sources { display: flex; flex-wrap: wrap; gap: 8px; }
.source-tag { font-size: 11px; padding: 4px 10px; border-radius: 10px; background: #e3f2fd; color: #1976d2; }
</style>
