// ios-app-frontend/src/views/AIInsights.vue
<template>
  <div class="app-shell">
    <PageHeader title="AI洞察" />

    <!-- 加载态 -->
    <div v-if="loading" class="skeleton-list">
      <div class="insight-skeleton skeleton" v-for="i in 3" :key="i">
        <div class="shimmer-line w60"></div>
        <div class="shimmer-line w80"></div>
      </div>
    </div>

    <!-- 空状态 -->
    <div v-else-if="insights.length === 0" class="empty-state">
      <div class="empty-icon">💡</div>
      <p class="empty-text">暂无AI洞察</p>
      <p class="empty-hint">系统会根据您的数据生成个性化洞察</p>
    </div>

    <!-- 洞察列表 -->
    <div v-else class="insight-list">
      <div v-for="insight in insights" :key="insight.id" class="insight-card">
        <div class="insight-header">
          <span class="insight-icon">{{ getInsightTypeIcon(insight.insight_type) }}</span>
          <span class="insight-type" :style="{ color: getInsightTypeColor(insight.insight_type) }">
            {{ getInsightTypeLabel(insight.insight_type) }}
          </span>
          <span class="insight-date">{{ formatDate(insight.created_at) }}</span>
        </div>
        <div class="insight-title">{{ insight.title || '洞察' }}</div>
        <div class="insight-summary">{{ insight.summary }}</div>
        <div v-if="insight.confidence_score" class="insight-confidence">
          置信度: {{ (insight.confidence_score * 100).toFixed(0) }}%
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useAIInsights } from '../composables/useAIInsights'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const productId = ref(route.query.product || '')

const { insights, loading, fetchInsights, getInsightTypeLabel, getInsightTypeIcon, getInsightTypeColor } = useAIInsights()

onMounted(() => {
  fetchInsights(productId.value || undefined)
})

function formatDate(dateStr) {
  const d = new Date(dateStr)
  return `${d.getMonth() + 1}/${d.getDate()}`
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; margin-bottom: 8px; }
.empty-hint { font-size: 13px; color: #999; }
.insight-list { padding: 16px 0; }
.insight-card { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
.insight-header { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
.insight-icon { font-size: 20px; }
.insight-type { font-size: 13px; font-weight: 500; }
.insight-date { margin-left: auto; font-size: 12px; color: #999; }
.insight-title { font-size: 16px; font-weight: 600; color: #333; margin-bottom: 8px; }
.insight-summary { font-size: 14px; color: #666; line-height: 1.6; }
.insight-confidence { margin-top: 8px; font-size: 12px; color: #999; }
</style>

// nuzzly-expo/app/ai-insights.tsx
import { useEffect } from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import PageHeader from '../src/components/PageHeader';
import {
  useAIInsights,
  getInsightTypeLabel,
  getInsightTypeIcon,
  getInsightTypeColor,
} from '../src/hooks/useAIInsights';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';

export default function AIInsightsScreen() {
  const { product } = useLocalSearchParams<{ product?: string }>();
  const insets = useSafeAreaInsets();
  const { insights, loading, fetchInsights } = useAIInsights();

  useEffect(() => {
    fetchInsights(product || undefined);
  }, [product]);

  const formatDate = (dateStr: string) => {
    const d = new Date(dateStr);
    return `${d.getMonth() + 1}/${d.getDate()}`;
  };

  return (
    <View style={[styles.container, { paddingBottom: insets.bottom + spacing.md }]}>
      <PageHeader title="AI洞察" />
      <ScrollView contentContainerStyle={styles.body}>
        {loading ? (
          <View style={styles.skeletonList}>
            {[1, 2, 3].map((i) => (
              <View key={i} style={styles.skeletonCard}>
                <View style={[styles.shimmerLine, { width: '60%' }]} />
                <View style={[styles.shimmerLine, { width: '80%' }]} />
              </View>
            ))}
          </View>
        ) : insights.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyIcon}>💡</Text>
            <Text style={styles.emptyText}>暂无AI洞察</Text>
            <Text style={styles.emptyHint}>系统会根据您的数据生成个性化洞察</Text>
          </View>
        ) : (
          <View style={styles.list}>
            {insights.map((insight) => {
              const typeColor = getInsightTypeColor(insight.insight_type);
              return (
                <View key={insight.id} style={styles.insightCard}>
                  <View style={styles.insightHeader}>
                    <Text style={styles.insightIcon}>
                      {getInsightTypeIcon(insight.insight_type)}
                    </Text>
                    <Text style={[styles.insightType, { color: typeColor }]}>
                      {getInsightTypeLabel(insight.insight_type)}
                    </Text>
                    <Text style={styles.insightDate}>{formatDate(insight.created_at)}</Text>
                  </View>
                  <Text style={styles.insightTitle}>{insight.title || '洞察'}</Text>
                  <Text style={styles.insightSummary}>{insight.summary}</Text>
                  {insight.confidence_score ? (
                    <Text style={styles.insightConfidence}>
                      置信度: {(insight.confidence_score * 100).toFixed(0)}%
                    </Text>
                  ) : null}
                </View>
              );
            })}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  body: {
    paddingHorizontal: spacing.pageX,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
  },
  skeletonList: {
    paddingTop: spacing.md,
  },
  skeletonCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  shimmerLine: {
    height: 12,
    borderRadius: radius.xs,
    backgroundColor: 'rgba(0,0,0,0.06)',
    marginBottom: spacing.sm,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: spacing.lg,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  emptyText: {
    fontSize: 16,
    color: colors.fg,
    marginBottom: spacing.sm,
  },
  emptyHint: {
    fontSize: 13,
    color: colors.muted,
  },
  list: {
    paddingVertical: spacing.md,
  },
  insightCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  insightIcon: {
    fontSize: 20,
  },
  insightType: {
    fontSize: 13,
    fontWeight: '500',
  },
  insightDate: {
    marginLeft: 'auto',
    fontSize: 12,
    color: colors.muted,
  },
  insightTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.fg,
    marginBottom: spacing.sm,
  },
  insightSummary: {
    fontSize: 14,
    color: colors.muted,
    lineHeight: 22,
  },
  insightConfidence: {
    marginTop: spacing.sm,
    fontSize: 12,
    color: colors.muted,
  },
});
