// ios-app-frontend/src/views/HealthReminders.vue
<template>
  <div class="app-shell">
    <!-- 顶栏 (与社区页一致) -->
    <header class="header anim-fade-up">
      <div class="header-row">
        <img class="brand-logo" src="/nuzzly-zuhe.png" alt="Nuzzly 毛球镇" />
        <div class="header-actions">
          <button class="action-circle" aria-label="通知" @click="$router.push('/notifications')">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18.134 11C18.715 16.375 21 18 21 18H3s3-2.133 3-9.6c0-1.697.632-3.325 1.757-4.525S10.41 2 12 2q.507 0 1 .09M19 8a3 3 0 1 0 0-6a3 3 0 0 0 0 6m-5.27 13a2 2 0 0 1-3.46 0"/></svg>
          </button>
        </div>
      </div>
    </header>

    <!-- 宠物选择 -->
    <div class="pet-selector anim-fade-up anim-delay-1">
      <div v-for="pet in pets" :key="pet.id" class="pet-chip" :class="{ active: selectedPet === pet.id }" @click="selectedPet = pet.id">
        <div class="pet-chip-avatar">{{ pet.emoji }}</div>
        <span class="pet-chip-name">{{ pet.name }}</span>
      </div>
    </div>

    <!-- 类型筛选 -->
    <div class="type-filter anim-fade-up anim-delay-1">
      <div v-for="t in TYPE_FILTERS" :key="t.value" class="type-chip" :class="{ active: typeFilter === t.value }" @click="typeFilter = t.value">
        {{ t.label }}
      </div>
    </div>

    <!-- 提醒列表 -->
    <div class="reminders-list anim-fade-up anim-delay-2">
      <div v-if="loading" class="empty-state">加载中…</div>
      <div v-else-if="!filteredReminders.length" class="empty-state">
        <div class="empty-icon">🔔</div>
        <div class="empty-text">暂无健康提醒</div>
        <div class="empty-desc">点击右下角 + 添加提醒</div>
      </div>
      <template v-else>
        <div v-for="r in filteredReminders" :key="r.id" class="reminder-card" :class="{ overdue: isOverdue(r), completed: r.is_completed }">
          <div class="reminder-icon" :class="r.reminder_type">
            {{ TYPE_ICON[r.reminder_type] || '📌' }}
          </div>
          <div class="reminder-body">
            <div class="reminder-title">{{ r.title }}</div>
            <div class="reminder-meta">
              <span class="reminder-type-tag">{{ TYPE_LABEL[r.reminder_type] }}</span>
              <span v-if="r.repeat_interval && r.repeat_interval !== 'none'" class="reminder-repeat">🔁 {{ REPEAT_LABEL[r.repeat_interval] }}</span>
            </div>
            <div v-if="r.description" class="reminder-desc">{{ r.description }}</div>
            <div class="reminder-date" :class="{ overdue: isOverdue(r) && !r.is_completed }">
              {{ isOverdue(r) && !r.is_completed ? '已过期 · ' : '' }}{{ formatDate(r.due_date) }}
            </div>
          </div>
          <div class="reminder-actions">
            <button v-if="!r.is_completed" class="action-btn done" @click="handleComplete(r)" aria-label="完成">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M20 6L9 17l-5-5"/></svg>
            </button>
            <button class="action-btn del" @click="handleDelete(r)" aria-label="删除">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="M18 6L6 18M6 6l12 12"/></svg>
            </button>
          </div>
        </div>
      </template>
    </div>

    <!-- 浮动按钮 -->
    <button class="fab anim-scale-in anim-delay-3" @click="$router.push({ path: '/health-reminders/create', query: { petId: selectedPet } })" aria-label="新建提醒">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>
    </button>

    <TabBar active-tab="home" />
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import TabBar from '../components/TabBar.vue'
import { usePets } from '../composables/usePets'
import { useHealthReminders } from '../composables/useHealthReminders'

const { pets, fetchPets } = usePets()
const { reminders, loading, fetchReminders, completeReminder, deleteReminder } = useHealthReminders()

const selectedPet = ref('')
const typeFilter = ref('all')

const TYPE_FILTERS = [
  { value: 'all', label: '全部' },
  { value: 'vaccination', label: '疫苗' },
  { value: 'medication', label: '用药' },
  { value: 'checkup', label: '体检' },
  { value: 'custom', label: '自定义' },
]

const TYPE_ICON = { vaccination: '💉', medication: '💊', checkup: '🩺', custom: '📌' }
const TYPE_LABEL = { vaccination: '疫苗', medication: '用药', checkup: '体检', custom: '自定义' }
const REPEAT_LABEL = { monthly: '每月', quarterly: '每季', yearly: '每年' }

const filteredReminders = computed(() => {
  let list = reminders.value.filter(r => r.pet_id === selectedPet.value)
  if (typeFilter.value !== 'all') {
    list = list.filter(r => r.reminder_type === typeFilter.value)
  }
  return list
})

function isOverdue(r) {
  if (r.is_completed) return false
  return r.due_date < new Date().toISOString().slice(0, 10)
}

function formatDate(d) {
  if (!d) return ''
  const date = new Date(d + 'T00:00:00')
  const now = new Date()
  const diff = Math.ceil((date - now) / (1000 * 60 * 60 * 24))
  if (diff === 0) return '今天'
  if (diff === 1) return '明天'
  if (diff === -1) return '昨天'
  if (diff > 0 && diff <= 7) return `${diff} 天后`
  return `${date.getMonth() + 1}月${date.getDate()}日`
}

async function handleComplete(r) {
  try {
    await completeReminder(r.id)
  } catch (e) {
    console.warn('完成失败:', e.message)
  }
}

async function handleDelete(r) {
  try {
    await deleteReminder(r.id)
  } catch (e) {
    console.warn('删除失败:', e.message)
  }
}

onMounted(async () => {
  await fetchPets()
  if (pets.value.length) {
    selectedPet.value = pets.value[0].id
    await fetchReminders(pets.value[0].id)
  }
})
</script>

<style scoped>
.app-shell{width:100%;min-height:100vh;min-height:100dvh;padding-top:var(--safe-top);padding-bottom:calc(88px + var(--safe-bottom));overflow-y:auto;overflow-x:hidden;-webkit-overflow-scrolling:touch}
.header{position:relative;padding:4px 24px 0;z-index:1}
.header-row{display:flex;align-items:center;justify-content:space-between}
.brand-logo{height:32px;width:auto;display:block;flex-shrink:0;object-fit:contain}
.header-actions{display:flex;gap:10px}
.action-circle{width:41.31px;height:41.31px;border-radius:50%;background:var(--card);box-shadow:var(--shadow-card);display:flex;align-items:center;justify-content:center;border:1px solid var(--border);cursor:pointer;transition:transform .2s,box-shadow .2s;position:relative}
.action-circle:active{transform:scale(.92)}
.action-circle svg{width:18px;height:18px;color:var(--fg)}
.pet-selector{display:flex;gap:8px;padding:16px 24px 0;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none;z-index:1}
.pet-selector::-webkit-scrollbar{display:none}
.pet-chip{flex-shrink:0;display:flex;align-items:center;gap:6px;padding:6px 12px;border-radius:var(--radius-btn);background:var(--card);border:1.5px solid var(--border);box-shadow:0 2px 8px rgba(0,0,0,.03);cursor:pointer;transition:all .2s}
.pet-chip.active{border-color:var(--brown);background:rgba(139,94,70,.06)}
.pet-chip:active{transform:scale(.96)}
.pet-chip-avatar{width:22px;height:22px;border-radius:6px;background:linear-gradient(135deg,rgba(215,181,147,.2),rgba(215,181,147,.08));display:flex;align-items:center;justify-content:center;font-size:12px}
.pet-chip-name{font-size:12px;font-weight:500;color:var(--fg);white-space:nowrap}
.type-filter{display:flex;gap:6px;padding:12px 24px 0;overflow-x:auto;scrollbar-width:none;z-index:1}
.type-filter::-webkit-scrollbar{display:none}
.type-chip{flex-shrink:0;padding:6px 14px;border-radius:var(--radius-btn);background:var(--card);border:1px solid var(--border);font-size:12px;font-weight:500;color:var(--muted);cursor:pointer;transition:all .2s}
.type-chip.active{background:var(--brown);color:#fff;border-color:var(--brown)}
.type-chip:active{transform:scale(.96)}
.reminders-list{padding:16px 20px 0;position:relative;z-index:1}
.empty-state{text-align:center;padding:48px 24px;color:var(--muted)}
.empty-icon{font-size:40px;margin-bottom:12px}
.empty-text{font-size:16px;font-weight:600;color:var(--fg);margin-bottom:4px}
.empty-desc{font-size:13px}
.reminder-card{display:flex;align-items:flex-start;gap:12px;padding:16px;background:var(--card);border-radius:16px;border:1px solid var(--border);box-shadow:var(--shadow-card);margin-bottom:10px;transition:opacity .2s}
.reminder-card.completed{opacity:.5}
.reminder-icon{width:44px;height:44px;border-radius:14px;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:20px}
.reminder-icon.vaccination{background:rgba(108,138,105,.1)}
.reminder-icon.medication{background:rgba(59,130,246,.1)}
.reminder-icon.checkup{background:rgba(215,181,147,.15)}
.reminder-icon.custom{background:rgba(0,0,0,.04)}
.reminder-body{flex:1;min-width:0}
.reminder-title{font-size:15px;font-weight:600;color:var(--fg);margin-bottom:4px}
.reminder-meta{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:4px}
.reminder-type-tag{font-size:10px;padding:2px 8px;border-radius:var(--radius-btn);background:rgba(0,0,0,.04);color:var(--muted);font-weight:500}
.reminder-repeat{font-size:10px;padding:2px 8px;border-radius:var(--radius-btn);background:rgba(139,94,70,.08);color:var(--brown);font-weight:500}
.reminder-desc{font-size:12px;color:var(--muted);margin-bottom:4px;line-height:1.4}
.reminder-date{font-size:12px;color:var(--muted);font-weight:500}
.reminder-date.overdue{color:#FF3B30}
.reminder-actions{display:flex;flex-direction:column;gap:6px;flex-shrink:0}
.action-btn{width:32px;height:32px;border-radius:10px;border:none;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:transform .15s}
.action-btn:active{transform:scale(.85)}
.action-btn.done{background:rgba(108,138,105,.1)}
.action-btn.done svg{width:16px;height:16px;color:var(--green)}
.action-btn.del{background:rgba(255,59,48,.06)}
.action-btn.del svg{width:14px;height:14px;color:var(--muted)}
.fab{position:fixed;bottom:calc(100px + var(--safe-bottom));right:clamp(16px,4vw,24px);width:52px;height:52px;border-radius:50%;background:var(--brown);box-shadow:var(--shadow-btn);display:flex;align-items:center;justify-content:center;cursor:pointer;z-index:50;transition:transform .15s}
.fab:active{transform:scale(.9)}
.fab svg{width:24px;height:24px;color:#fff}
@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
@keyframes scaleIn{from{opacity:0;transform:scale(.9)}to{opacity:1;transform:scale(1)}}
.anim-fade-up{opacity:0;animation:fadeUp .6s cubic-bezier(.22,1,.36,1) forwards}
.anim-delay-1{animation-delay:.1s}.anim-delay-2{animation-delay:.2s}.anim-delay-3{animation-delay:.3s}
.anim-scale-in{opacity:0;animation:scaleIn .5s cubic-bezier(.22,1,.36,1) forwards}
</style>

// nuzzly-expo/app/health-reminders.tsx
import { useEffect, useMemo, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Image,
  Alert,
  StyleSheet,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { usePets } from '../src/hooks/usePets';
import { useHealthReminders, HealthReminder } from '../src/hooks/useHealthReminders';
import PetChipGroup from '../src/components/PetChipGroup';
import { colors, spacing, radius, shadows, sizes, typography } from '../src/theme/tokens';

const TYPE_FILTERS = [
  { value: 'all', label: '全部' },
  { value: 'vaccination', label: '疫苗' },
  { value: 'medication', label: '用药' },
  { value: 'checkup', label: '体检' },
  { value: 'custom', label: '自定义' },
];

const TYPE_ICON: Record<string, string> = {
  vaccination: '💉',
  medication: '💊',
  checkup: '🩺',
  custom: '📌',
};

const TYPE_LABEL: Record<string, string> = {
  vaccination: '疫苗',
  medication: '用药',
  checkup: '体检',
  custom: '自定义',
};

const REPEAT_LABEL: Record<string, string> = {
  monthly: '每月',
  quarterly: '每季',
  yearly: '每年',
};

const TYPE_BG: Record<string, string> = {
  vaccination: 'rgba(108,138,105,0.1)',
  medication: 'rgba(59,130,246,0.1)',
  checkup: 'rgba(215,181,147,0.15)',
  custom: 'rgba(0,0,0,0.04)',
};

const SPECIES_EMOJI: Record<string, string> = { cat: '🐱', dog: '🐶' };

export default function HealthRemindersScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { pets, fetchPets } = usePets();
  const { reminders, loading, fetchReminders, completeReminder, deleteReminder } =
    useHealthReminders();

  const [selectedPet, setSelectedPet] = useState('');
  const [typeFilter, setTypeFilter] = useState('all');

  const petChips = useMemo(
    () => pets.map((p) => ({ id: p.id, name: p.name, emoji: SPECIES_EMOJI[p.species] || '🐾' })),
    [pets]
  );

  const filteredReminders = useMemo(() => {
    let list = reminders.filter((r) => r.pet_id === selectedPet);
    if (typeFilter !== 'all') {
      list = list.filter((r) => r.reminder_type === typeFilter);
    }
    return list;
  }, [reminders, selectedPet, typeFilter]);

  useEffect(() => {
    fetchPets().then(() => {
      if (pets.length && !selectedPet) {
        setSelectedPet(pets[0].id);
      }
    });
  }, []);

  useEffect(() => {
    if (selectedPet) fetchReminders(selectedPet);
  }, [selectedPet]);

  function isOverdue(r: HealthReminder) {
    if (r.is_completed) return false;
    return r.due_date < new Date().toISOString().slice(0, 10);
  }

  function formatDate(d: string) {
    if (!d) return '';
    const date = new Date(d + 'T00:00:00');
    const now = new Date();
    const diff = Math.ceil((date.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    if (diff === 0) return '今天';
    if (diff === 1) return '明天';
    if (diff === -1) return '昨天';
    if (diff > 0 && diff <= 7) return `${diff} 天后`;
    return `${date.getMonth() + 1}月${date.getDate()}日`;
  }

  async function handleComplete(r: HealthReminder) {
    try {
      await completeReminder(r.id);
    } catch (e: any) {
      Alert.alert('完成失败', e.message);
    }
  }

  async function handleDelete(r: HealthReminder) {
    Alert.alert('删除提醒', `确定删除"${r.title}"吗？`, [
      { text: '取消', style: 'cancel' },
      {
        text: '删除',
        style: 'destructive',
        onPress: async () => {
          try {
            await deleteReminder(r.id);
          } catch (e: any) {
            Alert.alert('删除失败', e.message);
          }
        },
      },
    ]);
  }

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <ScrollView
        contentContainerStyle={{ paddingBottom: insets.bottom + spacing['3xl'] }}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.header}>
          <View style={styles.headerRow}>
            <Image source={require('../assets/images/nuzzly-zuhe.png')} style={styles.brandLogo} />
            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => router.push('/notifications')}
              style={styles.actionCircle}
            >
              <Ionicons name="notifications-outline" size={18} color={colors.fg} />
            </TouchableOpacity>
          </View>
        </View>

        <PetChipGroup pets={petChips} selectedId={selectedPet} onSelect={setSelectedPet} />

        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.typeFilter}
        >
          {TYPE_FILTERS.map((t) => {
            const active = typeFilter === t.value;
            return (
              <TouchableOpacity
                key={t.value}
                activeOpacity={0.8}
                onPress={() => setTypeFilter(t.value)}
                style={[styles.typeChip, active && styles.typeChipActive]}
              >
                <Text style={[styles.typeChipText, active && styles.typeChipTextActive]}>
                  {t.label}
                </Text>
              </TouchableOpacity>
            );
          })}
        </ScrollView>

        <View style={styles.remindersList}>
          {loading ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyText}>加载中…</Text>
            </View>
          ) : filteredReminders.length === 0 ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyIcon}>🔔</Text>
              <Text style={styles.emptyTitle}>暂无健康提醒</Text>
              <Text style={styles.emptyDesc}>点击右下角 + 添加提醒</Text>
            </View>
          ) : (
            filteredReminders.map((r) => (
              <View
                key={r.id}
                style={[
                  styles.reminderCard,
                  r.is_completed && styles.completedCard,
                  isOverdue(r) && !r.is_completed && styles.overdueCard,
                ]}
              >
                <View style={[styles.reminderIcon, { backgroundColor: TYPE_BG[r.reminder_type] }]}>
                  <Text style={styles.reminderIconText}>{TYPE_ICON[r.reminder_type] || '📌'}</Text>
                </View>
                <View style={styles.reminderBody}>
                  <Text style={styles.reminderTitle}>{r.title}</Text>
                  <View style={styles.reminderMeta}>
                    <View style={styles.typeTag}>
                      <Text style={styles.typeTagText}>{TYPE_LABEL[r.reminder_type]}</Text>
                    </View>
                    {r.repeat_interval && r.repeat_interval !== 'none' ? (
                      <View style={styles.repeatTag}>
                        <Text style={styles.repeatTagText}>
                          🔁 {REPEAT_LABEL[r.repeat_interval]}
                        </Text>
                      </View>
                    ) : null}
                  </View>
                  {r.description ? <Text style={styles.reminderDesc}>{r.description}</Text> : null}
                  <Text
                    style={[
                      styles.reminderDate,
                      isOverdue(r) && !r.is_completed && styles.reminderDateOverdue,
                    ]}
                  >
                    {isOverdue(r) && !r.is_completed ? '已过期 · ' : ''}
                    {formatDate(r.due_date)}
                  </Text>
                </View>
                <View style={styles.reminderActions}>
                  {!r.is_completed ? (
                    <TouchableOpacity
                      activeOpacity={0.7}
                      onPress={() => handleComplete(r)}
                      style={[styles.actionBtn, styles.doneBtn]}
                    >
                      <Ionicons name="checkmark" size={16} color={colors.success} />
                    </TouchableOpacity>
                  ) : null}
                  <TouchableOpacity
                    activeOpacity={0.7}
                    onPress={() => handleDelete(r)}
                    style={[styles.actionBtn, styles.delBtn]}
                  >
                    <Ionicons name="close" size={14} color={colors.muted} />
                  </TouchableOpacity>
                </View>
              </View>
            ))
          )}
        </View>
      </ScrollView>

      <TouchableOpacity
        activeOpacity={0.8}
        onPress={() => router.push({ pathname: '/health-reminders/create', params: { petId: selectedPet } })}
        style={[styles.fab, { bottom: 24 + insets.bottom }]}
      >
        <Ionicons name="add" size={24} color="#fff" />
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    paddingHorizontal: spacing.pageX,
    paddingTop: 4,
    paddingBottom: 0,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandLogo: {
    height: 32,
    width: 120,
    resizeMode: 'contain',
  },
  actionCircle: {
    width: 41.31,
    height: 41.31,
    borderRadius: 999,
    backgroundColor: colors.card,
    ...shadows.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeFilter: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: spacing.pageX,
    paddingTop: spacing.md,
  },
  typeChip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: radius.pill,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  typeChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  typeChipText: {
    fontSize: 12,
    fontWeight: typography.weights.medium,
    color: colors.muted,
  },
  typeChipTextActive: {
    color: colors.card,
  },
  remindersList: {
    paddingHorizontal: 20,
    paddingTop: spacing.md,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  emptyIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
    marginBottom: 4,
  },
  emptyDesc: {
    fontSize: 13,
    color: colors.muted,
  },
  emptyText: {
    fontSize: 14,
    color: colors.muted,
  },
  reminderCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 16,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.card,
    marginBottom: 10,
  },
  completedCard: {
    opacity: 0.5,
  },
  overdueCard: {
    borderColor: colors.danger,
  },
  reminderIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  reminderIconText: {
    fontSize: 20,
  },
  reminderBody: {
    flex: 1,
    minWidth: 0,
  },
  reminderTitle: {
    fontSize: 15,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
    marginBottom: 4,
  },
  reminderMeta: {
    flexDirection: 'row',
    gap: 6,
    flexWrap: 'wrap',
    marginBottom: 4,
  },
  typeTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  typeTagText: {
    fontSize: 10,
    color: colors.muted,
    fontWeight: typography.weights.medium,
  },
  repeatTag: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.primaryBg,
  },
  repeatTagText: {
    fontSize: 10,
    color: colors.primary,
    fontWeight: typography.weights.medium,
  },
  reminderDesc: {
    fontSize: 12,
    color: colors.muted,
    marginBottom: 4,
    lineHeight: 16,
  },
  reminderDate: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: typography.weights.medium,
  },
  reminderDateOverdue: {
    color: colors.danger,
  },
  reminderActions: {
    flexDirection: 'column',
    gap: 6,
    flexShrink: 0,
  },
  actionBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneBtn: {
    backgroundColor: 'rgba(108,138,105,0.1)',
  },
  delBtn: {
    backgroundColor: 'rgba(255,59,48,0.06)',
  },
  fab: {
    position: 'absolute',
    right: 20,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.primary,
    ...shadows.btn,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
});
