// ios-app-frontend/src/views/ProductIngredients.vue
<template>
  <div class="app-shell">
    <PageHeader title="成分分析" />

    <!-- 加载态 -->
    <div v-if="loading" class="skeleton-list">
      <div class="ingredient-skeleton skeleton" v-for="i in 5" :key="i">
        <div class="shimmer-line w60"></div>
        <div class="shimmer-line w40"></div>
      </div>
    </div>

    <!-- 空状态 -->
    <div v-else-if="ingredients.length === 0" class="empty-state">
      <div class="empty-icon">📊</div>
      <p class="empty-text">暂无成分数据</p>
    </div>

    <!-- 成分列表 -->
    <div v-else class="ingredients-container">
      <!-- 营养摘要 -->
      <div class="nutrition-summary" v-if="summary">
        <div class="summary-title">营养摘要</div>
        <div class="summary-grid">
          <div class="summary-item">
            <span class="summary-value">{{ summary.totalProtein }}%</span>
            <span class="summary-label">蛋白质</span>
          </div>
          <div class="summary-item">
            <span class="summary-value">{{ summary.totalFat }}%</span>
            <span class="summary-label">脂肪</span>
          </div>
          <div class="summary-item">
            <span class="summary-value">{{ summary.totalCarbs }}%</span>
            <span class="summary-label">碳水</span>
          </div>
          <div class="summary-item">
            <span class="summary-value">{{ summary.totalFiber }}%</span>
            <span class="summary-label">纤维</span>
          </div>
        </div>
        <div class="summary-tags">
          <span v-if="summary.hasNovelProtein" class="tag tag-novel">新型蛋白</span>
          <span v-if="summary.isGrainFree" class="tag tag-grainfree">无谷</span>
        </div>
      </div>

      <!-- 成分列表 -->
      <div class="section-title">成分列表 ({{ ingredients.length }})</div>
      <div class="ingredient-list">
        <div v-for="ing in ingredients" :key="ing.id" class="ingredient-item">
          <div class="ing-color" :style="{ background: getTypeColor(ing.ingredient_type) }"></div>
          <div class="ing-info">
            <div class="ing-name">{{ ing.ingredient_name }}</div>
            <div class="ing-type">{{ getTypeLabel(ing.ingredient_type) }}</div>
          </div>
          <div class="ing-percent">{{ ing.percentage }}%</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useProductIngredients } from '../composables/useProductIngredients'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const productId = ref(route.query.product || '')

const { ingredients, loading, fetchIngredients, calculateNutritionSummary, getIngredientTypeLabel, getIngredientTypeColor } = useProductIngredients()

const summary = computed(() => calculateNutritionSummary(ingredients.value))

onMounted(() => {
  if (productId.value) {
    fetchIngredients(productId.value)
  }
})

function getTypeLabel(type) {
  return getIngredientTypeLabel(type)
}

function getTypeColor(type) {
  return getIngredientTypeColor(type)
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; }
.ingredients-container { padding: 16px 0; }
.nutrition-summary { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 20px; }
.summary-title { font-size: 15px; font-weight: 600; margin-bottom: 12px; }
.summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; text-align: center; }
.summary-value { display: block; font-size: 20px; font-weight: 600; color: #ff6b4a; }
.summary-label { font-size: 12px; color: #999; }
.summary-tags { display: flex; gap: 8px; margin-top: 12px; }
.tag { font-size: 11px; padding: 4px 10px; border-radius: 10px; }
.tag-novel { background: #e8f5e9; color: #2e7d32; }
.tag-grainfree { background: #e3f2fd; color: #1976d2; }
.section-title { font-size: 15px; font-weight: 600; margin-bottom: 12px; }
.ingredient-list { background: #fff; border-radius: 12px; overflow: hidden; }
.ingredient-item { display: flex; align-items: center; gap: 12px; padding: 12px 16px; border-bottom: 1px solid #f5f5f5; }
.ing-color { width: 4px; height: 32px; border-radius: 2px; }
.ing-info { flex: 1; }
.ing-name { font-size: 14px; color: #333; }
.ing-type { font-size: 12px; color: #999; }
.ing-percent { font-size: 15px; font-weight: 600; color: #333; }
</style>

// nuzzly-expo/app/product-ingredients.tsx
import { useEffect, useMemo } from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';
import PageHeader from '../src/components/PageHeader';
import EmptyState from '../src/components/EmptyState';
import { useProductIngredients } from '../src/hooks/useProductIngredients';

export default function ProductIngredientsScreen() {
  const insets = useSafeAreaInsets();
  const { product } = useLocalSearchParams<{ product?: string }>();
  const {
    ingredients,
    loading,
    fetchIngredients,
    calculateNutritionSummary,
    getIngredientTypeLabel,
    getIngredientTypeColor,
  } = useProductIngredients();

  useEffect(() => {
    if (product) fetchIngredients(product);
  }, [product]);

  const summary = useMemo(() => calculateNutritionSummary(ingredients), [ingredients]);

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="成分分析" />
      <ScrollView
        style={styles.container}
        contentContainerStyle={{ paddingBottom: insets.bottom + spacing.xl }}
        showsVerticalScrollIndicator={false}
      >
        {loading ? (
          <View style={styles.skeletonList}>
            {[1, 2, 3, 4, 5].map((i) => (
              <View key={i} style={styles.ingredientSkeleton}>
                <View style={[styles.shimmerLine, { width: '60%' }]} />
                <View style={[styles.shimmerLine, { width: '40%' }]} />
              </View>
            ))}
          </View>
        ) : ingredients.length === 0 ? (
          <EmptyState icon="📊" title="暂无成分数据" />
        ) : (
          <View style={styles.content}>
            <View style={styles.nutritionSummary}>
              <Text style={styles.summaryTitle}>营养摘要</Text>
              <View style={styles.summaryGrid}>
                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>{summary.totalProtein.toFixed(1)}%</Text>
                  <Text style={styles.summaryLabel}>蛋白质</Text>
                </View>
                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>{summary.totalFat.toFixed(1)}%</Text>
                  <Text style={styles.summaryLabel}>脂肪</Text>
                </View>
                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>{summary.totalCarbs.toFixed(1)}%</Text>
                  <Text style={styles.summaryLabel}>碳水</Text>
                </View>
                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>{summary.totalFiber.toFixed(1)}%</Text>
                  <Text style={styles.summaryLabel}>纤维</Text>
                </View>
              </View>
              <View style={styles.summaryTags}>
                {summary.hasNovelProtein && (
                  <Text style={[styles.tag, styles.tagNovel]}>新型蛋白</Text>
                )}
                {summary.isGrainFree && (
                  <Text style={[styles.tag, styles.tagGrainFree]}>无谷</Text>
                )}
              </View>
            </View>

            <Text style={styles.sectionTitle}>成分列表 ({ingredients.length})</Text>
            <View style={styles.ingredientList}>
              {ingredients.map((ing) => (
                <View key={ing.id} style={styles.ingredientItem}>
                  <View
                    style={[
                      styles.ingColor,
                      { backgroundColor: getIngredientTypeColor(ing.ingredient_type) },
                    ]}
                  />
                  <View style={styles.ingInfo}>
                    <Text style={styles.ingName}>{ing.ingredient_name}</Text>
                    <Text style={styles.ingType}>
                      {getIngredientTypeLabel(ing.ingredient_type)}
                    </Text>
                  </View>
                  <Text style={styles.ingPercent}>{ing.percentage ?? '-'}%</Text>
                </View>
              ))}
            </View>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.pageX,
  },
  skeletonList: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  ingredientSkeleton: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  shimmerLine: {
    height: 14,
    borderRadius: 7,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  content: {
    paddingVertical: spacing.lg,
  },
  nutritionSummary: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  summaryTitle: {
    fontSize: typography.sizes.md,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
    marginBottom: spacing.md,
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: typography.weights.bold,
    color: colors.primary,
  },
  summaryLabel: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginTop: 2,
  },
  summaryTags: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  tag: {
    fontSize: typography.sizes.xs,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    fontWeight: typography.weights.medium,
  },
  tagNovel: {
    backgroundColor: 'rgba(108,138,105,0.12)',
    color: colors.success,
  },
  tagGrainFree: {
    backgroundColor: 'rgba(0,122,255,0.12)',
    color: colors.info,
  },
  sectionTitle: {
    fontSize: typography.sizes.md,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
    marginBottom: spacing.md,
  },
  ingredientList: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  ingredientItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  ingColor: {
    width: 4,
    height: 32,
    borderRadius: 2,
  },
  ingInfo: {
    flex: 1,
  },
  ingName: {
    fontSize: typography.sizes.base,
    color: colors.fg,
    fontWeight: typography.weights.medium,
  },
  ingType: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginTop: 2,
  },
  ingPercent: {
    fontSize: typography.sizes.md,
    fontWeight: typography.weights.semibold,
    color: colors.fg,
  },
});
