// ios-app-frontend/src/views/ProductMetrics.vue
<template>
  <div class="app-shell">
    <PageHeader title="产品指标" />

    <!-- 加载态 -->
    <div v-if="loading" class="skeleton-list">
      <div class="metric-skeleton skeleton" v-for="i in 3" :key="i">
        <div class="shimmer-line w60"></div>
        <div class="shimmer-line w40"></div>
      </div>
    </div>

    <!-- 空状态 -->
    <div v-else-if="productMetrics.length === 0" class="empty-state">
      <div class="empty-icon">📊</div>
      <p class="empty-text">暂无产品指标</p>
    </div>

    <!-- 指标列表 -->
    <div v-else class="metrics-list">
      <div v-for="metric in productMetrics" :key="metric.id" class="metric-card">
        <div class="metric-header">
          <span class="metric-date">{{ formatDate(metric.date) }}</span>
          <span class="risk-badge" :class="getRiskClass(metric.risk_score)">
            {{ getRiskLabel(metric.risk_score) }}
          </span>
        </div>
        <div class="metric-grid">
          <div class="metric-item">
            <span class="metric-label">评分</span>
            <span class="metric-value">{{ metric.average_rating || '-' }}</span>
          </div>
          <div class="metric-item">
            <span class="metric-label">评价数</span>
            <span class="metric-value">{{ metric.review_count || 0 }}</span>
          </div>
          <div class="metric-item">
            <span class="metric-label">复购率</span>
            <span class="metric-value">{{ metric.repurchase_rate ? metric.repurchase_rate + '%' : '-' }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useProductMetrics } from '../composables/useProductMetrics'
import PageHeader from '../components/PageHeader.vue'

const route = useRoute()
const productId = ref(route.query.product || '')

const { productMetrics, loading, fetchProductMetrics, getRiskLevel } = useProductMetrics()

onMounted(() => {
  if (productId.value) fetchProductMetrics(productId.value)
})

function getRiskLabel(score) {
  if (score == null) return '-'
  const level = getRiskLevel(score)
  return level.label
}

function getRiskClass(score) {
  if (score == null) return ''
  if (score >= 0.7) return 'risk-high'
  if (score >= 0.4) return 'risk-medium'
  return 'risk-low'
}

function formatDate(dateStr) {
  const d = new Date(dateStr)
  return `${d.getMonth() + 1}/${d.getDate()}`
}
</script>

<style scoped>
.app-shell { min-height: 100vh; background: #f5f5f5; padding: 0 16px; }
.empty-state { text-align: center; padding: 60px 20px; }
.empty-icon { font-size: 48px; margin-bottom: 12px; }
.empty-text { font-size: 16px; color: #333; }
.metrics-list { padding: 16px 0; }
.metric-card { background: #fff; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
.metric-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
.metric-date { font-size: 14px; color: #666; }
.risk-badge { font-size: 12px; padding: 4px 10px; border-radius: 10px; }
.risk-low { background: #e8f5e9; color: #2e7d32; }
.risk-medium { background: #fff3e0; color: #f57c00; }
.risk-high { background: #ffebee; color: #c62828; }
.metric-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; text-align: center; }
.metric-label { display: block; font-size: 12px; color: #999; }
.metric-value { font-size: 18px; font-weight: 600; color: #333; }
</style>

// nuzzly-expo/app/product-metrics.tsx
import { useEffect, useMemo } from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, spacing, radius, shadows, typography } from '../src/theme/tokens';
import PageHeader from '../src/components/PageHeader';
import EmptyState from '../src/components/EmptyState';
import { useProductMetrics, ProductMetric } from '../src/hooks/useProductMetrics';

function getRiskClass(score?: number) {
  if (score == null) return 'none';
  if (score >= 0.7) return 'high';
  if (score >= 0.4) return 'medium';
  return 'low';
}

function formatDate(dateStr?: string) {
  if (!dateStr) return '--';
  const d = new Date(dateStr);
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

export default function ProductMetricsScreen() {
  const insets = useSafeAreaInsets();
  const { product } = useLocalSearchParams<{ product?: string }>();
  const { productMetrics, loading, fetchProductMetrics, getRiskLevel } = useProductMetrics();

  useEffect(() => {
    if (product) fetchProductMetrics(product);
  }, [product]);

  const riskBadgeStyle = (score?: number) => {
    const cls = getRiskClass(score);
    return cls === 'high'
      ? styles.riskHigh
      : cls === 'medium'
      ? styles.riskMedium
      : cls === 'low'
      ? styles.riskLow
      : styles.riskNone;
  };

  const renderMetric = (metric: ProductMetric) => {
    const level = metric.risk_score != null ? getRiskLevel(metric.risk_score) : null;
    return (
      <View key={metric.id} style={styles.metricCard}>
        <View style={styles.metricHeader}>
          <Text style={styles.metricDate}>{formatDate(metric.date)}</Text>
          <Text style={[styles.riskBadge, riskBadgeStyle(metric.risk_score)]}>
            {level?.label || '-'}
          </Text>
        </View>
        <View style={styles.metricGrid}>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>评分</Text>
            <Text style={styles.metricValue}>{metric.average_rating ?? '-'}</Text>
          </View>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>评价数</Text>
            <Text style={styles.metricValue}>{metric.review_count ?? 0}</Text>
          </View>
          <View style={styles.metricItem}>
            <Text style={styles.metricLabel}>复购率</Text>
            <Text style={styles.metricValue}>
              {metric.repurchase_rate != null ? `${metric.repurchase_rate}%` : '-'}
            </Text>
          </View>
        </View>
      </View>
    );
  };

  return (
    <View style={[styles.shell, { paddingTop: insets.top }]}>
      <PageHeader title="产品指标" />
      <ScrollView
        style={styles.container}
        contentContainerStyle={{ paddingBottom: insets.bottom + spacing.xl }}
        showsVerticalScrollIndicator={false}
      >
        {loading ? (
          <View style={styles.skeletonList}>
            {[1, 2, 3].map((i) => (
              <View key={i} style={styles.metricSkeleton}>
                <View style={[styles.shimmerLine, { width: '60%' }]} />
                <View style={[styles.shimmerLine, { width: '40%' }]} />
              </View>
            ))}
          </View>
        ) : productMetrics.length === 0 ? (
          <EmptyState icon="📊" title="暂无产品指标" />
        ) : (
          <View style={styles.metricsList}>
            {productMetrics.map(renderMetric)}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    flex: 1,
    paddingHorizontal: spacing.pageX,
  },
  skeletonList: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  metricSkeleton: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  shimmerLine: {
    height: 14,
    borderRadius: 7,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  metricsList: {
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  metricCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  metricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  metricDate: {
    fontSize: typography.sizes.base,
    color: colors.muted,
  },
  riskBadge: {
    fontSize: typography.sizes.xs,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    fontWeight: typography.weights.medium,
  },
  riskHigh: {
    backgroundColor: 'rgba(255,59,48,0.12)',
    color: colors.danger,
  },
  riskMedium: {
    backgroundColor: 'rgba(245,166,35,0.12)',
    color: colors.warning,
  },
  riskLow: {
    backgroundColor: 'rgba(108,138,105,0.12)',
    color: colors.success,
  },
  riskNone: {
    backgroundColor: 'rgba(0,0,0,0.04)',
    color: colors.muted,
  },
  metricGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  metricItem: {
    flex: 1,
    alignItems: 'center',
  },
  metricLabel: {
    fontSize: typography.sizes.xs,
    color: colors.muted,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: typography.weights.bold,
    color: colors.fg,
  },
});
