// ios-app-frontend/src/components/OnboardingGuide.vue
<template>
  <div v-if="!dismissed" class="onboard-card anim-fade-up">
    <div class="onboard-header">
      <span class="onboard-icon">✨</span>
      <h2 class="onboard-title">3 步开始精准推荐</h2>
    </div>
    <div class="onboard-steps">
      <div v-for="(s, i) in steps" :key="i" class="onboard-step">
        <div class="step-num">{{ i + 1 }}</div>
        <div class="step-body">
          <div class="step-icon" :style="{ background: s.color + '15', color: s.color }">{{ s.emoji }}</div>
          <div class="step-text">
            <div class="step-title">{{ s.title }}</div>
            <div class="step-desc">{{ s.desc }}</div>
          </div>
        </div>
        <button class="step-btn" :style="{ background: s.color }" @click="$router.push(s.href)">{{ s.action }}</button>
      </div>
    </div>
    <div class="onboard-footer">
      <span class="onboard-hint">✓ 创建档案后即可获得个性化推荐</span>
      <button class="onboard-skip" @click="dismissed = true">稍后再说</button>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const dismissed = ref(false)

const steps = [
  { emoji: '🐱', title: '创建宠物档案', desc: '记录品种、年龄、肠胃状况', action: '去创建', href: '/pet/quick', color: '#FF7A59' },
  { emoji: '🍖', title: '记录饮食', desc: '记录每日喂食，追踪长期效果', action: '去记录', href: '/record/create?type=diet', color: '#ff9500' },
  { emoji: '💡', title: '获取推荐', desc: '基于档案获得个性化猫粮推荐', action: '去查看', href: '/butler', color: '#8B5E46' },
]
</script>

<style scoped>
.onboard-card{margin:0 20px;padding:20px;background:linear-gradient(135deg,rgba(255,122,89,.05),rgba(255,149,0,.05));border-radius:24px;border:1px solid var(--border);box-shadow:var(--shadow-card)}
.onboard-header{display:flex;align-items:center;gap:8px;margin-bottom:16px}
.onboard-icon{font-size:20px}
.onboard-title{font-size:17px;font-weight:700;color:var(--fg)}
.onboard-steps{display:flex;flex-direction:column;gap:12px}
.onboard-step{display:flex;align-items:center;gap:12px;padding:14px;background:var(--card);border-radius:16px;border:1px solid var(--border);position:relative}
.step-num{position:absolute;top:-6px;left:-6px;width:20px;height:20px;border-radius:50%;background:var(--brown);color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center}
.step-body{display:flex;align-items:center;gap:10px;flex:1;min-width:0}
.step-icon{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:18px;flex-shrink:0}
.step-text{min-width:0}
.step-title{font-size:14px;font-weight:600;color:var(--fg)}
.step-desc{font-size:11px;color:var(--muted);margin-top:2px}
.step-btn{padding:6px 14px;border-radius:var(--radius-btn);color:#fff;font-size:12px;font-weight:500;border:none;cursor:pointer;white-space:nowrap;flex-shrink:0}
.step-btn:active{transform:scale(.95)}
.onboard-footer{display:flex;align-items:center;justify-content:space-between;margin-top:14px}
.onboard-hint{font-size:11px;color:var(--muted)}
.onboard-skip{background:none;border:none;font-size:12px;color:var(--muted);cursor:pointer;padding:4px 8px}
.onboard-skip:active{color:var(--fg)}
@keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
.anim-fade-up{opacity:0;animation:fadeUp .6s cubic-bezier(.22,1,.36,1) forwards}
</style>

// web/components/dashboard/onboarding-guide.tsx
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { PawPrint, ArrowRight, Check, Sparkles, Cat, Heart, Utensils } from "lucide-react"
import Link from "next/link"

const steps = [
  {
    icon: <Cat className="size-6" />,
    title: "创建宠物档案",
    description: "记录品种、年龄、体重、肠胃状况，为精准推荐打基础",
    action: "去创建",
    href: "/dashboard/pets/new",
    color: "#FF7A59",
  },
  {
    icon: <Utensils className="size-6" />,
    title: "记录饮食",
    description: "记录每日喂食情况，系统会追踪长期效果",
    action: "去记录",
    href: "/dashboard/pets",
    color: "#ff9500",
  },
  {
    icon: <Heart className="size-6" />,
    title: "获取推荐",
    description: "基于宠物档案和社区数据，获得个性化猫粮推荐",
    action: "去查看",
    href: "/dashboard/recommendations",
    color: "#111111",
  },
]

export function OnboardingGuide() {
  const [dismissed, setDismissed] = useState(false)

  if (dismissed) return null

  return (
    <Card className="rounded-[20px] border-[rgba(0,0,0,0.05)] bg-gradient-to-br from-[#FF7A59]/5 to-[#ff9500]/5 p-6">
      <div className="mb-5 flex items-center gap-2">
        <Sparkles className="size-5 text-[#FF7A59]" />
        <h2 className="text-[18px] font-semibold text-[#111111]">欢迎！3 步开始精准推荐</h2>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        {steps.map((step, i) => (
          <div key={i} className="relative rounded-[16px] border border-[rgba(0,0,0,0.05)] bg-white p-5">
            {/* Step number */}
            <div className="absolute -top-2.5 -left-2.5 flex size-6 items-center justify-center rounded-full bg-[#FF7A59] text-[12px] font-bold text-white">
              {i + 1}
            </div>

            <div className="mb-3 flex size-12 items-center justify-center rounded-xl" style={{ backgroundColor: `${step.color}15`, color: step.color }}>
              {step.icon}
            </div>

            <h3 className="text-[15px] font-semibold text-[#111111]">{step.title}</h3>
            <p className="mt-1.5 text-[13px] text-[#6B6B6B]">{step.description}</p>

            <Button asChild className="mt-4 h-9 w-full rounded-full text-[13px]" style={{ backgroundColor: step.color }}>
              <Link href={step.href}>
                {step.action} <ArrowRight className="ml-1 size-3.5" />
              </Link>
            </Button>
          </div>
        ))}
      </div>

      <div className="mt-5 flex items-center justify-between">
        <div className="flex items-center gap-2 text-[12px] text-[#6B6B6B]">
          <Check className="size-3.5 text-[#FF7A59]" />
          <span>创建档案后即可获得个性化推荐</span>
        </div>
        <button
          type="button"
          onClick={() => setDismissed(true)}
          className="text-[12px] text-[#6B6B6B] hover:text-[#111111]"
        >
          稍后再说
        </button>
      </div>
    </Card>
  )
}
